<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>frames</key>
        <dict>
            <key>boom1.png</key>
            <dict>
                <key>frame</key>
                <string>{{458,146},{50,57}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{50,57}}</string>
                <key>sourceSize</key>
                <string>{50,57}</string>
            </dict>
            <key>boom2.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,296},{98,94}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{98,94}}</string>
                <key>sourceSize</key>
                <string>{98,94}</string>
            </dict>
            <key>boom3.png</key>
            <dict>
                <key>frame</key>
                <string>{{167,2},{141,157}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{141,157}}</string>
                <key>sourceSize</key>
                <string>{141,157}</string>
            </dict>
            <key>boom4.png</key>
            <dict>
                <key>frame</key>
                <string>{{326,2},{151,142}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{151,142}}</string>
                <key>sourceSize</key>
                <string>{151,142}</string>
            </dict>
            <key>boom5.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,2},{163,156}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{163,156}}</string>
                <key>sourceSize</key>
                <string>{163,156}</string>
            </dict>
            <key>boom6.png</key>
            <dict>
                <key>frame</key>
                <string>{{318,146},{138,133}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{138,133}}</string>
                <key>sourceSize</key>
                <string>{138,133}</string>
            </dict>
            <key>boom7.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,160},{148,134}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{148,134}}</string>
                <key>sourceSize</key>
                <string>{148,134}</string>
            </dict>
            <key>boom8.png</key>
            <dict>
                <key>frame</key>
                <string>{{167,145},{149,134}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{149,134}}</string>
                <key>sourceSize</key>
                <string>{149,134}</string>
            </dict>
        </dict>
        <key>metadata</key>
        <dict>
            <key>format</key>
            <integer>2</integer>
            <key>realTextureFileName</key>
            <string>boom.png</string>
            <key>size</key>
            <string>{512,512}</string>
            <key>smartupdate</key>
            <string>$TexturePacker:SmartUpdate:d3790915796ae7e0e9af5898578adef7$</string>
            <key>textureFileName</key>
            <string>boom.png</string>
        </dict>
    </dict>
</plist>
