<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>frames</key>
        <dict>
            <key>bg1.png</key>
            <dict>
                <key>frame</key>
                <string>{{1286,204},{640,200}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{640,200}}</string>
                <key>sourceSize</key>
                <string>{640,200}</string>
            </dict>
            <key>bg2.png</key>
            <dict>
                <key>frame</key>
                <string>{{644,204},{640,200}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{640,200}}</string>
                <key>sourceSize</key>
                <string>{640,200}</string>
            </dict>
            <key>bg3.png</key>
            <dict>
                <key>frame</key>
                <string>{{1286,2},{640,200}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{640,200}}</string>
                <key>sourceSize</key>
                <string>{640,200}</string>
            </dict>
            <key>bg4.png</key>
            <dict>
                <key>frame</key>
                <string>{{644,2},{640,200}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{640,200}}</string>
                <key>sourceSize</key>
                <string>{640,200}</string>
            </dict>
            <key>bg5.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,204},{640,200}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{640,200}}</string>
                <key>sourceSize</key>
                <string>{640,200}</string>
            </dict>
            <key>bg6.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,2},{640,200}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{640,200}}</string>
                <key>sourceSize</key>
                <string>{640,200}</string>
            </dict>
        </dict>
        <key>metadata</key>
        <dict>
            <key>format</key>
            <integer>2</integer>
            <key>realTextureFileName</key>
            <string>map.png</string>
            <key>size</key>
            <string>{1928,406}</string>
            <key>smartupdate</key>
            <string>$TexturePacker:SmartUpdate:a35c473c85ff530995db5c6de5a0e3c3$</string>
            <key>textureFileName</key>
            <string>map.png</string>
        </dict>
    </dict>
</plist>
