<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>frames</key>
        <dict>
            <key>anchor1.png</key>
            <dict>
                <key>frame</key>
                <string>{{604,175},{150,72}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{150,72}}</string>
                <key>sourceSize</key>
                <string>{150,72}</string>
            </dict>
            <key>anchor2.png</key>
            <dict>
                <key>frame</key>
                <string>{{530,249},{174,73}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{174,73}}</string>
                <key>sourceSize</key>
                <string>{174,73}</string>
            </dict>
            <key>anchor3.png</key>
            <dict>
                <key>frame</key>
                <string>{{530,2},{244,72}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{244,72}}</string>
                <key>sourceSize</key>
                <string>{244,72}</string>
            </dict>
            <key>cat.png</key>
            <dict>
                <key>frame</key>
                <string>{{689,2},{66,114}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{66,114}}</string>
                <key>sourceSize</key>
                <string>{66,114}</string>
            </dict>
            <key>end.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,338},{620,159}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{620,159}}</string>
                <key>sourceSize</key>
                <string>{620,159}</string>
            </dict>
            <key>fish.png</key>
            <dict>
                <key>frame</key>
                <string>{{624,433},{117,58}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{117,58}}</string>
                <key>sourceSize</key>
                <string>{117,58}</string>
            </dict>
            <key>help.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,2},{526,334}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{526,334}}</string>
                <key>sourceSize</key>
                <string>{526,334}</string>
            </dict>
            <key>scoreText.png</key>
            <dict>
                <key>frame</key>
                <string>{{604,2},{171,83}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{171,83}}</string>
                <key>sourceSize</key>
                <string>{171,83}</string>
            </dict>
            <key>xuanwo.png</key>
            <dict>
                <key>frame</key>
                <string>{{624,324},{102,107}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{102,107}}</string>
                <key>sourceSize</key>
                <string>{102,107}</string>
            </dict>
        </dict>
        <key>metadata</key>
        <dict>
            <key>format</key>
            <integer>2</integer>
            <key>realTextureFileName</key>
            <string>ui_12.png</string>
            <key>size</key>
            <string>{757,499}</string>
            <key>smartupdate</key>
            <string>$TexturePacker:SmartUpdate:e200ab4f2eb694cc9378494de7da14aa$</string>
            <key>textureFileName</key>
            <string>ui_12.png</string>
        </dict>
    </dict>
</plist>
