<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>frames</key>
        <dict>
            <key>bottle1.png</key>
            <dict>
                <key>frame</key>
                <string>{{570,644},{170,118}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{170,118}}</string>
                <key>sourceSize</key>
                <string>{170,118}</string>
            </dict>
            <key>bottle2.png</key>
            <dict>
                <key>frame</key>
                <string>{{375,639},{193,109}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{193,109}}</string>
                <key>sourceSize</key>
                <string>{193,109}</string>
            </dict>
            <key>btn_start3.png</key>
            <dict>
                <key>frame</key>
                <string>{{936,375},{371,73}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{371,73}}</string>
                <key>sourceSize</key>
                <string>{371,73}</string>
            </dict>
            <key>btn_start33.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,714},{371,73}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{371,73}}</string>
                <key>sourceSize</key>
                <string>{371,73}</string>
            </dict>
            <key>btn_start4.png</key>
            <dict>
                <key>frame</key>
                <string>{{936,2},{371,73}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{371,73}}</string>
                <key>sourceSize</key>
                <string>{371,73}</string>
            </dict>
            <key>btn_start44.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,639},{371,73}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{371,73}}</string>
                <key>sourceSize</key>
                <string>{371,73}</string>
            </dict>
            <key>over.png</key>
            <dict>
                <key>frame</key>
                <string>{{2,2},{621,635}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{0,0},{621,635}}</string>
                <key>sourceSize</key>
                <string>{621,635}</string>
            </dict>
            <key>role1.png</key>
            <dict>
                <key>frame</key>
                <string>{{926,748},{89,79}}</string>
                <key>offset</key>
                <string>{0,-4}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{7,15},{89,79}}</string>
                <key>sourceSize</key>
                <string>{103,101}</string>
            </dict>
            <key>role2.png</key>
            <dict>
                <key>frame</key>
                <string>{{742,741},{89,79}}</string>
                <key>offset</key>
                <string>{0,-4}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{7,15},{89,79}}</string>
                <key>sourceSize</key>
                <string>{103,101}</string>
            </dict>
            <key>role3.png</key>
            <dict>
                <key>frame</key>
                <string>{{742,644},{89,95}}</string>
                <key>offset</key>
                <string>{0,3}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{7,0},{89,95}}</string>
                <key>sourceSize</key>
                <string>{103,101}</string>
            </dict>
            <key>role4.png</key>
            <dict>
                <key>frame</key>
                <string>{{833,644},{93,91}}</string>
                <key>offset</key>
                <string>{2,2}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{7,3},{93,91}}</string>
                <key>sourceSize</key>
                <string>{103,101}</string>
            </dict>
            <key>role5.png</key>
            <dict>
                <key>frame</key>
                <string>{{833,737},{91,79}}</string>
                <key>offset</key>
                <string>{0,-6}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{6,17},{91,79}}</string>
                <key>sourceSize</key>
                <string>{103,101}</string>
            </dict>
            <key>title_box.png</key>
            <dict>
                <key>frame</key>
                <string>{{625,2},{640,309}}</string>
                <key>offset</key>
                <string>{0,0}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{0,0},{640,309}}</string>
                <key>sourceSize</key>
                <string>{640,309}</string>
            </dict>
        </dict>
        <key>metadata</key>
        <dict>
            <key>format</key>
            <integer>2</integer>
            <key>realTextureFileName</key>
            <string>gui.png</string>
            <key>size</key>
            <string>{1017,829}</string>
            <key>smartupdate</key>
            <string>$TexturePacker:SmartUpdate:5edab546e3e15c28b93d474264cb7aa4$</string>
            <key>textureFileName</key>
            <string>gui.png</string>
        </dict>
    </dict>
</plist>
