typeof Mugeda=="undefined"&&(Mugeda={});Mugeda.data=Mugeda.data||{};Mugeda.script=Mugeda.script||[];Mugeda.customScript="";Mugeda.scene=void 0;Mugeda.unzipAniData=function(a){a=MugedaCompress.unzip(a);if(a.script&&a.script.length)a.script=unescape(a.script);return a};Mugeda.getFrameLength=function(a){for(var e=1,c=a.length-1;c>=0;c--)for(var d=a[c],g=d.units.length,f=0;f<g;f++){var j=d.units[f],j=j.frameStart+j.frameCount;e<j&&(e=j)}return e};
Mugeda.getWindowSize=function(){var a=document.documentElement,e=a&&a.clientHeight===0;if(typeof document.clientWidth=="number")return{width:document.clientWidth,height:document.clientHeight};else{if(!e){var e=document,c=e.createElement("div");c.style.height="2500px";e.body.insertBefore(c,e.body.firstChild);var d=e.documentElement.clientHeight>2400;e.body.removeChild(c);e=d}if(e)a=document.body;return{width:a.clientWidth,height:a.clientHeight}}};
Mugeda.updateViewport=function(a,e,c,d){if(typeof _mrmcp=="undefined"||_mrmcp.render_mode!="inline"&&_mrmcp.render_mode!="embedded"){if(c){var g=c.aniData.metadata?c.aniData.metadata.adaptMode:null;if(g=="none"||g==null)if(c.aniData.metadata=c.aniData.metadata||{},g=c.aniData.metadata.adaptMode=d?"none_mobile":"none_pc",!d)document.body.style.overflow="auto";if("contain,cover,width,width2,height,none_mobile,none_pc,fill".split(",").indexOf(g)>-1)a=document.createElement("div"),c.dom.style.position=
"absolute",c.dom.style.overflow="hidden",c.dom.style.left="0",c.dom.style.top="0",c.dom.style.right="0",c.dom.style.bottom="0",c.dom.style.margin="auto",c.dom.appendChild(a),c.dom=a}if(g==="width2")document.body.style.overflow="auto";document.documentElement.style.height="100%";document.body.style.height="100%"}};Mugeda.getCanvas=function(){return document.getElementsByClassName("MugedaStage")[0]};Mugeda.randPlus=0;
Mugeda.guidGen=function(){var a=new Date-new Date("2012/1/1")+""+Math.random().toString().substr(2,4);return Number(a).toString(36)+""+Mugeda.randPlus++};Mugeda.getMugedaObject=function(){return Mugeda.scene};Mugeda.loadUrl=function(a){return MugedaMraid.loadUrl(a)};Mugeda.enable3DRendering=function(a){a==void 0&&(a=false);this.threeDRendering=a};Mugeda.showFPS=function(){Mugeda.FPSMeter=true};Mugeda.enableNonDisplay=function(a){a==void 0&&(a=false);this.nonDisplay=a};
Mugeda.enableFlexibleFrameRate=function(a){a==void 0&&(a=false);this.flexibleFrameRate=a};Mugeda.enablePulseAnimation=function(a){a==void 0&&(a=false);Mugeda.enablePulse=a};
Mugeda.log=function(a){if(!Mugeda.logConsole)Mugeda.logConsole=document.createElement("div"),Mugeda.logConsole.style.display="block",Mugeda.logConsole.style.position="fixed",Mugeda.logConsole.style.background="#000",Mugeda.logConsole.style.color="#FFF",Mugeda.logConsole.style.left=0,Mugeda.logConsole.style.top=0,document.body.appendChild(Mugeda.logConsole);if(typeof a=="string"||a)Mugeda.logConsole.innerHTML=a;return Mugeda.logConsole.innerHTML};Mugeda.getAudioCache=function(a,e){return Mugeda.currentAni.audioBeList[e]};
Mugeda.setTextAsFlexbox=function(){this.textAsFlexbox=true};
window.MugedaCss3=function(a){if(!a){Mugeda.customScript="";var e=function(a){if(/^<.+>$/.test(a))return document.createElement(a.match(/^<(.+)>$/)[1]);else if(/^#.+/.test(a))return document.getElementById(a.match(/^#(.+)/)[1])};e.stage={};e.getAnimation=function(a){return e.stage[a]};e.initAnimation=function(a,e,c,b,m){a=new d(a,e,c,b);Mugeda.currentAni=a;a.initDom(m);return a};e.getCssBackgroundColor=function(a){var l=a.fillInfo;if(l.fillStyle==0)return"rgba("+l.fillColors[0].r+","+l.fillColors[0].g+
","+l.fillColors[0].b+","+l.fillColors[0].a+")";else if(l.fillStyle==1||l.fillStyle==2){var c=l.fillStartPos.x,b=l.fillStartPos.y,d=l.fillEndPos.x,f=l.fillEndPos.y,g=a.rawWidth||a.width,j=a.rawHeight||a.height,a=Math.atan2(f-b,d-c),s=function(a,b,h){return{x:a*Math.cos(h)-b*Math.sin(h),y:a*Math.sin(h)+b*Math.cos(h)}},n=s(0,j,-a).x,x=s(g,j,-a).x,v=s(g,0,-a).x,p=s(c,b,-a).x,r=s(d,f,-a).x,w=Math.max(0,n,x,v),y=Math.min(0,n,x,v),n=function(a,b,h){var e={};e.pm=h;e.r=(b.r-a.r)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.r);
e.g=(b.g-a.g)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.g);e.b=(b.b-a.b)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.b);e.a=(b.a-a.a)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.a);return e},s=function(a,b){return"rgba("+Math.round(a.r)+","+Math.round(a.g)+","+Math.round(a.b)+","+a.a+") "+(b==void 0?a.pm:b)+"%"};if(l.fillStyle==1){l.fillColors.m_operate(function(a){a.pm=100/(w-y)*(p+(r-p)*a.p-y)+0});for(var c=false,u="",d=0;d<l.fillColors.length;d++)if(b=l.fillColors[d],g=b.pm,c)if(g<100){if(u+=", "+s(b),d==l.fillColors.length-
1){u+=", "+s(b,100);break}}else{u+=", "+s(n(b,l.fillColors[d-1],100),100);break}else{if(g<0)if(d<l.fillColors.length-1)if(l.fillColors[d+1].pm<0)continue;else u+=", "+s(n(b,l.fillColors[d+1],0));else u+=", "+s(b,0),u+=", "+s(b,100);else u+=", "+s(b,0),u+=", "+s(b);c=true}u="linear-gradient("+(e.browser.msie?a*180/Math.PI+90:-a*180/Math.PI)+"deg"+u+")"}else if(l.fillStyle==2){a=Math.sqrt(Math.pow(c-d,2)+Math.pow(b-f,2));u="";for(d=0;d<l.fillColors.length;d++)u+=", "+s(l.fillColors[d],l.fillColors[d].p*
100);u="radial-gradient("+c/g*100+"% "+b/j*100+"%, "+a+"px "+a+"px"+u+")"}return e.css3Per?e.css3Per.toLowerCase()+u:u}else return"transparent"};e.handleCapture=function(a){if(!a.redirected&&e.captureObject!=null){var l=document.createEvent("MouseEvents");l.initMouseEvent(a.type,true,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget);l.redirected=true;e.captureObject.object.dispatchEvent(l);a.type=="mouseup"&&e.captureObject&&
e.captureObject.object.m_releasecapture()}};e.getCurrentStyle=function(a,e){if(document.defaultView){var c=document.defaultView.getComputedStyle(a,null);return c?c.getPropertyValue(e):null}else return a.currentStyle[e]};e.getEventPosition=function(a,c,d,b){var f,d=d||1;if(a.changedTouches&&(a=a.changedTouches[0],a==null))return null;f=a.clientX;a=a.clientY;if(c){for(var g=c,q=0,j=0;g&&g.tagName!="BODY";)q+=g.offsetTop,j+=g.offsetLeft,g=g.offsetParent;f=f-j+window.pageXOffset-parseInt(e.getCurrentStyle(c,
"border-left-width"));a=a-q+window.pageYOffset-parseInt(e.getCurrentStyle(c,"border-top-width"))}b&&(f/=d,a/=d);return{x:f,y:a}};var c=window;(function(){var a=c.performance;e.getTime=a&&(a.now||a.webkitNow)?a[a.now?"now":"webkitNow"].bind(a):function(){return+new Date}})();a=navigator.userAgent.toLowerCase();a={version:(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1],safari:/webkit/.test(a),opera:/opera/.test(a),msie:(/msie/.test(a)||/trident/.test(a))&&!/opera/.test(a),mozilla:/mozilla/.test(a)&&
!/(compatible|webkit)/.test(a)&&!/trident/.test(a)};e.browser=a;if(a.safari)e.css3Per="-webkit-",e.css3PerH="webkit";else if(a.opera)e.css3Per="-o-",e.css3PerH="o";else if(a.msie)e.css3Per="",e.css3PerH="";else if(a.mozilla)e.css3Per="-moz-",e.css3PerH="Moz";var d=function(a,e,c,b){this.aniData=a=a.zip?Mugeda.unzipAniData(a):a;this.title=a.title;this.width=a.width;this.height=a.height;this.dom=c;this.rate=a.rate;this.frameTime=1E3/a.rate;this.frameTimeString=this.frameTime+"ms";this.sceneHash={};
this.mainSceneFrameUnitHash={};this.zoneCached={};this.event={};this.stopRedraw=false;this.resDir=b;this.scriptFile="string"==typeof e?e:null;this.frameParamCache={};this.paramUpdatePool={};this.audioList={};this.scriptList=[]};d.prototype.getScene=function(){return this.scene};var g={mousedown:1,mouseup:1,click:1,dblclick:1,mouseover:1,mouseout:1,mousemove:1,touchstart:1,touchmove:1,touchend:1,inputstart:2,inputmove:2,inputend:2},f=navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||
navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i);window.navigator.userAgent.indexOf("Android");var j=function(a,c,d){a=="inputstart"?a=f?"touchstart":"mousedown":a=="inputmove"?a=f?"touchmove":"mousemove":a=="inputend"&&(a=f?"touchend":"mouseup");if(g[a]==1&&this.dom){var b=this,m={fun:c,dir:function(a){a.postionGotton=false;a.inputX==void 0&&(Object.defineProperty(a,
"inputX",{get:function(){return e.getEventPosition(a,b.thisAni.scene.dom,b.thisAni.overAllScaleX,b.thisAni).x}}),Object.defineProperty(a,"inputY",{get:function(){return e.getEventPosition(a,b.thisAni.scene.dom,b.thisAni.overAllScaleY,b.thisAni).y}}));c.call(b,a)}};this.event[a]?this.event[a].push(m):this.event[a]=[m];this.dom.addEventListener(a,m.dir,d||false)}else this.event[a]?this.event[a].push(c):this.event[a]=[c];return this},y=function(a,e,c){a=="inputstart"?a=f?"touchstart":"mousedown":a==
"inputmove"?a=f?"touchmove":"mousemove":a=="inputend"&&(a=f?"touchend":"mouseup");if(g[a]==1&&this.dom){if(this.event[a]){for(var b=this.event[a].length-1;b>=0;b--)this.event[a][b].fun&&this.event[a][b].fun==e&&(this.dom.removeEventListener(a,this.event[a][b].dir,c||false),this.event[a].splice(b,1));this.event[a].length==0&&delete this.event[a]}}else if(this.event[a]){for(b=this.event[a].length-1;b>=0;b--)this.event[a][b]==e&&this.event[a].splice(b,1);this.event[a].length==0&&delete this.event[a]}return this},
v=function(a,e,c,b,d){if(this.event[a]){for(var f=[],g=0;g<this.event[a].length;g++)f[g]=this.event[a][g];for(g=0;g<f.length;g++)f[g].call(this,e,c,b,d)}};d.prototype.addEventListener=j;d.prototype.removeEventListener=y;d.prototype.initDom=function(a){if(this.aniData&&this.dom){this.thisAni=this;this.countDownRef=0;this.imageCache=[];this.maxNum=0;Mugeda.updateViewport(this.aniData,null,this,f);this.loadOver=a;var c=this.aniData,g=this.dom,b=this;setTimeout(function(){window.scroll(0,0)},0);b.iOS=
function(){var a={};if(/iP(hone|od|ad)/.test(navigator.platform)){var b=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);a.version=parseInt(b[1],10)+0.1*parseInt(b[2],10)}return a}();var m=function(a){var b=null;window.weixinAudioLoader&&window.weixinAudioLoader[a]?b=window.weixinAudioLoader[a]:(b=new Audio(a),b.load());b.addEventListener("ended",function(){b.loop?(b.currentTime=0,b.play()):b.currentTime=0});return b},t=function(a,c,e,k,d,h,i,l,g){this.id=a;this.data=c;this.length=Mugeda.getFrameLength(c.layers);
this.playing=e;this.currentId=null;this.nextId=0;this.offset=d;this.dom=h;this.layerList=[];this.objectHash={};this.unitHash=[];this.isSymbol=i;this.clickEventAttached={};this.nameHash={};this.scriptHash={};this.segment={};this.currentSegment={};b.sceneHash[this.id]=this;this.event={};this.frameout=[];this.thisAni=b;this.parentScene=l;this.cachedVisibility={};this.lastRenderList={};this.frameLength=0;if(i)this.object=g;a=i?c.id:"_main";b.frameParamCache[a]=b.frameParamCache[a]||{};this.frameParamCache=
b.frameParamCache[a]};t.prototype.getObjectByName=function(a){return this.nameHash[a]};t.prototype.initAndGetDom=function(){var a=this;a.data.layers.m_operate(function(b){b=new q(b,a);a.layerList.push(b);b.initAndGetDom(a.dom)},true)};t.prototype.play=function(){this.playing=true;b.stopRedraw=false;return this};t.prototype.pause=function(){this.pauseFlag=true;this.playing=false;v.call(this,"pause");return this};t.prototype.gotoAndPlay=function(a){this.gotoFlag=true;this.nextId=a;return this.play()};
t.prototype.gotoAndPause=function(a){this.nextId=a;this.gotoFlag=true;return this.pause()};t.prototype.setSegment=function(a,b,c,e){this.segment[a]={from:Math.min(b,this.length),to:Math.min(c,this.length),isLoop:e};return this};t.prototype.playSegment=function(a){(this.currentSegment=this.segment[a])&&this.gotoAndPlay(this.currentSegment.from);return this};t.prototype.setFrameout=function(a,b){for(var c=this.frameout.length,e=0,d=0;d<this.frameout.length;d++){var h=this.frameout[d];if(e+h.time>a){c=
d;break}e+=h.time}this.frameout.splice(c,0,{time:a-e,fun:b});return this};t.prototype.removeChild=function(a){if(a.unit){var b=a.unit.data.objects;if(a.parentGroup)b=a.parentGroup.data;b.m_operate(function(c,e){if(c.guid==a.id)return b.splice(e,1),false})}a.dom.parentNode.removeChild(a.dom);this.nameHash[a.name]&&delete this.nameHash[a.name];delete this.objectHash[a.id];if(this.scriptHash[a.id])delete this.scriptHash[a.id];else{var c=a.unit?a.unit.data.frameStart:0,e=a.unit?a.unit.data.frameStart+
a.unit.data.frameCount-1:a.currentScene.frameLength-1,d=this.cachedVisibility;setTimeout(function(){for(var b=c;b<=e;b++)for(var i=d[b].length,h=0;h<i;h++)if(d[b][h].id==a.id){d[b].splice(h,1);break}},0)}return this};t.prototype.appendChild=function(a,b){if(a.name&&this.nameHash[a.name])throw"object name: "+a.name+" had been used";this.nameHash[a.name]=a;for(var c=0;c<(this.frameLength||1);c++)this.cachedVisibility[c]=this.cachedVisibility[c]||[],this.cachedVisibility[c].push(a);a.currentScene=this;
a.initAndGetDom(this.dom,b&&b.dom?b.dom:null);Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";return a};t.prototype.addEventListener=j;t.prototype.removeEventListener=y;var q=function(a,b){this.id=a.id;this.name=a.name;this.data=a;this.unitList=[];this.scene=b};q.prototype.initAndGetDom=function(a){var b=this;b.data.units.m_operate(function(c){c=new p(c,b);b.unitList.push(c);c.initAndGetDom(a)},true)};var p=function(a,b){this.data=a;this.layer=b;this.objectList=[];this.symbolList=[];
this.imageList=[];this.id=a.id;b.scene.unitHash[a.id]=this;b.scene.frameParamCache[this.id]=b.scene.frameParamCache[this.id]||{};this.cachedFrame=b.scene.frameParamCache[this.id];this.zoneCached=false};p.prototype.initAndGetDom=function(a){var c=this;if(this.data&&(this.data.audio||this.data.audioId))this.audio=this.data.audioId?m(b.resDir+b.audioSym[this.data.audioId]):m(b.resDir+this.data.audio);if(this.audio){for(var e=Mugeda.guidGen(),k=this.layer.scene,d=this.data.frameStart;d<this.data.frameStart+
this.data.frameCount;d++)k.cachedAudio=k.cachedAudio||[],k.cachedAudio[d]=k.cachedAudio[d]||[],k.cachedAudio[d].push({audio:this.audio,start:d==this.data.frameStart,hash:e});b.audioList[e]=this.audio}if(this.data.objects&&this.data.objects.length!=0){if(this.data.keyframes.length)this.data.hashKey={},this.data.keyframes.m_operate(function(a){c.data.hashKey["key_"+a.id]=a});this.data.objects.m_operate(function(b){b=new n(b,c);c.objectList.push(b);b.initAndGetDom(a);if(b.symbolIdList)c.symbolList=c.symbolList.concat(b.symbolIdList);
Mugeda.nonDisplay?b.hide():b.dom.style.cssText+="display:none;"});k=this.layer.scene;for(d=this.data.frameStart;d<this.data.frameStart+this.data.frameCount;d++)k.cachedVisibility[d]=k.cachedVisibility[d]||[],k.cachedVisibility[d]=k.cachedVisibility[d].concat(this.objectList);k.frameLength=Math.max(k.frameLength,this.data.frameStart+this.data.frameCount);if(this.layer.scene.id=="_main")for(d=this.data.frameStart;d<this.data.frameStart+this.data.frameCount;d++)b.mainSceneFrameUnitHash[d]=b.mainSceneFrameUnitHash[d]||
[],b.mainSceneFrameUnitHash[d].push(this)}};p.prototype.updateUnitVisibility=function(a){this.objectList.m_operate(function(b){Mugeda.nonDisplay?a?b.show():b.hide():b.dom.m_css("display",a?b.dom.displayType||"block":"none")})};var s=function(a,b,c,e){this.parent=a;this.dom=b;this.data=a.data.items;this.objectList=[];this.unit=c;this.scene=e};s.prototype.initAndGetDom=function(){var a=this;this.data.length!=0&&this.data.m_operate(function(b){b=new n(b,a.unit,{inGroup:true,group:a});if(!b.currentScene)b.currentScene=
a.scene;a.objectList.push(b);b.initAndGetDom(a.dom)})};var n=MugedaCss3.aObject=function(a,c,e){e=e||{};a=this.data=JSON.parse(JSON.stringify(a));this.currentScene=(this.unit=c)?c.layer.scene:null;this.id=Mugeda.guidGen();c&&(this.currentScene.nameHash[a.param.name]=this);if(e.inGroup)this.offset={x:0,y:0},this.parentGroup=e.group;this.event={};this.thisAni=b;this.userParam={};var k=[],d=[],h=function(a){if(a.items)for(var b=0;b<a.items.length;b++){var c=a.items[b];c.type==2021||c.type==2023?(c.symbolSceneId=
Mugeda.guidGen(),k.push(c.symbolSceneId),d.push(c.param.symbolId)):a.type==2014&&h(c)}};if(!e.inGroup)if(a.type==2014)h(a);else if(a.type==2021||a.type==2023)a.symbolSceneId=Mugeda.guidGen(),k.push(a.symbolSceneId),d.push(a.param.symbolId);if(k.length)this.symbolList=k,this.symbolIdList=d;Object.defineProperty(this,"name",{get:function(){return this.data.param.name},set:function(a){if(this.currentScene.nameHash[a])throw"name had been used before";this.currentScene.nameHash[a]=this.currentScene.nameHash[this.data.param.name];
delete this.currentScene.nameHash[this.data.param.name];this.data.param.name=a}});a.type==2005&&Object.defineProperty(this,"src",{get:function(){return this.userParam.src},set:function(a){this.userParam.src=a;this.dom.tagName=="DIV"?this.dom.childNodes[0].src=a:this.dom.src=a}});Object.defineProperty(this,"width",{get:function(){return this.data.param.width},set:function(a){var b=this.data.param.width/this.scaleX,c=this.rotateCenterX/this.scaleX;this.rotateCenterX=0;this.scaleX=a/b;this.rotateCenterX=
c*this.scaleX}});Object.defineProperty(this,"height",{get:function(){return this.data.param.height},set:function(a){var b=this.data.param.height/this.scaleY,c=this.rotateCenterY/this.scaleY;this.rotateCenterY=0;this.scaleY=a/b;this.rotateCenterY=c*this.scaleY}});Object.defineProperty(this,"left",{get:function(){return this.data.param.left},set:function(a){this.userParam.x=a-this.userParam.ox+this.userParam.rx;this.data.param.left=a;this.data.param.right=this.data.param.left+this.data.param.width;
z(this)}});Object.defineProperty(this,"right",{get:function(){return this.data.param.right},set:function(a){this.data.param.right=a;this.data.param.left=a-this.data.param.width;this.userParam.x=this.data.param.left-this.userParam.ox+this.userParam.rx;z(this)}});Object.defineProperty(this,"top",{get:function(){return this.data.param.top},set:function(a){this.data.param.top=a;this.userParam.y=a-this.userParam.oy+this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;z(this)}});
Object.defineProperty(this,"bottom",{get:function(){return this.data.param.bottom},set:function(a){this.data.param.bottom=a;this.data.param.top=a-this.data.param.height;this.userParam.y=this.data.param.top-this.userParam.oy+this.userParam.ry;z(this)}});Object.defineProperty(this,"x",{get:function(){return this.userParam.x},set:function(a){this.userParam.x=a;this.data.param.left=a+this.userParam.ox-this.userParam.rx;this.data.param.right=this.data.param.left+this.data.param.width;z(this)}});Object.defineProperty(this,
"y",{get:function(){return this.userParam.y},set:function(a){this.userParam.y=a;this.data.param.top=a+this.userParam.oy-this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;z(this)}});Object.defineProperty(this,"rotateCenterX",{get:function(){return this.userParam.rx},set:function(a){this.data.param.rotateCenterX=this.userParam.rx=Math.round(a);this.userParam.rsx=a/this.userParam.sx;this.userParam.x=this.data.param.left+a-this.userParam.ox;z(this)}});Object.defineProperty(this,
"rotateCenterY",{get:function(){return this.userParam.ry},set:function(a){this.data.param.rotateCenterY=this.userParam.ry=Math.round(a);this.userParam.rsy=a/this.userParam.sy;this.userParam.y=this.data.param.top+a-this.userParam.oy;z(this)}});Object.defineProperty(this,"scaleX",{get:function(){return this.userParam.sx},set:function(a){this.userParam.rx=this.data.param.rotateCenterX=this.userParam.rx/this.userParam.sx*a;this.userParam.sx=this.data.param.scaleX=a;this.data.param.width=this.data.param.rawWidth*
a;this.data.param.left=this.userParam.x+this.userParam.ox-this.userParam.rx;this.data.param.right=this.data.param.left+this.data.param.width;z(this)}});Object.defineProperty(this,"scaleY",{get:function(){return this.userParam.sy},set:function(a){this.userParam.ry=this.data.param.rotateCenterY=this.userParam.ry/this.userParam.sy*a;this.userParam.sy=this.data.param.scaleY=a;this.data.param.height=this.data.param.rawHeight*a;this.data.param.top=this.userParam.y+this.userParam.oy-this.userParam.ry;this.data.param.bottom=
this.data.param.top+this.data.param.height;z(this)}});Object.defineProperty(this,"rotate",{get:function(){return this.data.param.rotate},set:function(a){this.data.param.rotate=a;z(this)}});Object.defineProperty(this,"alpha",{get:function(){return this.data.param.alpha},set:function(a){this.data.param.alpha=a;z(this)}});this.userParam.visible=true;Object.defineProperty(this,"visible",{get:function(){return this.userParam.visible},set:function(a){(this.userParam.visible=a)?this.dom.m_css("display",
this.dom.m_attr("displayType")||"block"):this.dom.m_css("display","none")}});Object.defineProperty(this,"text",{get:function(){if(this.data.type==2010)return unescape(this.data.param.textContent)},set:function(a){if(this.data.type==2010)this.data.param.textContent=escape(a);z(this)}});Object.defineProperty(this,"url",{get:function(){},set:function(a){this.data.param.url=a}})},x={},w=function(){delete x.old;for(objId in x)x[objId].updateObjectParam();x={}},z=function(a){x[a.id]=a;x.old=true;setTimeout(w,
0)};n.prototype.setCapture=function(a){this.dom.m_setCapture(a)};n.prototype.releaseCapture=function(a){this.dom.m_releasecapture(a)};n.prototype.initAndGetDom=function(a,c){var d=this.data,k;if(d.param.left===null)this.unit&&this.unit.data.keyframes&&this.unit.data.keyframes.length>=2?d.param=JSON.parse(JSON.stringify(this.unit.data.keyframes[0].param)):console.log("Fatal error: object (ID: "+d.guid+") param is lost!");var h=false;if(this.currentScene&&this.currentScene.cachedSymbolScene)var h=true,
l=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[d.guid].dom.className)[0];var i=d.param;switch(d.type){case 2003:case 2004:case 2009:if(h)break;var g=i.lineWidth,f=Math.floor(i.lineWidth/2);k=e("<div>");var o=e("<div>");o.m_addClass("guid_"+Mugeda.guidGen());g&&o.m_css("border",g+"px solid "+i.strokeColor).m_css("position","absolute").m_css("top",-f+"px").m_css("bottom",-f+"px").m_css("left",-f+"px").m_css("right",-f+"px").m_appendTo(k);if(d.type==2009){var m=
d.cornerRadius[0]+"px ";k.m_css("border-radius",m+m+m+m);k.m_css("border-top-left-radius",m);k.m_css("border-top-right-radius",m);k.m_css("border-bottom-left-radius",m);k.m_css("border-bottom-right-radius",m)}else if(d.type==2004){var m=i.width/2+"px",q=i.height/2+"px";k.m_css("border-radius",m+" "+q);k.m_css("border-top-left-radius",m+" "+q);k.m_css("border-top-right-radius",m+" "+q);k.m_css("border-bottom-left-radius",m+" "+q);k.m_css("border-bottom-right-radius",m+" "+q)}k.m_css("background",e.getCssBackgroundColor(i));
g&&(d.type==2009?(m=d.cornerRadius[0]+f+"px ",o.m_css("border-radius",m+m+m+m),o.m_css("border-top-left-radius",m),o.m_css("border-top-right-radius",m),o.m_css("border-bottom-left-radius",m),o.m_css("border-bottom-right-radius",m)):d.type==2004&&(m=i.width/2+f+"px",q=i.height/2+f+"px",o.m_css("border-radius",m+" "+q),o.m_css("border-top-left-radius",m+" "+q),o.m_css("border-top-right-radius",m+" "+q),o.m_css("border-bottom-left-radius",m+" "+q),o.m_css("border-bottom-right-radius",m+" "+q)));break;
case 2005:if(!i.imageSrc.length)i.imageSrc="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";if(i.imageSrc.length>0){this.userParam=this.userParam||[];this.userParam.src=(i.imageSrc.indexOf("data:")==0?"":b.resDir)+i.imageSrc;if(h){g=l;l.tagName=="DIV"&&(g=l.childNodes[0]);b.loadImage("dom_back",{dom:g,url:b.resDir+i.imageSrc,duringBuilding:b.zoneCachedMode,scene:this.currentScene,unit:this.unit});break}k=e("<img>");if(i.keepAspect){var g=i.rawWidth,f=i.rawHeight,
o=i.width,m=i.height,q=o/g*f,n=o,j=n=0;q>m?(q=m,n=(o-m/f*g)/2,k.m_css("padding-left",n.toString()+"px"),k.m_css("padding-right",n.toString()+"px")):(j=(m-q)/2,k.m_css("padding-top",n.toString()+"px"),k.m_css("padding-bottom",n.toString()+"px"))}b.loadImage("dom_back",{dom:k,url:(i.imageSrc.indexOf("data:")==0?"":b.resDir)+i.imageSrc,duringBuilding:b.zoneCachedMode,scene:this.currentScene,unit:this.unit})}break;case 2010:if(Mugeda.textAsFlexbox){if(h){l.displayType="";break}k=e("<div>");g=e("<div>").m_appendTo(k).m_css("width",
"100%");g.innerHTML=unescape(i.textContent).replace(/\n/g,"<br>").replace(/\s\s/g," &nbsp;");g.txt=i.textContent;k.m_css("font-size",i.fontSize+"px").m_css("font-weight",i.fontWeight).m_css("font-family",i.fontFamily).m_css("text-stroke",i.lineWidth/2+"px "+i.strokeColor).m_css("text-shadow","0 "+(i.lineWidth/2<1?1:i.lineWidth/2)+"px "+i.strokeColor).m_css("line-height",parseInt(i.fontSize)+4+"px").m_css("text-align",i.textAlign||"left").m_css("text-fill-color",e.getCssBackgroundColor(i)).m_css("color",
"rgba("+i.fillInfo.fillColors[0].r+","+i.fillInfo.fillColors[0].g+","+i.fillInfo.fillColors[0].b+","+i.fillInfo.fillColors[0].a+")").m_css("padding-top","1px").m_addClass("flex").m_addClass(i.textVAlign);k.displayType=""}else{if(h){l.displayType="table";break}k=e("<div>");g=e("<div>").m_appendTo(k).m_css("display","table-cell").m_css("vertical-align",i.textVAlign||"baseline");g.displayType="table-cell";g.innerHTML=unescape(i.textContent).replace(/\n/g,"<br>").replace(/\s\s/g," &nbsp;");g.txt=i.textContent;
k.m_css("font-size",i.fontSize+"px").m_css("font-weight",i.fontWeight).m_css("font-family",i.fontFamily).m_css("display","table").m_css("text-stroke",i.lineWidth/2+"px "+i.strokeColor).m_css("text-shadow","0 "+(i.lineWidth/2<1?1:i.lineWidth/2)+"px "+i.strokeColor).m_css("line-height",parseInt(i.fontSize)+4+"px").m_css("text-align",i.textAlign||"left").m_css("text-fill-color",e.getCssBackgroundColor(i)).m_css("color","rgba("+i.fillInfo.fillColors[0].r+","+i.fillInfo.fillColors[0].g+","+i.fillInfo.fillColors[0].b+
","+i.fillInfo.fillColors[0].a+")").m_css("padding-top","1px");k.displayType="table"}i.fontStyle&&k.m_css("font-style",i.fontStyle);i.textDecoration&&k.m_css("text-decoration",i.textDecoration);break;case 2014:h?k=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[d.guid].dom.className)[0]:(k=e("<div>"),k.m_addClass("group"));this.group=g=new s(this,k,this.unit,this.currentScene);g.initAndGetDom(k);break;case 2023:g=function(a){return{fillInfo:null,imageSrc:i.imageSrc,
rawWidth:i.rawWidth,rawHeight:i.rawHeight*i.frameNum,left:0,right:i.rawWidth,top:-i.rawHeight*a,bottom:i.rawHeight*(i.frameNum-a),scaleX:1,scaleY:1,rotate:0,alpha:1,width:i.rawWidth,height:i.rawHeight*i.frameNum}};f=Mugeda.guidGen();o=Math.ceil(i.frameNum/i.fps*b.rate);b.symbols[f]={id:f,name:f,cw:b.aniData.width,ch:b.aniData.height,layers:[{id:0,name:"\u56fe\u5c420",units:[{id:Mugeda.guidGen(),layerId:0,frameStart:0,frameCount:o,animated:true,objects:[{guid:Mugeda.guidGen(),type:2005,param:g(0)}],
keyframes:[],hashKey:[],visible:true}]}]};m=null;for(q=0;q<o;q++){var p=Math.min(Math.round(q/b.rate*i.fps),i.frameNum-1);p!=m&&(b.symbols[f].layers[0].units[0].keyframes.push({id:q,mode:0,tween:"Step.EaseIn",param:g(p)}),m=p);b.symbols[f].layers[0].units[0].guessKeyframe=false}i.symbolId=f;i.offsetX=-b.aniData.width/2;i.offsetY=-b.aniData.height/2;case 2021:if(!b.symbols[i.symbolId])break;g=b.symbols[i.symbolId];if(h)f=b.symbols[i.symbolId].cw/2+i.offsetX,o=b.symbols[i.symbolId].ch/2+i.offsetY,f=
this.scene=new t(this.data.symbolSceneId,b.symbols[i.symbolId],true,0,{x:f,y:o},l,true,this.currentScene,this),f.cachedSymbolScene=this.currentScene.cachedSymbolScene.objectHash[d.guid].scene;else{k=e("<div>");k.m_addClass("symbol");d.type==2023&&k.m_css("overflow","hidden");f=b.symbols[i.symbolId].cw/2+i.offsetX;o=b.symbols[i.symbolId].ch/2+i.offsetY;f=this.scene=new t(this.data.symbolSceneId,b.symbols[i.symbolId],true,0,{x:f,y:o},k,true,this.currentScene,this);if(d.type==2023){if(i.looped==null)i.looped=
true;this.scene.looped=i.looped}if(g.cachedInstance)symCache=g.cachedInstance.scene,f.dom.innerHTML=symCache.dom.innerHTML,f.cachedSymbolScene=symCache}f.initAndGetDom();break;case 2024:if(g=JSON.parse(d.param.Form),k=e("<div>"),MugedaBehavior.popupForm(g,true),o=g.iframeDiv){o.style.padding=0;k.appendChild(o);var f=o.querySelectorAll(".inputlabel"),o=o.querySelectorAll(".popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select"),x=g.hwObj;Array.prototype.forEach.call(f,function(a){a.style.width=
x.l+"px"});Array.prototype.forEach.call(o,function(a){a.style.width=x.r+"px"})}}if(k||h)if(h)this.dom=l,this.currentScene.objectHash[d.guid]=this,this.updateObjectParam({staticMode:true,readyCachedMode:true,isImage:d.type==2005}),this.dom.object=this;else{k.m_addClass("layer_"+(this.unit?this.unit.layer.id:"script")).m_addClass("guid_"+this.id).m_css("position","absolute").m_css("left",0).m_css("top",0).m_css("backface-visibility","hidden");if(i.vF||i.hF)h=e("<div>").m_css("position","absolute").m_append(k),
k.m_css("top","0").m_css("left","0").m_css("right","0").m_css("bottom","0").m_css("transform",(i.vF?"scaleY(-1) ":"")+(i.hF?"scaleX(-1)":"")),k=h,h.className="guid_"+Mugeda.guidGen();a.m_append(k,c);this.dom=k;this.dom.object=this;this.currentScene.objectHash[d.guid]=this;this.updateObjectParam({staticMode:true,isImage:d.type==2005,dw:n,dh:j});if(d.type===2024)k=k.firstChild,h=d.param.width,l=d.param.height,d=function(a,b,c,e){var d=a,k=b,h=1;a/b>c/e?(d=c,k=c*(b/a),h=c/a):(k=e,d=e/(b/a),h=e/b);return{w:d,
h:k,mt:(e-k)/2,ml:(c-d)/2,r:h}}(288,MugedaBehavior.getPopupFormHeight(JSON.parse(d.param.Form)),h,l),k.parentNode.m_transform(0,0,null,1,1,0,0),k.m_transform(d.ml,d.mt,null,d.r,d.r,0,0)}};n.prototype.addEventListener=j;n.prototype.removeEventListener=y;n.prototype.setParam=function(a){a.call(this,this.param);this.updateObjectParam({param:this.param});Mugeda.nonDisplay?this.param.hide?this.hide():this.show():this.dom.m_css("display",this.param.hide?"none":this.dom.displayType!=null?this.dom.displayType:
"block")};n.prototype.getParam=function(){this.param.hide=this.param.hide||false;return this.param};n.prototype.setButton=function(a,b,c){var e=this.scene;e&&(c==void 0&&(c=a),typeof a=="number"&&(a={from:a,to:a,isLoop:false}),typeof b=="number"&&(b={from:b,to:b,isLoop:false}),typeof c=="number"&&(c={from:c,to:c,isLoop:false}),e.setSegment("__normal",a.from,a.to,a.isLoop),e.setSegment("__push",b.from,b.to,b.isLoop),e.setSegment("__up",c.from,c.to,c.isLoop),e.playSegment("__normal"),this.addEventListener("inputstart",
function(){this.disabled||this.scene.playSegment("__push")}),this.addEventListener("inputend",function(){this.scene.currentSegment==e.segment.__push&&this.scene.playSegment("__up")}),this.addEventListener("mouseout",function(){this.scene.currentSegment==e.segment.__push&&this.scene.playSegment("__up")}));this.dom.m_css("cursor","pointer");return this};n.prototype.appendChild=function(a,b){if(a.name&&this.currentScene.nameHash[a.name])throw"object name: "+a.name+" had been used";this.currentScene.nameHash[a.name]=
a;for(var c=this.unit?this.unit.data.frameStart:0,e=this.unit?c+this.unit.data.frameCount:this.currentScene.frameLength;c<e;c++)this.currentScene.cachedVisibility[c]=this.currentScene.cachedVisibility[c]||[],this.currentScene.cachedVisibility[c].push(a);a.currentScene=this.currentScene;a.initAndGetDom(this.dom,b&&b.dom?b.dom:null);Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";return a};n.prototype.updateObjectParam=function(a){a=a||{};staticMode=a.staticMode||false;readyCachedMode=
a.readyCachedMode||false;var c=this.dom,e=this.offset||this.currentScene.offset,d=a.param||this.data.param,h=this;this.param=d;if(staticMode&&(a.isImage?(d.rawWidth=d.width-(a.dw?a.dw*2:0),d.rawHeight=d.height-(a.dh?a.dh*2:0)):(d.rawWidth=d.rawWidth||d.width,d.rawHeight=d.rawHeight||d.height),readyCachedMode||(c.m_width(d.rawWidth).m_height(d.rawHeight),(d.vF||d.hF)&&c.childNodes[0].m_width(d.rawWidth).m_height(d.rawHeight)),d.action))if(d.action=="link"&&d.url&&d.url.length){var g=function(){MugedaMraid.openLink(d.url,
d.urlTarget)};c.m_css("cursor","pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":f?"touchend":"mouseup",function(a){g();a.preventDefault();a.stopPropagation();return false})}else if(d.action=="form"&&d.form&&d.form.length)g=function(){MugedaBehavior.popupForm(JSON.parse(d.form))},c.m_css("cursor","pointer").m_event(f?"touchend":"mouseup",function(a){g();a.preventDefault();a.stopPropagation();return false});else if(d.action=="behavior"&&d.behavior)a=JSON.parse(d.behavior),d.behaviorObj=
a,a.m_operate(function(a){if(a.type=="audio"){var c=a.param.audio_id?b.audioSym[a.param.audio_id]:b.resDir+a.param.audio_url;b.audioBeList=b.audioBeList||{};var d=Mugeda.guidGen();a.param.audioId=d;b.audioBeList[d]=m(c);if(a.param.audio_loop=="1")b.audioBeList[d].loop=true;a.param.audio_name&&(h.currentScene.nameHash[a.param.audio_name]=b.audioBeList[d]);b.audioList[d]=b.audioBeList[d]}});var a=d.width/d.rawWidth,l=d.height/d.rawHeight,o=d.rotateCenterX!=void 0?d.rotateCenterX:d.width/2,q=d.rotateCenterY!=
void 0?d.rotateCenterY:d.height/2,n=Math.round(o/a),j=Math.round(q/l),o=n*a,q=j*l,s=d.left-(n-o)-e.x,t=d.top-(j-q)-e.y,p=d.rotate;s.toString().indexOf("e")>-1&&(s=0);t.toString().indexOf("e")>-1&&(t=0);a.toString().indexOf("e")>-1&&(a=0);l.toString().indexOf("e")>-1&&(l=0);p.toString().indexOf("e")>-1&&(p=0);this.userParam.x=s+n;this.userParam.y=t+j;this.userParam.rx=o;this.userParam.ry=q;this.userParam.sx=a;this.userParam.sy=l;this.userParam.rsx=n;this.userParam.rsy=j;this.userParam.ox=e.x;this.userParam.oy=
e.y;c.m_css("opacity",Math.floor(100*d.alpha)*0.01,b).m_css("transform-origin",n.toString()+"px "+j.toString()+"px",b);this.beforeHiddenTrans="translate("+s.toString()+"px,"+t.toString()+"px) rotate("+p.toString()+"rad) scale("+a.toString()+","+l.toString()+")";this.hidden||c.m_css("transform",this.beforeHiddenTrans,b);if(d.textContent!=void 0&&c.childNodes[0].txt!=d.textContent)c.childNodes[0].innerHTML=unescape(d.textContent).replace(/\n/g,"<br>"),c.childNodes[0].txt=d.textContent};n.prototype.hide=
function(){if(!this.hidden)return this.dom.m_css("transform","translate(-9999999px, -99999999px)",b),this.hidden=true,this};n.prototype.show=function(){if(this.hidden)return this.beforeHiddenTrans&&this.dom.m_css("transform",this.beforeHiddenTrans,b),this.hidden=false,this};n.prototype.clone=function(a){var b=JSON.parse(JSON.stringify(this.data));b.param.name=a;b.guid=Mugeda.guidGen();return new n(b,null)};a=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(a);b.externalStylesheet=
a.sheet||a.styleSheet;b.indexedStylesheet={};b.cachedRule=[];this.dom.m_attr("name",c.title).m_addClass("MugedaStage").m_width(c.width).m_height(c.height).m_css("background-color",c.color).m_css("background-image",c.image?"url("+c.image+")":"").m_css("background-repeat","no-repeat").m_css("background-size",c.width+"px "+c.height+"px").m_css("overflow","hidden").m_css("position","relative");Mugeda.enablePulse&&this.dom.m_css("transform","translate(0,0)");this.dom.style.webkitTapHighlightColor="rgba(0,0,0,0)";
b.loadingDiv=e("<div>").m_css("line-height",c.height+"px").m_css("text-align","center").m_css("background","black").m_css("color","white").m_css("font-family","arial");b.dom.insertBefore(b.loadingDiv,b.dom.firstChild);b.loadingDiv.innerHTML="Loading...";b.loadingDiv.id="loadingDiv";var r=b.dom,A=function(){b.adaption=b.adaption||{};if(typeof _mrmcp=="undefined"||_mrmcp.render_mode!="inline"&&_mrmcp.render_mode!="embedded"){var a=document.body.offsetWidth/c.width,d=document.body.offsetHeight/c.height,
d=document.body.offsetHeight/c.height,e=c.metadata?c.metadata.adaptMode:null,h=1,g=c.width,f=c.height;b.adaption.type=e;switch(e){case "contain":h=Math.max(0.001,Math.min(a,d));break;case "cover":h=Math.max(a,d,0.001);break;case "width":case "width2":case "none_mobile":h=Math.max(a,0.001);break;case "height":h=Math.max(d,0.001)}a=e=="fill"?a:h;d=e=="fill"?d:h;g*=a;f*=d;r.parentNode.style.width=g+"px";r.parentNode.style.height=f+"px";b.overAllScaleX=a;b.overAllScaleY=d;b.adaption.scale=h;b.adaption.scaleX=
a;b.adaption.scaleY=d;e=="width2"?b.adaption.marginLeft=b.adaption.marginRight=b.adaption.marginTop=b.adaption.marginBottom=0:(b.adaption.marginLeft=b.adaption.marginRight=(document.body.offsetWidth/a-c.width)/2,b.adaption.marginTop=b.adaption.marginBottom=(document.body.offsetHeight/d-c.height)/2);e=="none_mobile"||e=="none_pc"?(h=document.body.offsetHeight-c.height*d<0)?(b.adaption.marginTop=b.adaption.marginBottom=0,r.parentNode.style.marginTop="0",r.parentNode.style.marginBottom="0"):(r.parentNode.style.marginTop=
"auto",r.parentNode.style.marginBottom="auto"):e=="width2"?(r.parentNode.style.marginTop="0",r.parentNode.style.marginBottom="0"):(h=document.body.offsetHeight-c.height*d<0)?(r.parentNode.style.marginTop=-(c.height*d-document.body.offsetHeight)/2+"px",r.parentNode.style.marginBottom="0",r.parentNode.style.height="auto"):(r.parentNode.style.marginTop="auto",r.parentNode.style.marginBottom="auto",r.parentNode.style.height=f+"px");e=="none_pc"?document.body.offsetWidth-c.width*a<0?(b.adaption.marginLeft=
b.adaption.marginRight=0,r.parentNode.style.marginLeft="0"):r.parentNode.style.marginLeft="auto":(h=document.body.offsetWidth-c.width*a<0)?(r.parentNode.style.marginLeft=-(c.width*a-document.body.offsetWidth)/2+"px",r.parentNode.style.marginRight="0",r.parentNode.style.width="auto"):(r.parentNode.style.marginLeft="auto",r.parentNode.style.marginRight="auto",r.parentNode.style.width=g+"px");r.m_transform(null,null,null,a,d,0,0)}v.call(b,"resize",b.adaption)};A();Mugeda.textAsFlexbox&&(b.insertRule(".flex.middle",
"-webkit-box-align: center;-moz-box-align: center;-ms-flex-align: center;-webkit-justify-content: center;-moz-justify-content: center;justify-content: center;-webkit-box-pack: center;-moz-box-pack: center;-ms-flex-pack: center;-webkit-align-items: center;-moz-align-items: center;align-items: center;"),b.insertRule(".flex","display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -moz-flex; display: -ms-flexbox; display: flex;"),b.insertRule(".flex.top","-webkit-box-align: start;-moz-box-align: start;-ms-flex-align: start;-webkit-justify-content: start;-moz-justify-content: start;justify-content: flex-start;-webkit-box-pack: start;-moz-box-pack: start;-ms-flex-pack: start;-webkit-align-items: flex-start;-moz-align-items: flex-start;align-items: flex-start;"),
b.insertRule(".flex.bottom","-webkit-box-align: end;-moz-box-align: end;-ms-flex-align: end;-webkit-justify-content: end;-moz-justify-content: end;justify-content: flex-end;-webkit-box-pack: end;-moz-box-pack: end;-ms-flex-pack: end;-webkit-align-items: flex-end;-moz-align-items: flex-end;align-items: flex-end;"));b.updateRuleCached();b.loadProcess="script";if(b.aniData.sL)if(Mugeda.previewMode){if(b.aniData.sL.extra&&b.aniData.sL.extra.length)for(a=0;a<b.aniData.sL.extra.length;a++)B=b.aniData.sL.extra[a],
B.indexOf("://")>-1?b.loadImage("script",b.aniData.sL.extra[a]):b.loadImage("script",b.resDir+b.aniData.sL.extra[a]);b.aniData.sL.cardCommon&&b.loadImage("script","/mugeda_client_utils/js/card_common.js");b.aniData.sL.mugedaPage&&b.loadImage("script","/mugeda_client_utils/js/mugeda_page.js")}else{b.aniData.sL.jquery&&b.loadImage("script",b.resDir+"jquery-1.10.2.min.js");b.aniData.sL.socketio&&(b.loadImage("script",b.resDir+"socket.io.1.9.16.min.js"),b.loadImage("script",b.resDir+"mugeda_connection.js"));
b.aniData.sL.box2d&&b.loadImage("script",b.resDir+"Box2dWeb-2.1.a.3.min.js");b.aniData.sL.qrcode&&(b.loadImage("script",b.resDir+"qrcode.min.js"),b.loadImage("script",b.resDir+"jquery.qrcode.min.js",1));if(b.aniData.sL.extra&&b.aniData.sL.extra.length)for(a=0;a<b.aniData.sL.extra.length;a++){var B=b.aniData.sL.extra[a];B.indexOf("://")>-1?b.loadImage("script",b.aniData.sL.extra[a]):b.loadImage("script",b.resDir+b.aniData.sL.extra[a])}b.aniData.sL.cardCommon&&b.loadImage("script",b.resDir+"card_common.js");
b.aniData.sL.mugedaPage&&b.loadImage("script",b.resDir+"mugeda_page.js")}b.scriptFile&&b.loadImage("script",b.resDir+b.scriptFile,2);setTimeout(function(){b.checkCountDownRef(true,true)},0);var u=function(){if(b.scriptFile){if(b.script=Mugeda.script[Mugeda.script.length-1],typeof b.script=="function")b.script(b),b.scriptExeced=true}else if(b.aniData.script)(function(a){eval(a.aniData.script)})(b),Mugeda.customScript=b.aniData.script;var a=function(){delete b.evt;b.loadProcess="image";b.afterLoadScriptProcess()},
c={stopLoad:false,goOnLoad:a};b.evt=c;v.call(b,"scriptReady",c);c.stopLoad||a()};b.checkCountDownRef=function(a,c){function d(){for(var a in b.paramUpdatePool){var c=b.paramUpdatePool[a];c.object.style.cssText+=c.text}b.paramUpdatePool={};a=function(){delete b.evt;b.loadProcess="loaded";b.loadOver.call(b);b.setupTimer()};c={stopLoad:false,goOnLoad:a};b.evt=c;v.call(b,"imageReady",c);c.stopLoad||a()}a||--b.countDownRef;b.countDownRef==0&&(b.loadProcess=="script"?c?setTimeout(u,10):u():b.loadProcess==
"image"&&(c?setTimeout(d,10):d()));this.zoneLoadCallback&&this.zoneLoadCallback((this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal);return b.countDownRef};b.afterLoadScriptProcess=function(){if(c.action=="link"&&c.url&&c.url.length){var a=function(){MugedaMraid.openLink(c.url,c.urlTarget)};this.dom.m_css("cursor","pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":f?"touchend":"mouseup",function(b){a();b.preventDefault();b.stopPropagation();return false})}c.action=="form"&&
c.form&&c.form.length&&(a=function(){MugedaBehavior.popupForm(JSON.parse(c.form))},this.dom.m_css("cursor","pointer").m_event(f?"touchend":"mouseup",function(b){a();b.preventDefault();b.stopPropagation();return false}));var d=function(a){var c=c||[];(a=a.layers)&&a.m_operate(function(){var a=this.units;a&&a.m_operate(function(){var a=this.objects;if(a){var e=function(){var a=this.type;a==2005?c.push(b.resDir+this.param.imageSrc):a==2021?c=c.concat(d(b.symbols[this.param.symbolId])):a==2014&&this.items.m_operate(function(){e.call(this)})};
a.m_operate(function(){e.call(this)})}})});return c};b.symbols={};b.audioSym={};b.audioSymName={};b.symbolsName={};b.aniData.symbols.m_operate(function(a){if(a.type===2)b.audioSym[a.id]=b.resDir+a.url,b.audioSymName[a.name]=b.resDir+a.url;else{b.symbols[a.id]=a;b.symbolsName[a.name]=a;var c=99999999,e=-c,h=c,g=-c;a.layers.m_operate(function(a){a.units.m_operate(function(a){a.objects.m_operate(function(a){a=a.param;c=Math.min(c,a.left);e=Math.max(e,a.right);h=Math.min(h,a.top);g=Math.max(g,a.bottom)})})});
a.bound={left:c,right:e,top:h,bottom:g,width:e-c,height:g-h};a.zoneCached=false;a.imageList=a.imageList||d(a);var l={guid:Mugeda.guidGen(),type:2021,param:{name:"",fillInfo:{fillStyle:0,fillImage:"",fillColors:[{p:0,r:144,g:200,b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:a.bound.width,rawHeight:a.bound.height,symbolId:a.id,offsetX:(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,offsetY:(a.bound.top+a.bound.bottom-a.ch-a.bound.height)/2,rotateCenterX:a.bound.width/2,rotateCenterY:a.bound.height/
2,strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-a.bound.width,right:0,top:0,bottom:a.bound.height,scaleX:1,scaleY:1,rotate:0,lineWidth:1,alpha:1,strokeColor:"#0683ff",startX:0,startY:0,endX:a.bound.width,endY:a.bound.height,width:a.bound.width,height:a.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},l=new n(l,null),f={};f.dom=document.createElement("div");f.objectHash={};f.offset={x:a.cw/2+(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,y:a.ch/2+(a.bound.top+
a.bound.bottom-a.ch-a.bound.height)/2};l.currentScene=f;l.initAndGetDom(f.dom,null);a.cachedInstance=l}});b.scene=new t("_main",c,true,0,{x:0,y:0},g,false,null,null);b.scene.initAndGetDom();b.updateRuleCached();c.action==="behavior"&&c.behavior&&b.handleBehavior(c.behavior,b.dom,b.id,b.scene);for(var e in b.scene.unitHash)b.scene.unitHash[e]instanceof p&&b.scene.unitHash[e].updateUnitVisibility(false);b.playTriggered=true;A();window.addEventListener("resize",A);b.zoneCachedMode?b.cacheZone(b.zoneStart,
b.zoneEnd,null):b.checkCountDownRef(true)};b.setupTimer=function(){if(!b.timerSetted){var a;if(Mugeda.FPSMeter){var c=document.createElement("div");c.style.cssText+="position: absolute; left: 0; right: 0; background:black; color:red; z-index:999999; width:2em;";a=function(a){c.innerHTML=a.toString()};this.dom.appendChild(c);setInterval(function(){Mugeda.FPSMeter&&a(b.fpsFrame);b.fpsFrame=0},1E3)}b.fpsFrame=0;b.timerSetted=true;b.lastFrameTime=e.getTime();b.nextRenderTime=b.lastFrameTime+b.frameTime;
b.timeDuring=0;b.dom.removeChild(b.loadingDiv);if(Mugeda.enablePulse&&Mugeda.pulse==null){b.insertRule("@"+e.css3Per+"keyframes MugedaPulse","from {"+e.css3Per+"transform: translate(-100px,0px);}to {"+e.css3Per+"transform: translate(-99px,0px);}");b.insertRule(".MugedaStamp","margin-top:-1em;");Mugeda.pulse=e("<div>").m_addClass("MugedaStamp");var d=document.getElementsByTagName("body")[0];d.insertBefore(Mugeda.pulse,d.firstChild);Mugeda.pulse.innerHTML="Mugeda";Mugeda.pulse.style[e.css3PerH+"Animation"]=
"MugedaPulse 1s infinite"}(d=b.dom.m_attr("onRenderReady"))&&eval(d);v.call(b,"renderReady");var h=function(){if(!b.stopRedraw){b.fpsFrame++;var a=e.getTime();if(Mugeda.flexibleFrameRate){var c=a-b.lastFrameTime;if(c>b.frameTime)c=b.frameTime;b.timeDuring=c}for(;C(b.scene,true););if(!(c=x.old)){var d;a:{for(d in b.paramUpdatePool){d=false;break a}d=true}c=!d}if(c){Mugeda.pulse&&(Mugeda.pulse.style[e.css3PerH+"AnimationPlayState"]="running");x.old&&w();for(var g in b.paramUpdatePool)d=b.paramUpdatePool[g],
d.object.style.cssText+=d.text;b.paramUpdatePool={};Mugeda.pulse&&(Mugeda.pulse.style[e.css3PerH+"AnimationPlayState"]="paused")}g=e.getTime();if(Mugeda.flexibleFrameRate)b.lastFrameTime=a,b.timeoutHandle=setTimeout(h,Math.max(40-(g-a),0));else{b.nextRenderTime+=b.frameTime;if(g>b.nextRenderTime)b.nextRenderTime=g;b.timeoutHandle=setTimeout(h,b.nextRenderTime-g)}}};b.timeoutHandle=setTimeout(h,0)}};typeof MugedaBehavior!="undefined"&&MugedaBehavior.processCloseButton&&MugedaBehavior.processCloseButton();
var C=function(a){if(a!=null){if(a.currentId==null||a.gotoFlag)a.currentId=a.nextId,a.gotoFlag=false;if(a.pauseFlag&&Mugeda.flexibleFrameRate)a.currentId=Math.floor(a.currentId),a.nextId=a.currentId,a.pauseFlag=false;for(var c=a.currentId,d=[],e=Math.floor(c),h=a.cachedAudio?a.cachedAudio[e]||[]:[],g=a.playingAudio||[],l={},f=0;f<h.length;f++){var o=h[f];g[o.hash]&&delete g[o.hash];if(o.audio.playStatus!=1)o.audio.play(),o.audio.playStatus=1;l[o.hash]=o}for(hash in g)if(f=g[hash],f.audio)f=f.audio,
f.pause(),f.playStatus=0,f.currentTime=0,f.playStatus=0;a.playingAudio=l;g=a.cachedVisibility[e]||[];l={};for(f=0;f<g.length;f++)if(g[f].userParam.visible!==false&&(a.lastRenderList[g[f].id]?a.lastRenderList[g[f].id]=false:Mugeda.nonDisplay?g[f].show():g[f].dom.m_css("display",g[f].dom.displayType!=null?g[f].dom.displayType:"block"),l[g[f].id]=g[f]),!x[g[f].id]){if(a.lastDrawId!=c&&g[f].unit&&g[f].unit.data.keyframes.length>1&&g[f].unit.data.objects.length==1){if(a.unitHash[g[f].unit.id].cachedFrame[c])h=
a.unitHash[g[f].unit.id].cachedFrame[c],g[f].data.param={rawWidth:h.rawWidth,rawHeight:h.rawHeight,width:h.width,height:h.height,rotateCenterX:h.rotateCenterX,rotateCenterY:h.rotateCenterY,left:h.left,top:h.top,rotate:h.rotate,alpha:h.alpha,behaviorObj:h.behaviorObj,action:h.action};else if((h=TimelineUnit.getKeyframe(g[f].unit.data,c))?Param.exchange(h.param,g[f].data.param,true):(h=TimelineUnit.getTweenParam(g[f].unit.data,c))&&Param.exchange(h,g[f].data.param,true),!Mugeda.flexibleFrameRate)h=
g[f].data.param,a.unitHash[g[f].unit.id].cachedFrame[c]={rawWidth:h.rawWidth,rawHeight:h.rawHeight,width:h.width,height:h.height,rotateCenterX:h.rotateCenterX,rotateCenterY:h.rotateCenterY,left:h.left,top:h.top,rotate:h.rotate,alpha:h.alpha,behaviorObj:h.behaviorObj,action:h.action};d.push(g[f])}if(g[f].symbolList)for(h=0;h<g[f].symbolList.length;h++)if(o=C(b.sceneHash[g[f].symbolList[h]]),typeof o=="string")return o;else d=d.concat(o);a.lastDrawId!=c&&(h=g[f].data.param.behaviorObj||g[f].data.param.behavior,
g[f].data.param.action=="behavior"&&h&&b.handleBehavior(h,g[f].dom,g[f].id,a,g[f].unit))}for(var m in a.lastRenderList)a.lastRenderList[m]&&(Mugeda.nonDisplay?a.lastRenderList[m].hide():a.lastRenderList[m].dom.m_css("display","none"));a.lastRenderList=l;if(a.playing&&!a.gotoFlag)Mugeda.flexibleFrameRate?a.nextId=a.currentId+b.timeDuring/b.frameTime:a.nextId++;for(v.call(a,"enterframe");a.frameout.length&&a.frameout[0].time==0;)m=a.frameout[0].fun,a.frameout.splice(0,1),m.call(a);a.frameout.length&&
a.frameout[0].time--;if(a.currentSegment&&a.currentSegment.from!=void 0)m=a.currentSegment,a.nextId>m.to&&(m.isLoop?a.gotoAndPlay(a.currentSegment.from):(a.gotoAndPause(m.to),a.lastDrawId!=c&&v.call(a,"segmentend")));else if(a.nextId>=a.length)a.id=="_main"&&!b.aniData.loop?a.nextId=a.length-1:a.looped==false?a.nextId=a.length-1:(a.nextId=0,showAnimation=false);a.currentId=a.nextId;a.lastDrawId=c;if(a.pauseFlag&&Mugeda.flexibleFrameRate&&c!=e)return"inval";if(a.id!="_main")return d;else{for(f=0;f<
d.length;f++)d[f].updateObjectParam();return null}}};d.prototype.createInstanceOfSymbol=function(a,c){var d=b.symbolsName[a],e=b.audioSymName[a];if(d)return d={guid:Mugeda.guidGen(),type:2021,param:{name:c,fillInfo:{fillStyle:0,fillImage:"",fillColors:[{p:0,r:144,g:200,b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:d.bound.width,rawHeight:d.bound.height,symbolId:d.id,offsetX:(d.bound.left+d.bound.right-d.cw-d.bound.width)/2,offsetY:(d.bound.top+d.bound.bottom-d.ch-d.bound.height)/
2,rotateCenterX:d.bound.width/2,rotateCenterY:d.bound.height/2,strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-d.bound.width,right:0,top:0,bottom:d.bound.height,scaleX:1,scaleY:1,rotate:0,lineWidth:1,alpha:1,strokeColor:"#0683ff",startX:0,startY:0,endX:d.bound.width,endY:d.bound.height,width:d.bound.width,height:d.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},new n(d,null);else if(e)return m(e)};d.prototype.unloadAnimation=function(){this.stopRedraw=true;
this.dom&&this.dom.parentNode.removeChild(this.dom)}}};d.prototype.checkLoad=function(a){a&&--this.imageNum;this.zoneLoadCallback&&this.zoneLoadCallback((this.zoneLoadTotal-this.imageNum)/this.zoneLoadTotal);this.imageNum==0&&(this.loadOver.call(this),this.setupTimer())};d.prototype.loadAudio=function(a){d.prototype.loadImage("audio",a)};d.prototype.loadImage=function(a,c,d){d==null&&(d=0);var b=this;b.countDownRef=b.countDownRef||0;if(a=="dom_back"){var d=c.dom,e=c.url,a=c.duringBuilding||false,
g=c.cacheZone||false;if(b.imageCache[e])if(b.imageCache[e].loaded){if(d)d.src=e;return false}else if(g){if(b.imageCache[e].loading)return false;var f=new Image;f.src=e;f.url=e;b.imageCache[e].loaded=true;b.countDownRef++;b.maxNum=b.countDownRef;f.m_event("load",function(){b.checkCountDownRef();b.imageCache[this.url].dom.m_operate(function(){this.src=e})}).m_event("error",function(){console.log("Error when loading image: "+f.src);b.checkCountDownRef()});return b.imageCache[e].loading=true}else return b.imageCache[e].dom.push(d),
a&&c.scene&&c.scene.id=="_main"&&c.unit&&(c.unit.imageList[e]=b.imageCache[e]),false;else return a?(b.imageCache[e]={image:null,url:e,dom:[d],loaded:false,duringBuilding:true},c.scene&&c.scene.id=="_main"&&c.unit&&(c.unit.imageList[e]=b.imageCache[e]),false):(f=new Image,f.src=e,f.url=e,b.imageCache[e]={image:f,dom:[d],loaded:false},b.countDownRef++,b.maxNum=b.countDownRef,f.m_event("load",function(){b.imageCache[this.url].loaded=true;b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+
"/"+b.maxNum;b.checkCountDownRef();b.imageCache[this.url].dom.m_operate(function(){this.src=e})}).m_event("error",function(){b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;b.checkCountDownRef();console.log("Error when loading image: "+f.src)}),true)}else if(a=="script"){b.countDownRef++;b.maxNum=b.countDownRef;for(a=b.scriptList.length;a<d;a++)b.scriptList[a]=[];b.scriptList[d]=b.scriptList[d]||[];b.scriptList[d].push(c);if(typeof j!="undefined")return Mugeda.loadJs(c);
var j=-1;if(!b.scriptLoadTimer)b.scriptLoadTimer=setTimeout(function(){var a=function(c){if(!(c>=b.scriptList.length)){var d=b.scriptList[c];d||a(++c);for(var e=d.length,h=0;h<d.length;h++)Mugeda.loadJs(d[h],function(){b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;b.checkCountDownRef();--e==0&&a(++c)},function(){console.log("Error when loading user script");b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;b.checkCountDownRef();--e==0&&a(++c)});
d.length==0&&a(++c)}};a(++j)},0)}else a="audio"};d.prototype.cacheZone=function(a,c,d,b){if(c==null||c<a)c=a;a<0&&(a=0);var e=this;if(e.scene){a++;c++;if(c>e.scene.length)c=e.scene.length;d==null&&(d=[]);e.zoneCachedMode=true;e.zoneLoadCallback=b||function(){};var f={},g={},j=0;for(a-=1;a<c;a++)e.zoneCached[a]||(e.mainSceneFrameUnitHash[a].m_operate(function(){if(!this.zoneCached){this.symbolList.m_operate(function(){e.symbols[this.toString()]&&(f[this.toString()]=e.symbols[this.toString()])});d.m_operate(function(){var a=
this.toString();f[e.symbolsName[a].id]=e.symbolsName[a]});var a=this.imageList;for(c in a)a[c].loaded==false&&(g[c]=a[c]);for(var b in f)if(a=f[b],a.zoneCached==false)a.imageList.m_operate(function(){var a=this.toString();g[a]||(g[a]={dom:[],url:a})}),a.zoneCached=true;for(var c in g)g[c].url&&e.loadImage("dom_back",{url:c,cacheZone:true,dom:[]})&&j++;this.zoneCached=true}}),e.zoneCached[a]=true);e.zoneLoadTotal=j;j==0&&(c=(this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal,e.zoneLoadCallback(c?
c:1))}else e.zoneCachedMode=true,e.zoneStart=a,e.zoneEnd=c};var p=function(a){var c=a.className,d=c.indexOf("guid");return d>-1?(a=c.indexOf(" ",d),a==-1?c.substr(d):c.substr(d,a-d)):(c="guid_"+Mugeda.guidGen(),a.m_addClass(c),c)};d.prototype.insertRuleCached=function(a,c){if(this.cachedRule){if(this.cachedRule.push({obj:a,cssText:c}),!this.waitToupdateRuleCached){this.waitToupdateRuleCached=true;var d=this;setTimeout(function(){d.updateRuleCached()},0)}}else this.insertRule("."+p(a),c)};d.prototype.updateRuleCached=
function(){for(var a=0;a<this.cachedRule.length;a++){var c=this.cachedRule[a];this.insertRule("."+p(c.obj),c.cssText)}this.cachedRule=[];delete this.waitToupdateRuleCached};d.prototype.insertRule=function(a,c){var d=this.externalStylesheet,b=this.indexedStylesheet;if(b[a])b[a].style.cssText+=c;else{var e=0,f=d.rules?d.rules.length:d.cssRules.length;d.insertRule?e=d.insertRule(a+"{"+c+"}",f):d.addRule&&(e=d.addRule(a,c,f));b[a]=d.rules?d.rules[e]:d.cssRules[e]}};d.prototype.handleBehavior=function(a,
c,d,b,e){var g=this;(typeof a=="string"?JSON.parse(a):a).m_operate(function(a,h){var j=null;a.unit=e?e.data||{}:{};a.param=a.param||{};var n=a.param.scope=="symbol"?b:g.scene;if(a.type=="play")j=function(){n.play.call(n)};else if(a.type=="pause")j=function(){n.pause.call(n)};else if(a.type=="gotoAndPlay")parseInt(a.param.frame_number),j=function(){n.gotoAndPlay.call(n,parseInt(a.param.frame_number)-2+1)};else if(a.type=="gotoAndStop"||a.type=="gotoAndPause")parseInt(a.param.frame_number),j=function(){n.gotoAndPause.call(n,
parseInt(a.param.frame_number)-2+1)};else if(a.type=="next")parseInt(a.param.frame_number),j=function(){n.gotoAndPause.call(n,Math.min(n.length,n.currentId+0+1))};else if(a.type=="previous")parseInt(a.param.frame_number),j=function(){n.gotoAndPause.call(n,Math.max(1,n.currentId-2+1))};else if(a.type!="callback")if(a.type=="audio"){if(a.param.audio_id)a.param.audio_url=g.audioSym[a.param.audio_id]}else a.type=="stopAllAudio"&&(j=function(){for(var a in g.audioList){var b=g.audioList[a];try{b.pause(),
b.currentTime=0}catch(c){}}});if(a.event=="click"){if(!n.clickEventAttached[d+"_"+h])c.style.cursor="pointer",c.m_event(f?"touchend":"mouseup",function(b){MugedaBehavior.processAction(a,"click",true);j&&j.call();b.preventDefault();b.stopPropagation();return false}),n.clickEventAttached[d+"_"+h]=true}else a.event=="appear"&&(j?j():MugedaBehavior.processAction(a,"appear",true))})};window.HTMLElement.prototype.m_attr=function(a,c){return typeof c!="undefined"?(this.setAttribute(a,c),this):this.getAttribute(a)};
window.HTMLElement.prototype.m_addClass=function(a){if(a&&typeof a==="string")this.className=this.className?this.className+" "+a:a;return this};window.HTMLElement.prototype.m_removeClass=function(a){if(a&&typeof a==="string"&&this.className)this.className=this.className.replace(RegExp("("+a+"\\s)|(\\s*"+a+")"),"");return this};window.HTMLElement.prototype.m_event=function(a,c,d){/(transition)|(other)/.test(a)&&(a=e.css3Per+(e.css3Per?a.substr(0,1).toUpperCase():a.substr(0,1))+a.substr(1));this.addEventListener(a,
c,d||false);return this};var w={transform:e.css3Per+"transform",transition:e.css3Per+"transition",textStroke:e.css3Per+"textStroke",textFillColor:e.css3Per+"textFillColor","transform-origin":e.css3Per+"transform-origin"};window.HTMLElement.prototype.m_css=function(a,c,d){w[a]&&(a=w[a]);if(c!=null)if(d)if(c!==""){if(this.guid==null)this.guid=Mugeda.guidGen();d.paramUpdatePool[this.guid]==null&&(d.paramUpdatePool[this.guid]={object:this,text:""});d.paramUpdatePool[this.guid].text+=a+":"+c+";"}else this.style[a]=
null;else a.indexOf("opacity")>-1||a.indexOf("tran")>-1||!Mugeda.nonDisplay&&a.indexOf("display")>-1||!Mugeda.nonDisplay&&a.indexOf("vertical")>-1?c!==""?this.style.cssText+=a+":"+c+";":this.style[a]=null:c!==""?Mugeda.currentAni.insertRuleCached(this,a+":"+c+";"):this.style[a]=null;else return e.getCurrentStyle(this,a);return this};window.HTMLElement.prototype.m_width=function(a){if(a!=void 0)return this.m_css("width",a+"px")};window.HTMLElement.prototype.m_height=function(a){if(a!=void 0)return this.m_css("height",
a+"px")};window.HTMLElement.prototype.m_transform=function(a,c,d,b,e,f,g){data={};a!=null&&(data.translateX=a.toString()+"px");c!=null&&(data.translateY=c.toString()+"px");d!=null&&(data.rotate=d.toString()+"rad");b!=null&&(data.scaleX=b.toString());b!=null&&(data.scaleY=e.toString());Mugeda.threeDRendering&&(data.translateZ="0px");var a="",j;for(j in data)a+=j+"("+data[j]+") ";if(f!=null||g!=null)this.m_css("transform-origin",(Math.abs(f)<0.01?0:Math.floor(100*f)*0.01)+"px "+(Math.abs(g)<0.01?0:
Math.floor(100*g)*0.01)+"px");return this.m_css("transform",a)};window.HTMLElement.prototype.m_append=function(a,c){a instanceof window.HTMLElement&&(c?this.insertBefore(a,c):this.appendChild(a));return this};window.HTMLElement.prototype.m_appendTo=function(a){a instanceof window.HTMLElement&&a.appendChild(this);return this};window.HTMLElement.prototype.m_setCapture=function(a){MugedaCss3.captureObject={object:this,capture:a==void 0?true:a};return this};window.HTMLElement.prototype.m_releasecapture=
function(){MugedaCss3.captureObject=null;return this};Array.prototype.m_operate=function(a,c){for(var d=c?this.length-1:0;c&&d>=0||!c&&d<this.length;c?d--:d++)if(a.call(this[d],this[d],d)==false)break};String.prototype.m_trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};return e}}(window.MugedaCss3);
var MugedaCompress={keys:"Ac,action,fM,form,tt,title,wt,width,ht,height,cl,color,sm,symbols,ly,layers,vr,version,sC,scripts,zI,zoomInfo,pd,pid,tp,type,nm,name,un,units,lI,layerId,fS,frameStart,fC,frameCount,ad,animated,vb,visible,ob,objects,pm,param,fI,fillInfo,cv,curve,kf,keyframes,md,mode,tw,tween,hK,hashKey,ix,index,rW,rawWidth,rH,rawHeight,sI,symbolId,oX,offsetX,oY,offsetY,rX,rotateCenterX,rY,rotateCenterY,it,items,nI,nodeId,gP,guidPath,ph,path,gi,guid,sm,smooth,iX,innerX,iY,innerY,uX,outerX,uY,outerY,cX,centerX,cY,centerY,ed,edges,st,section,fZ,fontSize,fT,fontStyle,fW,fontWeight,fF,fontFamily,tA,textAlign,tC,textContent,tD,textDecoration,cR,cornerRadius,iS,imageSrc,lC,lineCap,lJ,LineJoin,fR,frameRate,iP,innerPercent,TA,trackAnchors,MT,mugedaTrackAnchors".split(","),unzip:function(a){if(!a)return a;
if(a.zip!=1)return HaniData.unzip(a);a=JSON.parse(JSON.stringify(a));a=MugedaCompress.unzipKey(a);delete a.zip;if(a.rate==void 0)a.rate=12;if(a.width==void 0)a.width=600;if(a.height==void 0)a.height=400;if(a.guid==void 0)a.guid="";if(a.title==void 0)a.title="";if(a.script==void 0)a.script="";if(a.loop==void 0)a.loop=true;if(a.useCamera==void 0)a.useCamera=false;if(a.symbols==void 0)a.symbols=[];if(a.symbols.length)for(var e=a.symbols,c=0;c<e.length;c++){var d=e[c];d.runtime=true;d.dirtyFlag=false;
MugedaCompress.unzipLayers(d.layers)}MugedaCompress.unzipZoomInfo(a);MugedaCompress.unzipLayers(a.layers);return a},unzipKey:function(a){for(var e,a=JSON.stringify(a),c=0;c<MugedaCompress.keys.length;c+=2)e=eval('/"'+MugedaCompress.keys[c]+'":/g'),a=a.replace(e,'"'+MugedaCompress.keys[c+1]+'":');return JSON.parse(a)},unzipZoomInfo:function(a){for(var e=[],c=a.zoomInfo.split(",")||[],d=0;d<c.length;d+=4){var g=c[d];if(g.indexOf("i")==0){g=g.substr(1);d++;var f=c[d];f.indexOf("t")==0?(f=f.substr(1),
d++):f=null;e[g]={offsetLeft:Number(c[d]),offsetTop:Number(c[d+1]),rotation:Number(c[d+2]),zoomLevel:Number(c[d+3])};if(f)e[g].tween=f}}a.zoomInfo=e},unzipLayers:function(a){for(var e=0;e<a.length;e++){var c=a[e];c.hide=false;c.lock=false;for(var c=c.units,d=0;d<c.length;d++){var g=c[d];g.animated&&MugedaCompress.unzipPath(g);for(var f=g.keyframes||[],j=0;j<f.length;j++)MugedaCompress.unzipParam(f[j].param);if(g.visible==void 0)g.visible=true;MugedaCompress.unzipObjects(g.objects)}}},unzipPath:function(a){for(var e=
a.path.split(","),c=[],d=e.shift(),g=e.shift(),f=0;f<e.length;f+=7)c.push({id:Number(e[f]),backwardX:Number(e[f+1]),backwardY:Number(e[f+2]),forwardX:Number(e[f+3]),forwardY:Number(e[f+4]),nodeX:Number(e[f+5]),nodeY:Number(e[f+6])});c.length?(a.pathLeft=Number(d),a.pathTop=Number(g),a.path=c):(delete a.path,delete a.pathLeft,delete a.pathTop)},unzipObjects:function(a){for(var e=0;e<a.length;e++){var c=a[e];c.items&&c.items.length?MugedaCompress.unzipObjects(c.items):(c.id=0,c.name="",c.items=[],c.aryAnchors=
[]);MugedaCompress.unzipCurve(c);MugedaCompress.unzipParam(c.param)}},unzipCurve:function(a){var e=a.curve;if(typeof e=="string"){a.curve={};var e=e.split(","),c=e.shift()==1;a.curve.closed=c;for(var c=[],d=0;d<e.length;d+=6)c.push({backwardX:Number(e[d]),backwardY:Number(e[d+1]),forwardX:Number(e[d+2]),forwardY:Number(e[d+3]),nodeX:Number(e[d+4]),nodeY:Number(e[d+5])});a.curve.points=c}},unzipParam:function(a){if(a.strokeType==void 0)a.strokeType=0;if(a.frameRate==void 0)a.frameRate=12;if(a.lineCap==
void 0)a.lineCap="round";if(a.lineJoin==void 0)a.lineJoin="round";for(var e=a.m.split(";"),c=0;c<e.length;c++){var d=e[c].substr(0,1),g=e[c].substr(1);switch(d){case "L":a.left=Number(g);break;case "R":a.right=Number(g);break;case "T":a.top=Number(g);break;case "B":a.bottom=Number(g);break;case "S":a.startX=Number(g);break;case "P":a.startY=Number(g);break;case "E":a.endX=Number(g);break;case "N":a.endY=Number(g);break;case "X":a.scaleX=Number(g);break;case "Y":a.scaleY=Number(g);break;case "O":a.rotate=
Number(g);break;case "W":a.lineWidth=Number(g);break;case "A":a.alpha=Number(g);break;case "C":a.strokeColor=g}}if(a.startX==void 0)a.startX=a.left;if(a.startY==void 0)a.startY=a.top;if(a.endX==void 0)a.endX=a.right;if(a.endY==void 0)a.endY=a.bottom;a.width=a.right-a.left;a.height=a.bottom-a.top;delete a.m;MugedaCompress.unzipFillInfo(a)},unzipFillInfo:function(a){if(a.fillInfo){for(var e=a.fillInfo.split(";"),c=Number(e[0]),d=e[1].split(","),g=e[3],f=[],j=0;j<d.length;j+=5)f.push({p:Number(d[j]),
r:Number(d[j+1]),g:Number(d[j+2]),b:Number(d[j+3]),a:Number(d[j+4])});c={fillStyle:c,fillImage:g,fillColors:f};e=e[2].split(",");e.length!=4&&(e=[0,0,0,0]);c.fillStartPos={x:Number(e[0]),y:Number(e[1])};c.fillEndPos={x:Number(e[2]),y:Number(e[3])};a.fillInfo=c}}},TimelineUnit={getKeyframe:function(a,e){var c=a.hashKey["key_"+e];c||(c=null);return c},getTweenParam:function(a,e){var c=a.keyframes.length,d=a.keyframes[0],g=null,f=null,j=0,y=-1;bezierInterpolate=function(a,c,b,d,e,f){return Math.pow(c,
3)*b+3*Math.pow(c,2)*a*d+3*c*Math.pow(a,2)*e+Math.pow(a,3)*f};var v=function(a,c,b){var d=1-b,e=a.nodeY,f=a.forwardY,g=c.backwardY,h=c.nodeY,a=bezierInterpolate(b,d,a.nodeX,a.forwardX,c.backwardX,c.nodeX),b=bezierInterpolate(b,d,e,f,g,h);return{x:a,y:b}};if(c>1&&!a.hashKey["key_"+e]){for(var p=1;p<c;p++){g=a.keyframes[p];if(g.id>e){y=p;break}d=g;j=p;g=null}if(g){c=Math.abs(g.id-d.id);f=e-d.id;c=TimelineUnit.getTweenFactors(c,d.tween);if(Mugeda.flexibleFrameRate){c.push(1);var p=Math.floor(f),w=Math.ceil(f),
h=c[p],c=c[w],c=w==p?c:(f-w)*(c-h)/(w-p)+c}else c=c[f];f={left:0,top:0,right:0,bottom:0,startX:0,startY:0,endX:0,endY:0,width:0,height:0,alpha:1,rotate:0,scaleX:1,scaleY:1,lineWidth:1,strokeType:0,strokeColor:"#0683ff",lineCap:"round",lineJoin:"round",fillInfo:{fillStyle:0,fillImage:"",fillStartPos:{x:32,y:10},fillEndPos:{x:80,y:100},fillColors:[{p:0,r:144,g:200,b:255,a:1},{p:0.8,r:255,g:144,b:200,a:1},{p:1,r:200,g:255,b:144,a:1}]}};Param.tweenParam(f,d.param,g.param,c);if(a.pathMode>Hanimation.PATHMODE_DEFAULT&&
j>=0&&y>=0)g=a.path,j=v(g[j],g[y],c),j.x=a.pathLeft+j.x-f.rotateCenterX,j.y=a.pathTop+j.y-f.rotateCenterY,f.startX=j.x,f.startY=j.y,f.endX=f.startX+f.width,f.endY=f.startY+f.height,f.left=f.startX,f.top=f.startY,f.right=f.endX,f.bottom=f.endY}}if(!f)f=d.param;return f},getTweenFactors:function(a,e){var c=[],d=new TWEEN.Tween({x:0});d.to({x:1},1E3);e||(e="Linear.EaseNone");for(var e=e.split("."),g=e.length,f=TWEEN.Easing;g;)f=f[e[e.length-g]],g--;d.easing(f);for(g=0;g<a;g++)c[g]=d.getFactor(g/a);return c}},
TWEEN=TWEEN||function(){var a,e,c,d,g=[];return{start:function(a){c=setInterval(this.update,1E3/(a||60))},stop:function(){clearInterval(c)},add:function(a){g.push(a)},getAll:function(){return g},removeAll:function(){g=[]},remove:function(c){a=g.indexOf(c);a!==-1&&g.splice(a,1)},update:function(){a=0;e=g.length;for(d=(new Date).getTime();a<e;)g[a].update(d)?a++:(g.splice(a,1),e--)}}}();
TWEEN.Tween=function(a){var e={},c={},d={},g=1E3,f=0,j=null,y=TWEEN.Easing.Linear.EaseNone,v=null,p=null,w=null;this.to=function(c,e){e!==null&&(g=e);for(var f in c)a[f]!==null&&(d[f]=c[f]);return this};this.start=function(){TWEEN.add(this);j=(new Date).getTime()+f;for(var g in d)a[g]!==null&&(e[g]=a[g],c[g]=d[g]-a[g]);return this};this.stop=function(){TWEEN.remove(this);return this};this.delay=function(a){f=a;return this};this.easing=function(a){y=a;return this};this.chain=function(a){v=a};this.onUpdate=
function(a){p=a;return this};this.onComplete=function(a){w=a;return this};this.getFactor=function(a){a=Math.min(1,Math.max(0,a));return y(a)};this.update=function(d){var f,o;if(d<j)return true;d=(d-j)/g;d=d>1?1:d;o=y(d);for(f in c)a[f]=e[f]+c[f]*o;p!==null&&p.call(a,o);return d==1?(w!==null&&w.call(a),v!==null&&v.start(),false):true}};TWEEN.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{},Step:{}};
TWEEN.Easing.Linear.EaseNone=function(a){return a};TWEEN.Easing.Quadratic.EaseIn=function(a){return a*a};TWEEN.Easing.Quadratic.EaseOut=function(a){return-a*(a-2)};TWEEN.Easing.Quadratic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a:-0.5*(--a*(a-2)-1)};TWEEN.Easing.Cubic.EaseIn=function(a){return a*a*a};TWEEN.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};TWEEN.Easing.Cubic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a:0.5*((a-=2)*a*a+2)};TWEEN.Easing.Quartic.EaseIn=function(a){return a*a*a*a};
TWEEN.Easing.Quartic.EaseOut=function(a){return-(--a*a*a*a-1)};TWEEN.Easing.Quartic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};TWEEN.Easing.Quintic.EaseIn=function(a){return a*a*a*a*a};TWEEN.Easing.Quintic.EaseOut=function(a){return(a-=1)*a*a*a*a+1};TWEEN.Easing.Quintic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};TWEEN.Easing.Sinusoidal.EaseIn=function(a){return-Math.cos(a*Math.PI/2)+1};
TWEEN.Easing.Sinusoidal.EaseOut=function(a){return Math.sin(a*Math.PI/2)};TWEEN.Easing.Sinusoidal.EaseInOut=function(a){return-0.5*(Math.cos(Math.PI*a)-1)};TWEEN.Easing.Exponential.EaseIn=function(a){return a==0?0:Math.pow(2,10*(a-1))};TWEEN.Easing.Exponential.EaseOut=function(a){return a==1?1:-Math.pow(2,-10*a)+1};TWEEN.Easing.Exponential.EaseInOut=function(a){return a==0?0:a==1?1:(a*=2)<1?0.5*Math.pow(2,10*(a-1)):0.5*(-Math.pow(2,-10*(a-1))+2)};
TWEEN.Easing.Circular.EaseIn=function(a){return-(Math.sqrt(1-a*a)-1)};TWEEN.Easing.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};TWEEN.Easing.Circular.EaseInOut=function(a){return(a/=0.5)<1?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};TWEEN.Easing.Elastic.EaseIn=function(a){var e,c=0.1,d=0.25;if(a==0)return 0;if(a==1)return 1;d||(d=0.3);!c||c<1?(c=1,e=d/4):e=d/(2*Math.PI)*Math.asin(1/c);return-(c*Math.pow(2,10*(a-=1))*Math.sin((a-e)*2*Math.PI/d))};
TWEEN.Easing.Elastic.EaseOut=function(a){var e,c=0.1,d=0.25;if(a==0)return 0;if(a==1)return 1;d||(d=0.3);!c||c<1?(c=1,e=d/4):e=d/(2*Math.PI)*Math.asin(1/c);return c*Math.pow(2,-10*a)*Math.sin((a-e)*2*Math.PI/d)+1};
TWEEN.Easing.Elastic.EaseInOut=function(a){var e,c=0.1,d=0.25;if(a==0)return 0;if(a==1)return 1;d||(d=0.3);!c||c<1?(c=1,e=d/4):e=d/(2*Math.PI)*Math.asin(1/c);return(a*=2)<1?-0.5*c*Math.pow(2,10*(a-=1))*Math.sin((a-e)*2*Math.PI/d):c*Math.pow(2,-10*(a-=1))*Math.sin((a-e)*2*Math.PI/d)*0.5+1};TWEEN.Easing.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};TWEEN.Easing.Back.EaseOut=function(a){return(a-=1)*a*(2.70158*a+1.70158)+1};
TWEEN.Easing.Back.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};TWEEN.Easing.Bounce.EaseIn=function(a){return 1-TWEEN.Easing.Bounce.EaseOut(1-a)};TWEEN.Easing.Bounce.EaseOut=function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};
TWEEN.Easing.Bounce.EaseInOut=function(a){return a<0.5?TWEEN.Easing.Bounce.EaseIn(a*2)*0.5:TWEEN.Easing.Bounce.EaseOut(a*2-1)*0.5+0.5};TWEEN.Easing.Step.EaseIn=function(){return 0};
Param={exchange:function(a,e,c){c?(c=a,a=e):c=e;a.startX=c.startX;a.startY=c.startY;a.endX=c.endX;a.endY=c.endY;a.left=c.left;a.right=c.right;a.top=c.top;a.bottom=c.bottom;a.width=c.width;a.height=c.height;a.alpha=c.alpha;a.scaleX=c.scaleX;a.scaleY=c.scaleY;a.rotate=c.rotate;a.rotateCenterX=c.rotateCenterX;a.rotateCenterY=c.rotateCenterY;a.customPivot=c.customPivot},tweenParam:function(a,e,c,d){a.startX=e.startX+d*(c.startX-e.startX);a.startY=e.startY+d*(c.startY-e.startY);a.endX=e.endX+d*(c.endX-
e.endX);a.endY=e.endY+d*(c.endY-e.endY);a.width=e.width+d*(c.width-e.width);a.height=e.height+d*(c.height-e.height);a.alpha=e.alpha+d*(c.alpha-e.alpha);a.scaleX=e.scaleX+d*(c.scaleX-e.scaleX);a.scaleY=e.scaleY+d*(c.scaleY-e.scaleY);a.rotate=e.rotate+d*(c.rotate-e.rotate);a.rotateCenterX=e.rotateCenterX+d*(c.rotateCenterX-e.rotateCenterX);a.rotateCenterY=e.rotateCenterY+d*(c.rotateCenterY-e.rotateCenterY);a.customPivot=true;if(e.fillInfo&&e.fillInfo&&(e.fillInfo.fillStyle==1||e.fillInfo.fillStyle==
2))a.fillInfo.fillStartPos.x=e.fillInfo.fillStartPos.x+d*(c.fillInfo.fillStartPos.x-e.fillInfo.fillStartPos.x),a.fillInfo.fillStartPos.y=e.fillInfo.fillStartPos.y+d*(c.fillInfo.fillStartPos.y-e.fillInfo.fillStartPos.y),a.fillInfo.fillEndPos.x=e.fillInfo.fillEndPos.x+d*(c.fillInfo.fillEndPos.x-e.fillInfo.fillEndPos.x),a.fillInfo.fillEndPos.y=e.fillInfo.fillEndPos.y+d*(c.fillInfo.fillEndPos.y-e.fillInfo.fillEndPos.y);a.left=a.startX;a.top=a.startY;a.right=a.startX+a.width;a.bottom=a.startY+a.height}};
Hanimation={PATHMODE_DEFAULT:0};
(function(){Mugeda.initCss3Player=function(){document.addEventListener("mousedown",MugedaCss3.handleCapture,true);document.addEventListener("mouseup",MugedaCss3.handleCapture,true);document.addEventListener("mouseover",MugedaCss3.handleCapture,true);document.addEventListener("mouseout",MugedaCss3.handleCapture,true);document.addEventListener("mousemove",MugedaCss3.handleCapture,true);Mugeda.loadJs=function(c,d,e){if(a(c))d&&d();else{var f=document.createElement("script");f.src=c;document.getElementsByTagName("head")[0].appendChild(f);
f.onload=f.onreadystatechange=function(){!(this.readyState&&this.readyState=="loading")&&d&&(d(),d=function(){})};f.onerror=function(){f.parentNode.removeChild(f);e()}}};var a=function(a){var c=document.getElementsByTagName("script"),e=false;for(d=0;d<c.length;d++)if(c[d].src&&c[d].src.indexOf(a)!=-1&&(c[d].readyState=="loaded"||c[d].readyState=="complete")){e=true;break}return e};Mugeda.startAnimation=function(a,c,d,e,f){var g=navigator.userAgent.toLowerCase();Mugeda.isAndroid=g.indexOf("android")>
-1;Mugeda.androidVersion=parseFloat(g.slice(g.indexOf("android")+8));var j=MugedaCss3.initAnimation(Mugeda.data[a],c,d,e,function(){f&&(MugedaCss3.stage[f]=j)});Mugeda.scene=j;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript)};if(Mugeda.css3PlayerLoaded==void 0)for(var e=document.getElementsByClassName("MugedaStage"),c=e.length,d=0;d<c;d++){var g=e[d],f=g.getAttribute("mugedaName"),j=MugedaCss3.initAnimation(Mugeda.data[f],g.m_attr("hasScript")=="true"?"actions_"+(f.substr(f.indexOf("_")+
1)+".js"):"",g,g.m_attr("relDir")||"",function(){MugedaCss3.stage[f]=j;--c==0&&typeof Mugeda.script=="function"&&Mugeda.script()});Mugeda.scene=j;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript)}else if(Mugeda.css3PlayerLoaded=2,Mugeda.creationToBeLoad){for(d=0;d<Mugeda.creationToBeLoad.length;d++)Mugeda.creationToBeLoad[d].start();Mugeda.creationToBeLoad=[]}}})();
document&&document.getElementsByTagName&&document.getElementById&&document.body?Mugeda.initCss3Player():document.addEventListener("DOMContentLoaded",Mugeda.initCss3Player);
