typeof Mugeda=="undefined"&&(Mugeda={});Mugeda.data=Mugeda.data||{};Mugeda.script=Mugeda.script||[];Mugeda.scriptCounter={};Mugeda.customScript="";Mugeda.scene=void 0;Mugeda.mapFrameNameId=Mugeda.mapFrameNameId||[];Mugeda.unzipAniData=function(a){a=MugedaCompress.unzip(a);if(a.script&&a.script.length)a.script=unescape(a.script);return a};
Mugeda.getFrameLength=function(a){for(var d=1,c=a.length-1;c>=0;c--)for(var e=a[c],h=e.units.length,j=0;j<h;j++){var l=e.units[j],l=l.frameStart+l.frameCount;d<l&&(d=l)}return d};
Mugeda.getWindowSize=function(){var a=document.documentElement,d=a&&a.clientHeight===0;if(typeof document.clientWidth=="number")return{width:document.clientWidth,height:document.clientHeight};else{if(!d){var d=document,c=d.createElement("div");c.style.height="2500px";d.body.insertBefore(c,d.body.firstChild);var e=d.documentElement.clientHeight>2400;d.body.removeChild(c);d=e}if(d)a=document.body;return{width:a.clientWidth,height:a.clientHeight}}};
Mugeda.updateViewport=function(a,d,c,e){if(typeof _mrmcp=="undefined"||_mrmcp.render_mode!="inline"&&_mrmcp.render_mode!="embedded"){if(c){var h=c.aniData.metadata?c.aniData.metadata.adaptMode:null;if(h=="none"||h==null)if(c.aniData.metadata=c.aniData.metadata||{},h=c.aniData.metadata.adaptMode=e?"none_mobile":"none_pc",!e)document.body.style.overflow="auto";if("contain,cover,width,width2,height,none_mobile,none_pc,fill".split(",").indexOf(h)>-1)a=document.createElement("div"),c.dom.style.position=
"absolute",c.dom.style.overflow="hidden",c.dom.style.left="0",c.dom.style.top="0",c.dom.style.right="0",c.dom.style.bottom="0",c.dom.style.margin="auto",c.dom.appendChild(a),c.dom=a}if(h==="width2")document.body.style.overflow="auto";document.documentElement.style.height="100%";document.body.style.height="100%"}};Mugeda.getCanvas=function(){return document.getElementsByClassName("MugedaStage")[0]};Mugeda.randPlus=0;
Mugeda.guidGen=function(){var a=new Date-new Date("2012/1/1")+""+Math.random().toString().substr(2,4);return Number(a).toString(36)+""+Mugeda.randPlus++};Mugeda.getMugedaObject=function(){return Mugeda.scene};Mugeda.loadUrl=function(a){return MugedaMraid.loadUrl(a)};Mugeda.enable3DRendering=function(a){a==void 0&&(a=false);this.threeDRendering=a};Mugeda.showFPS=function(){Mugeda.FPSMeter=true};Mugeda.enableNonDisplay=function(a){a==void 0&&(a=false);this.nonDisplay=a};
Mugeda.enableFlexibleFrameRate=function(a){a==void 0&&(a=false);this.flexibleFrameRate=a};Mugeda.enablePulseAnimation=function(a){a==void 0&&(a=false);Mugeda.enablePulse=a};
Mugeda.log=function(a){if(!Mugeda.logConsole)Mugeda.logConsole=document.createElement("div"),Mugeda.logConsole.style.display="block",Mugeda.logConsole.style.position="fixed",Mugeda.logConsole.style.background="#000",Mugeda.logConsole.style.color="#FFF",Mugeda.logConsole.style.left=0,Mugeda.logConsole.style.top=0,document.body.appendChild(Mugeda.logConsole);if(typeof a=="string"||a)Mugeda.logConsole.innerHTML=a;return Mugeda.logConsole.innerHTML};Mugeda.getAudioCache=function(a,d){return Mugeda.currentAni.audioBeList[d]};
Mugeda.getVideoCache=function(a,d){return Mugeda.currentAni.videoBeList[d]};Mugeda.setTextAsFlexbox=function(){this.textAsFlexbox=true};
window.MugedaCss3=function(a){if(!a){Mugeda.customScript="";var d=function(a){if(/^<.+>$/.test(a))return document.createElement(a.match(/^<(.+)>$/)[1]);else if(/^#.+/.test(a))return document.getElementById(a.match(/^#(.+)/)[1])};d.stage={};d.getAnimation=function(a){return d.stage[a]};d.initAnimation=function(a,d,c,b,k){a=new e(a,d,c,b);Mugeda.currentAni=a;document.dispatchEvent&&(d=document.createEvent("Events"),d.initEvent("mugedaReady",true,true),document.dispatchEvent(d));a.initDom(k);return a};
d.getCssBackgroundColor=function(a){var m=a.fillInfo;if(m.fillStyle==0)return"rgba("+m.fillColors[0].r+","+m.fillColors[0].g+","+m.fillColors[0].b+","+m.fillColors[0].a+")";else if(m.fillStyle==1||m.fillStyle==2){var c=m.fillStartPos.x,b=m.fillStartPos.y,e=m.fillEndPos.x,j=m.fillEndPos.y,s=a.rawWidth||a.width,h=a.rawHeight||a.height,a=Math.atan2(j-b,e-c),v=function(b,a,f){return{x:b*Math.cos(f)-a*Math.sin(f),y:b*Math.sin(f)+a*Math.cos(f)}},q=v(0,h,-a).x,l=v(s,h,-a).x,u=v(s,0,-a).x,p=v(c,b,-a).x,o=
v(e,j,-a).x,w=Math.max(0,q,l,u),t=Math.min(0,q,l,u),q=function(b,a,f){var C={};C.pm=f;C.r=(a.r-b.r)/(a.pm-b.pm)*(f-b.pm)+parseFloat(b.r);C.g=(a.g-b.g)/(a.pm-b.pm)*(f-b.pm)+parseFloat(b.g);C.b=(a.b-b.b)/(a.pm-b.pm)*(f-b.pm)+parseFloat(b.b);C.a=(a.a-b.a)/(a.pm-b.pm)*(f-b.pm)+parseFloat(b.a);return C},v=function(b,a){return"rgba("+Math.round(b.r)+","+Math.round(b.g)+","+Math.round(b.b)+","+b.a+") "+(a==void 0?b.pm:a)+"%"};if(m.fillStyle==1){m.fillColors.m_operate(function(b){b.pm=100/(w-t)*(p+(o-p)*
b.p-t)+0});for(var c=false,x="",e=0;e<m.fillColors.length;e++)if(b=m.fillColors[e],s=b.pm,c)if(s<100){if(x+=", "+v(b),e==m.fillColors.length-1){x+=", "+v(b,100);break}}else{x+=", "+v(q(b,m.fillColors[e-1],100),100);break}else{if(s<0)if(e<m.fillColors.length-1)if(m.fillColors[e+1].pm<0)continue;else x+=", "+v(q(b,m.fillColors[e+1],0));else x+=", "+v(b,0),x+=", "+v(b,100);else x+=", "+v(b,0),x+=", "+v(b);c=true}x="linear-gradient("+(d.browser.msie?a*180/Math.PI+90:-a*180/Math.PI)+"deg"+x+")"}else if(m.fillStyle==
2){a=Math.sqrt(Math.pow(c-e,2)+Math.pow(b-j,2));x="";for(e=0;e<m.fillColors.length;e++)x+=", "+v(m.fillColors[e],m.fillColors[e].p*100);x="radial-gradient("+c/s*100+"% "+b/h*100+"%, "+a+"px "+a+"px"+x+")"}return d.css3Per?d.css3Per.toLowerCase()+x:x}else return"transparent"};d.handleCapture=function(a){if(!a.redirected&&d.captureObject!=null){var m=document.createEvent("MouseEvents");m.initMouseEvent(a.type,true,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,
a.shiftKey,a.metaKey,a.button,a.relatedTarget);m.redirected=true;d.captureObject.object.dispatchEvent(m);a.type=="mouseup"&&d.captureObject&&d.captureObject.object.m_releasecapture()}};d.getCurrentStyle=function(a,d){if(document.defaultView){var c=document.defaultView.getComputedStyle(a,null);return c?c.getPropertyValue(d):null}else return a.currentStyle[d]};d.getEventPosition=function(a,m,c,b){var e,c=c||1;if(a.changedTouches&&(a=a.changedTouches[0],a==null))return null;e=a.clientX;a=a.clientY;if(m){for(var j=
m,h=0,l=0;j&&j.tagName!="BODY";)h+=j.offsetTop,l+=j.offsetLeft,j=j.offsetParent;e=e-l+window.pageXOffset-parseInt(d.getCurrentStyle(m,"border-left-width"));a=a-h+window.pageYOffset-parseInt(d.getCurrentStyle(m,"border-top-width"))}b&&(e/=c,a/=c);return{x:e,y:a}};d.escapeHTML=function(){var a={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","/":"&#x2F;"},d=/[&<>"'\/]/g;return function(c){return(""+c).replace(d,function(b){return a[b]})}}();var c=window;(function(){var a=c.performance;d.getTime=
a&&(a.now||a.webkitNow)?a[a.now?"now":"webkitNow"].bind(a):function(){return+new Date}})();a=navigator.userAgent.toLowerCase();a={version:(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1],safari:/webkit/.test(a),opera:/opera/.test(a),msie:(/msie/.test(a)||/trident/.test(a))&&!/opera/.test(a),mozilla:/mozilla/.test(a)&&!/(compatible|webkit)/.test(a)&&!/trident/.test(a)};d.browser=a;if(a.safari)d.css3Per="-webkit-",d.css3PerH="webkit";else if(a.opera)d.css3Per="-o-",d.css3PerH="o";else if(a.msie)d.css3Per=
"",d.css3PerH="";else if(a.mozilla)d.css3Per="-moz-",d.css3PerH="Moz";var e=function(a,d,c,b){this.aniData=a=a.zip?Mugeda.unzipAniData(a):a;this.title=a.title;this.width=a.width;this.height=a.height;this.dom=c;this.rate=a.rate;this.frameTime=1E3/a.rate;this.frameTimeString=this.frameTime+"ms";this.sceneHash={};this.mainSceneFrameUnitHash={};this.zoneCached={};this.event={};this.stopRedraw=false;this.resDir=b;this.scriptFile="string"==typeof d?d:null;this.frameParamCache={};this.paramUpdatePool={};
this.audioList={};this.scriptList=[]};e.prototype.getScene=function(){return this.scene};var h={mousedown:1,mouseup:1,click:1,dblclick:1,mouseover:1,mouseout:1,mousemove:1,touchstart:1,touchmove:1,touchend:1,inputstart:2,inputmove:2,inputend:2},j=navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i);
window.navigator.userAgent.indexOf("Android");var l=function(a,c,e){a=="inputstart"?a=j?"touchstart":"mousedown":a=="inputmove"?a=j?"touchmove":"mousemove":a=="inputend"&&(a=j?"touchend":"mouseup");if(h[a]==1&&this.dom){var b=this,k={fun:c,dir:function(a){a.postionGotton=false;a.inputX==void 0&&(Object.defineProperty(a,"inputX",{get:function(){return d.getEventPosition(a,b.thisAni.scene.dom,b.thisAni.overAllScaleX,b.thisAni).x}}),Object.defineProperty(a,"inputY",{get:function(){return d.getEventPosition(a,
b.thisAni.scene.dom,b.thisAni.overAllScaleY,b.thisAni).y}}));c.call(b,a)}};this.event[a]?this.event[a].push(k):this.event[a]=[k];this.dom.addEventListener(a,k.dir,e||false)}else this.event[a]?this.event[a].push(c):this.event[a]=[c];return this},A=function(a,d,c){a=="inputstart"?a=j?"touchstart":"mousedown":a=="inputmove"?a=j?"touchmove":"mousemove":a=="inputend"&&(a=j?"touchend":"mouseup");if(h[a]==1&&this.dom){if(this.event[a]){for(var b=this.event[a].length-1;b>=0;b--)this.event[a][b].fun&&this.event[a][b].fun==
d&&(this.dom.removeEventListener(a,this.event[a][b].dir,c||false),this.event[a].splice(b,1));this.event[a].length==0&&delete this.event[a]}}else if(this.event[a]){for(b=this.event[a].length-1;b>=0;b--)this.event[a][b]==d&&this.event[a].splice(b,1);this.event[a].length==0&&delete this.event[a]}return this},u=function(a,d,c,b,e){var j=[];if(this.event[a]){for(var h=[],l=0;l<this.event[a].length;l++)h[l]=this.event[a][l];for(l=0;l<h.length;l++)j.push(h[l].call(this,d,c,b,e))}return j};e.prototype.addEventListener=
l;e.prototype.removeEventListener=A;e.prototype.initDom=function(a){if(this.aniData&&this.dom){this.thisAni=this;this.countDownRef=0;this.imageCache=[];this.maxNum=0;Mugeda.updateViewport(this.aniData,null,this,j);this.loadOver=a;var c=this.aniData,h=this.dom,b=this;setTimeout(function(){window.scroll(0,0)},0);b.iOS=function(){var a={};if(/iP(hone|od|ad)/.test(navigator.platform)){var b=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);a.version=parseInt(b[1],10)+0.1*parseInt(b[2],10)}return a}();
var k=function(a){var b=null;window.weixinAudioLoader&&window.weixinAudioLoader[a]?b=window.weixinAudioLoader[a]:(b=new Audio(a),b.load());b.addEventListener("ended",function(){b.loop?(b.currentTime=0,b.play()):b.currentTime=0});return b},t=function(a,b){var d=document.createElement("video"),c=document.createElement("source");if(b)videDom.poster=b;c.src=a;c.type="video/mp4";d.appendChild(c);return d},s=function(a,c,d,D,f,e,g,m,n){this.id=a;this.data=c;this.pageNum=this.id=="_main"&&this.data.pages&&
this.data.pages.length?this.data.pages.length+1:1;this.length=0;this.playing=d;this.currentId=null;this.nextId=0;this.offset=f;this.dom=e;this.pageDom=[];this.pages=[];this.currentPageIndex=null;this.objectHash={};this.unitHash=[];this.isSymbol=g;this.clickEventAttached={};this.nameHash={};this.scriptHash={};this.segment={};this.currentSegment={};b.sceneHash[this.id]=this;this.event={};this.frameout=[];this.thisAni=b;this.parentScene=m;this.cachedVisibility={};this.lastRenderList={};this.frameLength=
0;this.frameUnitHash={};this.zoneCached={};if(g)this.object=n;a=g?c.id:"_main";b.frameParamCache[a]=b.frameParamCache[a]||{};this.frameParamCache=b.frameParamCache[a]};s.prototype.getFrameId=function(a){var a=a.toString(),b=this.id=="_main"?"":this.id+"_";a.match(/^\d+$/)||(keyId=b+a,a=Mugeda.mapFrameNameId[keyId]);return a=parseInt(a)};s.prototype.getObjectByName=function(a){return this.nameHash[a]};s.prototype.initAndGetDom=function(){var a=this,b=a.pageNum;if(b>1)for(;b--;){var c=d("<div>");a.dom.m_append(c);
c.m_css("position","absolute").m_css("width","100%").m_css("height","100%").m_css("overflow","hidden").m_css("display","none").m_addClass("page");a.pageDom.push(c)}else a.pageDom.push(a.dom);var D=Mugeda.getFrameLength(a.data.layers),f={length:D,startFrame:a.length};a.pages.push(f);a.length+=D;a.data.layers.m_operate(function(b){b=new E(b,a);b.page=f;b.initAndGetDom(a.pageDom[0])},true);a.id=="_main"&&a.data.pages&&a.data.pages.length&&a.data.pages.m_operate(function(b,g){var c=b.layers;D=Mugeda.getFrameLength(c);
b={length:D,startFrame:a.length};a.pages.push(b);a.length+=D;c.m_operate(function(c){c=new E(c,a);c.page=b;c.initAndGetDom(a.pageDom[g+1])},true)})};s.prototype.play=function(){this.playing=true;b.stopRedraw=false;return this};s.prototype.pause=function(){this.pauseFlag=true;this.playing=false;u.call(this,"pause");return this};s.prototype.getFrameCount=function(){if(this.frameCount==void 0){for(var a=0,b=0,c=this.data.layers,d=0;d<c.length;d++){for(var a=0,f=c[d].units,e=0;e<f.length;e++)a+=f[e].frameCount;
a>b&&(b=a)}this.frameCount=b}return this.frameCount};s.prototype.freeze=function(a){a=a||{};a.mode=a.mode||"default";for(var b=this.dom,b=b.classList.contains("symbol")?b:b.getElementsByClassName("symbol"),c=b.length;c--;){var d=b[c];if(d&&d.object&&d.object.scene)d.object.scene.playingBeforeFreezing=d.object.scene.playing,a.mode=="default"?d.object.scene.pause():a.mode=="beginning"?d.object.scene.gotoAndPause(0):a.mode=="ending"&&d.object.scene.gotoAndPause(d.object.scene.getFrameCount()-1)}this.playingBeforeFreezing=
this.playing;a.mode=="default"?this.pause():a.mode=="beginning"?this.gotoAndPause(0):a.mode=="ending"&&this.gotoAndPause(this.getFrameCount()-1)};s.prototype.unfreeze=function(a){a=a||{};a.mode=a.mode||"default";for(var b=this.dom,b=b.classList.contains("symbol")?b:b.getElementsByClassName("symbol"),c=b.length;c--;){var d=b[c];d&&d.object&&d.object.scene&&(a.mode=="default"?a.loop&&d.object.scene.currentId==d.object.scene.length-1?d.object.scene.gotoAndPlay(0):d.object.scene.play():a.mode=="beginning"&&
d.object.scene.gotoAndPlay(0))}if(this.id=="_main"||this.id.indexOf("_page")===0||this.playingBeforeFreezing||a.force)a.mode=="default"?this.play():a.mode=="beginning"&&this.gotoAndPlay(0)};s.prototype.gotoAndPlay=function(a){this.gotoFlag=true;this.nextId=this.getFrameId(a);return this.play()};s.prototype.gotoAndPause=function(a){this.nextId=this.getFrameId(a);this.gotoFlag=true;return this.pause()};s.prototype.setSegment=function(a,b,d,c){this.segment[a]={from:Math.min(b,this.length),to:Math.min(d,
this.length),isLoop:c};return this};s.prototype.playSegment=function(a){(this.currentSegment=this.segment[a])&&this.gotoAndPlay(this.currentSegment.from);return this};s.prototype.setFrameout=function(a,b){for(var d=this.frameout.length,c=0,f=0;f<this.frameout.length;f++){var e=this.frameout[f];if(c+e.time>a){d=f;break}c+=e.time}this.frameout.splice(d,0,{time:a-c,fun:b});return this};s.prototype.removeChild=function(a){if(a.unit){var b=a.unit.data.objects;if(a.parentGroup)b=a.parentGroup.data;b.m_operate(function(c,
g){if(c.guid==a.id)return b.splice(g,1),false})}a.dom.parentNode.removeChild(a.dom);this.nameHash[a.name]&&delete this.nameHash[a.name];delete this.objectHash[a.id];if(this.scriptHash[a.id])delete this.scriptHash[a.id];else{var c=a.unit?a.unit.data.frameStart:0,d=a.unit?a.unit.data.frameStart+a.unit.data.frameCount-1:a.currentScene.frameLength-1,f=this.cachedVisibility;setTimeout(function(){for(var b=c;b<=d;b++)for(var g=f[b].length,e=0;e<g;e++)if(f[b][e].id==a.id){f[b].splice(e,1);break}},0)}return this};
s.prototype.appendChild=function(a,b){if(a.name&&this.nameHash[a.name])throw"object name: "+a.name+" had been used";this.nameHash[a.name]=a;for(var c=0;c<(this.frameLength||1);c++)this.cachedVisibility[c]=this.cachedVisibility[c]||[],this.cachedVisibility[c].push(a);a.currentScene=this;a.initAndGetDom(this.dom,b&&b.dom?b.dom:null);Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";return a};s.prototype.getPageIndexByFrameId=function(a){var b=this.pages,c=b[this.currentPageIndex];if(c&&
a>=c.startFrame&&a<c.startFrame+c.length)return this.currentPageIndex;for(var c=b.length,d=0;d<c;d++){var f=b[d];if(a>=f.startFrame&&a<f.startFrame+f.length)return d}return a>=b[c-1].startFrame+b[c-1].length?c-1:0};s.prototype.addEventListener=l;s.prototype.removeEventListener=A;var E=function(a,b){this.id=a.id;this.name=a.name;this.data=a;this.unitList=[];this.scene=b;this.page=null};E.prototype.initAndGetDom=function(a){var b=this;b.data.units.m_operate(function(c){c=new v(c,b);b.unitList.push(c);
c.initAndGetDom(a)},true)};var v=function(a,b){this.data=a;this.layer=b;this.objectList=[];this.symbolList=[];this.imageList=[];this.id=a.id;b.scene.unitHash[a.id]=this;b.scene.frameParamCache[this.id]=b.scene.frameParamCache[this.id]||{};this.cachedFrame=b.scene.frameParamCache[this.id];this.zoneCached=false};v.prototype.initAndGetDom=function(a){var c=this,d=this.layer.scene,f=this.data.frameStart,e=this.data.frameCount,m=d.frameLength,g=0;if(c.layer&&c.layer.page)f+=c.layer.page.startFrame,m=c.layer.page.length,
g=c.layer.page.startFrame;if(this.data&&(this.data.audio||this.data.audioId))this.audio=this.data.audioId?k(b.audioSym[this.data.audioId]):k(b.resDir+this.data.audio);if(this.audio){for(var r=Mugeda.guidGen(),n=f;n<f+e;n++)d.cachedAudio=d.cachedAudio||[],d.cachedAudio[n]=d.cachedAudio[n]||[],d.cachedAudio[n].push({audio:this.audio,start:n==f,hash:r});b.audioList[r]=this.audio}this.data.keyframes.length&&this.data.keyframes.m_operate(function(a){a.id+=g});if(!this.data.objects||this.data.objects.length==
0){if(f=this.data.keyframes[0],f.name)e=f.name,m=e.indexOf("_")+1,e=e.substr(m),e=(d.id=="_main"?"":d.id+"_")+e,Mugeda.mapFrameNameId[e]=f.id}else{if(this.data.keyframes.length)this.data.hashKey={},this.data.keyframes.m_operate(function(a){c.data.hashKey["key_"+a.id]=a;if(a.name){var b=a.name,g=b.indexOf("_")+1,b=b.substr(g),b=(d.id=="_main"?"":d.id+"_")+b;Mugeda.mapFrameNameId[b]=a.id}});this.data.objects.m_operate(function(b){b=new y(b,c);c.objectList.push(b);b.initAndGetDom(a);if(b.symbolIdList)c.symbolList=
c.symbolList.concat(b.symbolIdList);Mugeda.nonDisplay?b.hide():b.dom.style.cssText+="display:none;"});d=this.layer.scene;for(n=f;n<f+e;n++)d.cachedVisibility[n]=d.cachedVisibility[n]||[],d.cachedVisibility[n]=d.cachedVisibility[n].concat(this.objectList);d.frameLength=Math.max(m,f+e);if(this.layer.scene)for(n=f;n<f+e;n++)this.layer.scene.frameUnitHash[n]=this.layer.scene.frameUnitHash[n]||[],this.layer.scene.frameUnitHash[n].push(this)}};v.prototype.updateUnitVisibility=function(a){this.objectList.m_operate(function(b){Mugeda.nonDisplay?
a?b.show():b.hide():b.dom.m_css("display",a?b.dom.displayType||"block":"none")})};var q=function(a,b,c,d){this.parent=a;this.dom=b;this.data=a.data.items;this.objectList=[];this.unit=c;this.scene=d};q.prototype.initAndGetDom=function(){var a=this;this.data.length!=0&&this.data.m_operate(function(b){b=new y(b,a.unit,{inGroup:true,group:a});if(!b.currentScene)b.currentScene=a.scene;a.objectList.push(b);b.initAndGetDom(a.dom)})};var y=MugedaCss3.aObject=function(a,c,d){d=d||{};a=this.data=JSON.parse(JSON.stringify(a));
this.currentScene=(this.unit=c)?c.layer.scene:null;this.id=Mugeda.guidGen();c&&(this.currentScene.nameHash[a.param.name]=this);if(d.inGroup)this.offset={x:0,y:0},this.parentGroup=d.group;this.event={};this.thisAni=b;this.userParam={};var f=[],e=[],m=function(a){if(a.items)for(var b=0;b<a.items.length;b++){var c=a.items[b];c.type==2021||c.type==2023?(c.symbolSceneId=Mugeda.guidGen(),f.push(c.symbolSceneId),e.push(c.param.symbolId)):a.type==2014&&m(c)}};if(!d.inGroup)if(a.type==2014)m(a);else if(a.type==
2021||a.type==2023)a.symbolSceneId=Mugeda.guidGen(),f.push(a.symbolSceneId),e.push(a.param.symbolId);if(f.length)this.symbolList=f,this.symbolIdList=e;Object.defineProperty(this,"name",{get:function(){return this.data.param.name},set:function(a){if(this.currentScene.nameHash[a])throw"name had been used before";this.currentScene.nameHash[a]=this.currentScene.nameHash[this.data.param.name];delete this.currentScene.nameHash[this.data.param.name];this.data.param.name=a}});a.type==2005&&Object.defineProperty(this,
"src",{get:function(){return this.userParam.src},set:function(a){this.userParam.src=a;this.dom.tagName=="DIV"?this.dom.childNodes[0].src=a:this.dom.src=a}});Object.defineProperty(this,"width",{get:function(){return this.data.param.width},set:function(a){var b=this.data.param.width/this.scaleX,c=this.rotateCenterX/this.scaleX;this.rotateCenterX=0;this.scaleX=a/b;this.rotateCenterX=c*this.scaleX}});Object.defineProperty(this,"height",{get:function(){return this.data.param.height},set:function(a){var b=
this.data.param.height/this.scaleY,c=this.rotateCenterY/this.scaleY;this.rotateCenterY=0;this.scaleY=a/b;this.rotateCenterY=c*this.scaleY}});Object.defineProperty(this,"left",{get:function(){return this.data.param.left},set:function(a){this.userParam.x=a-this.userParam.ox+this.userParam.rx;this.data.param.left=a;this.data.param.right=this.data.param.left+this.data.param.width;o(this)}});Object.defineProperty(this,"right",{get:function(){return this.data.param.right},set:function(a){this.data.param.right=
a;this.data.param.left=a-this.data.param.width;this.userParam.x=this.data.param.left-this.userParam.ox+this.userParam.rx;o(this)}});Object.defineProperty(this,"top",{get:function(){return this.data.param.top},set:function(a){this.data.param.top=a;this.userParam.y=a-this.userParam.oy+this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;o(this)}});Object.defineProperty(this,"bottom",{get:function(){return this.data.param.bottom},set:function(a){this.data.param.bottom=
a;this.data.param.top=a-this.data.param.height;this.userParam.y=this.data.param.top-this.userParam.oy+this.userParam.ry;o(this)}});Object.defineProperty(this,"x",{get:function(){return this.userParam.x},set:function(a){this.userParam.x=a;this.data.param.left=a+this.userParam.ox-this.userParam.rx;this.data.param.right=this.data.param.left+this.data.param.width;o(this)}});Object.defineProperty(this,"y",{get:function(){return this.userParam.y},set:function(a){this.userParam.y=a;this.data.param.top=a+
this.userParam.oy-this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;o(this)}});Object.defineProperty(this,"rotateCenterX",{get:function(){return this.userParam.rx},set:function(a){this.data.param.rotateCenterX=this.userParam.rx=Math.round(a);this.userParam.rsx=a/this.userParam.sx;this.userParam.x=this.data.param.left+a-this.userParam.ox;o(this)}});Object.defineProperty(this,"rotateCenterY",{get:function(){return this.userParam.ry},set:function(a){this.data.param.rotateCenterY=
this.userParam.ry=Math.round(a);this.userParam.rsy=a/this.userParam.sy;this.userParam.y=this.data.param.top+a-this.userParam.oy;o(this)}});Object.defineProperty(this,"scaleX",{get:function(){return this.userParam.sx},set:function(a){this.userParam.rx=this.data.param.rotateCenterX=this.userParam.rx/this.userParam.sx*a;this.userParam.sx=this.data.param.scaleX=a;this.data.param.width=this.data.param.rawWidth*a;this.data.param.left=this.userParam.x+this.userParam.ox-this.userParam.rx;this.data.param.right=
this.data.param.left+this.data.param.width;o(this)}});Object.defineProperty(this,"scaleY",{get:function(){return this.userParam.sy},set:function(a){this.userParam.ry=this.data.param.rotateCenterY=this.userParam.ry/this.userParam.sy*a;this.userParam.sy=this.data.param.scaleY=a;this.data.param.height=this.data.param.rawHeight*a;this.data.param.top=this.userParam.y+this.userParam.oy-this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;o(this)}});Object.defineProperty(this,
"rotate",{get:function(){return this.data.param.rotate},set:function(a){this.data.param.rotate=a;o(this)}});Object.defineProperty(this,"alpha",{get:function(){return this.data.param.alpha},set:function(a){this.data.param.alpha=a;o(this)}});this.userParam.visible=true;Object.defineProperty(this,"visible",{get:function(){return this.userParam.visible},set:function(a){(this.userParam.visible=a)?this.dom.m_css("display",this.dom.displayType||"block",b):this.dom.m_css("display","none",b)}});Object.defineProperty(this,
"text",{get:function(){if(this.data.type==2010)return unescape(this.data.param.textContent)},set:function(a){if(this.data.type==2010)this.data.param.textContent=escape(a);o(this)}});Object.defineProperty(this,"url",{get:function(){},set:function(a){this.data.param.url=a}})},B={},p=function(){delete B.old;for(objId in B)B[objId].updateObjectParam();B={}},o=function(a){B[a.id]=a;B.old=true;setTimeout(p,0)};y.prototype.setCapture=function(a){this.dom.m_setCapture(a)};y.prototype.releaseCapture=function(a){this.dom.m_releasecapture(a)};
y.prototype.initAndGetDom=function(a,c){var f=this.data,e;if(f.param.left===null)this.unit&&this.unit.data.keyframes&&this.unit.data.keyframes.length>=2?f.param=JSON.parse(JSON.stringify(this.unit.data.keyframes[0].param)):console.log("Fatal error: object (ID: "+f.guid+") param is lost!");var m=false;if(this.currentScene&&this.currentScene.cachedSymbolScene)var m=true,h=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[f.guid].dom.className)[0];var g=f.param;
switch(f.type){case 2003:case 2004:case 2009:if(m)break;var r=g.lineWidth,n=Math.floor(g.lineWidth/2);e=d("<div>");var i=d("<div>");i.m_addClass("guid_"+Mugeda.guidGen());r&&i.m_css("border",r+"px solid "+g.strokeColor).m_css("position","absolute").m_css("top",-n+"px").m_css("bottom",-n+"px").m_css("left",-n+"px").m_css("right",-n+"px").m_appendTo(e);if(f.type==2009){var k=f.cornerRadius[0]+"px ";e.m_css("border-radius",k+k+k+k);e.m_css("border-top-left-radius",k);e.m_css("border-top-right-radius",
k);e.m_css("border-bottom-left-radius",k);e.m_css("border-bottom-right-radius",k)}else if(f.type==2004){var k=g.width/2+"px",p=g.height/2+"px";e.m_css("border-radius","50%");Mugeda.isAndroid&&(e.m_css("border-top-left-radius",k+" "+p),e.m_css("border-top-right-radius",k+" "+p),e.m_css("border-bottom-left-radius",k+" "+p),e.m_css("border-bottom-right-radius",k+" "+p))}e.m_css("background",d.getCssBackgroundColor(g));r&&(f.type==2009?(k=f.cornerRadius[0]+n+"px ",i.m_css("border-radius",k+k+k+k),i.m_css("border-top-left-radius",
k),i.m_css("border-top-right-radius",k),i.m_css("border-bottom-left-radius",k),i.m_css("border-bottom-right-radius",k)):f.type==2004&&(k=g.width/2+n+"px",p=g.height/2+n+"px",i.m_css("border-radius","50%"),Mugeda.isAndroid&&(i.m_css("border-top-left-radius",k+" "+p),i.m_css("border-top-right-radius",k+" "+p),i.m_css("border-bottom-left-radius",k+" "+p),i.m_css("border-bottom-right-radius",k+" "+p))));break;case 2005:if(!g.imageSrc.length)g.imageSrc="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";
if(g.imageSrc.length>0){this.userParam=this.userParam||[];this.userParam.src=(g.imageSrc.indexOf("data:")==0?"":b.resDir)+g.imageSrc;if(m){r=h;h.tagName=="DIV"&&(r=h.childNodes[0]);b.loadImage("dom_back",{dom:r,url:b.resDir+g.imageSrc,duringBuilding:b.zoneCachedMode,scene:this.currentScene,unit:this.unit});break}e=d("<img>");e.m_attr("draggable","false");if(g.keepAspect){var r=g.rawWidth,n=g.rawHeight,i=g.width,k=g.height,p=i/r*n,o=i,l=o=0;p>k?(p=k,o=(i-k/n*r)/2,e.m_css("padding-left",o.toString()+
"px"),e.m_css("padding-right",o.toString()+"px")):(l=(k-p)/2,e.m_css("padding-top",o.toString()+"px"),e.m_css("padding-bottom",o.toString()+"px"))}b.loadImage("dom_back",{dom:e,url:(g.imageSrc.indexOf("data:")==0?"":b.resDir)+g.imageSrc,duringBuilding:b.zoneCachedMode,scene:this.currentScene,unit:this.unit})}break;case 2010:if(g.tO=="scroll")this.unit.scrollTexts=this.unit.scrollTexts||[],this.unit.scrollTexts.push(this),b.insertRule(".overflow::-webkit-scrollbar","width: 4px;height:0px;"),b.insertRule(".overflow::-webkit-scrollbar-thumb",
"background-color:rgba(255,255,255,0.5);"),b.insertRule(".overflow::-webkit-scrollbar-track","-webkit-box-shadow: inset 0 0 4px rgba(0, 0, 0, 0.5);background-color: inset 0 0 4px rgba(0, 0, 0, 0.5);");if(Mugeda.textAsFlexbox){if(m){h.displayType="";break}e=d("<div>");r=d("<div>").m_appendTo(e).m_css("width","100%");r.innerHTML=g.tO=="visible"?unescape(g.textContent).replace(/\n/g,"<br>").replace(/\s\s/g," &nbsp;"):"<div class='overflow' style='height:"+g.height+"px; overflow: "+g.tO+";'>"+unescape(g.textContent).replace(/\n/g,
"<br>").replace(/\s\s/g," &nbsp;")+"</div>";r.txt=g.textContent;e.m_css("font-size",g.fontSize+"px").m_css("font-weight",g.fontWeight).m_css("font-family",g.fontFamily).m_css("text-stroke",g.lineWidth/2+"px "+g.strokeColor).m_css("text-shadow","0 "+(g.lineWidth/2<1?1:g.lineWidth/2)+"px "+g.strokeColor).m_css("line-height",parseInt(g.fontSize)+4+"px").m_css("text-align",g.textAlign||"left").m_css("text-fill-color",d.getCssBackgroundColor(g)).m_css("color","rgba("+g.fillInfo.fillColors[0].r+","+g.fillInfo.fillColors[0].g+
","+g.fillInfo.fillColors[0].b+","+g.fillInfo.fillColors[0].a+")").m_css("padding-top","1px").m_addClass("flex").m_addClass(g.textVAlign);j||e.m_css("user-select","none");e.displayType=""}else{if(m){h.displayType="table";break}e=d("<div>");r=d("<div>").m_appendTo(e).m_css("display","table-cell").m_css("vertical-align",g.textVAlign||"baseline");r.displayType="table-cell";r.innerHTML=g.tO=="visible"?d.escapeHTML(unescape(g.textContent)).replace(/\n/g,"<br>").replace(/\s/g," &nbsp;"):"<div class='overflow' style='height:"+
g.height+"px; overflow: "+(g.tO=="scroll"?"auto":g.tO)+";'>"+d.escapeHTML(unescape(g.textContent)).replace(/\n/g,"<br>").replace(/\s/g," &nbsp;")+"</div>";r.txt=g.textContent;e.m_css("font-size",g.fontSize+"px").m_css("font-weight",g.fontWeight).m_css("font-family",g.fontFamily).m_css("display","table").m_css("text-stroke",g.lineWidth/2+"px "+g.strokeColor).m_css("text-shadow","0 "+(g.lineWidth/2<1?1:g.lineWidth/2)+"px "+g.strokeColor).m_css("line-height",parseInt(g.fontSize)+4+"px").m_css("text-align",
g.textAlign||"left").m_css("text-fill-color",d.getCssBackgroundColor(g)).m_css("color","rgba("+g.fillInfo.fillColors[0].r+","+g.fillInfo.fillColors[0].g+","+g.fillInfo.fillColors[0].b+","+g.fillInfo.fillColors[0].a+")").m_css("padding-top","1px");j||e.m_css("user-select","none");e.displayType="table"}this.unit.data.pg&&r.m_addClass("progress");g.fontStyle&&e.m_css("font-style",g.fontStyle);g.textDecoration&&e.m_css("text-decoration",g.textDecoration);break;case 2014:m?e=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[f.guid].dom.className)[0]:
(e=d("<div>"),e.m_addClass("group"));this.group=r=new q(this,e,this.unit,this.currentScene);r.initAndGetDom(e);break;case 2023:r=function(a){return{fillInfo:null,imageSrc:g.imageSrc,rawWidth:g.rawWidth,rawHeight:g.rawHeight*g.frameNum,left:0,right:g.rawWidth,top:-g.rawHeight*a,bottom:g.rawHeight*(g.frameNum-a),scaleX:1,scaleY:1,rotate:0,alpha:1,width:g.rawWidth,height:g.rawHeight*g.frameNum}};n=Mugeda.guidGen();i=Math.ceil(g.frameNum/g.fps*b.rate);b.symbols[n]={id:n,name:n,cw:b.aniData.width,ch:b.aniData.height,
layers:[{id:0,name:"\u56fe\u5c420",units:[{id:Mugeda.guidGen(),layerId:0,frameStart:0,frameCount:i,animated:true,objects:[{guid:Mugeda.guidGen(),type:2005,param:r(0)}],keyframes:[],hashKey:[],visible:true}]}]};k=null;for(p=0;p<i;p++){var G=Math.min(Math.round(p/b.rate*g.fps),g.frameNum-1);G!=k&&(b.symbols[n].layers[0].units[0].keyframes.push({id:p,mode:0,tween:"Step.EaseIn",param:r(G)}),k=G);b.symbols[n].layers[0].units[0].guessKeyframe=false}g.symbolId=n;g.offsetX=-b.aniData.width/2;g.offsetY=-b.aniData.height/
2;case 2021:if(!b.symbols[g.symbolId])break;r=b.symbols[g.symbolId];if(m)n=b.symbols[g.symbolId].cw/2+g.offsetX,i=b.symbols[g.symbolId].ch/2+g.offsetY,n=this.scene=new s(this.data.symbolSceneId,b.symbols[g.symbolId],true,0,{x:n,y:i},h,true,this.currentScene,this),n.cachedSymbolScene=this.currentScene.cachedSymbolScene.objectHash[f.guid].scene;else{e=d("<div>");e.m_addClass("symbol");f.type==2023&&e.m_css("overflow","hidden");n=b.symbols[g.symbolId].cw/2+g.offsetX;i=b.symbols[g.symbolId].ch/2+g.offsetY;
n=this.scene=new s(this.data.symbolSceneId,b.symbols[g.symbolId],true,0,{x:n,y:i},e,true,this.currentScene,this);if(f.type==2023){if(g.looped==null)g.looped=true;this.scene.looped=g.looped}if(r.cachedInstance)symCache=r.cachedInstance.scene,n.dom.innerHTML=symCache.dom.innerHTML,n.cachedSymbolScene=symCache}n.initAndGetDom();break;case 2024:if(r=JSON.parse(f.param.Form),e=d("<div>"),MugedaBehavior.popupForm(r,true),i=r.iframeDiv){i.style.padding=0;e.appendChild(i);var n=i.querySelectorAll(".inputlabel"),
i=i.querySelectorAll(".popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select"),w=r.hwObj;Array.prototype.forEach.call(n,function(a){a.style.width=w.l+"px"});Array.prototype.forEach.call(i,function(a){a.style.width=w.r+"px"})}}if(e||m)if(m)this.dom=h,this.currentScene.objectHash[f.guid]=this,this.updateObjectParam({staticMode:true,readyCachedMode:true,isImage:f.type==2005}),this.dom.object=this;else{e.m_addClass("layer_"+(this.unit?this.unit.layer.id:"script")).m_addClass("guid_"+
this.id).m_css("position","absolute").m_css("left",0).m_css("top",0).m_css("backface-visibility","hidden");if(g.vF||g.hF)m=d("<div>").m_css("position","absolute").m_append(e),e.m_css("top","0").m_css("left","0").m_css("right","0").m_css("bottom","0").m_css("transform",(g.vF?"scaleY(-1) ":"")+(g.hF?"scaleX(-1)":"")),e=m,m.className="guid_"+Mugeda.guidGen();e.m_addClass("object");a.m_append(e,c);this.dom=e;this.dom.object=this;this.currentScene.objectHash[f.guid]=this;this.updateObjectParam({staticMode:true,
isImage:f.type==2005,dw:o,dh:l});if(f.type===2024)e=e.firstChild,m=f.param.width,h=f.param.height,f=function(a,b,c,d){var e=a,g=b,f=1;a/b>c/d?(e=c,g=c*(b/a),f=c/a):(g=d,e=d/(b/a),f=d/b);return{w:e,h:g,mt:(d-g)/2,ml:(c-e)/2,r:f}}(288,MugedaBehavior.getPopupFormHeight(JSON.parse(f.param.Form)),m,h),e.parentNode.m_transform(0,0,null,1,1,0,0),e.m_transform(f.ml,f.mt,null,f.r,f.r,0,0)}};y.prototype.addEventListener=l;y.prototype.removeEventListener=A;y.prototype.getPath=function(){for(var a=this,b="";;){b=
(a.name||"@"+a.id)+"/"+b;if(!a.currentScene)return"~"+b.substr(0,b.length-1);if(a.currentScene.id=="_main")return b.substr(0,b.length-1);if(!a.currentScene.object)return"<-"+b.substr(0,b.length-1);a=a.currentScene.object}};y.prototype.setParam=function(a){a.call(this,this.param);this.updateObjectParam({param:this.param});Mugeda.nonDisplay?this.param.hide?this.hide():this.show():this.dom.m_css("display",this.param.hide?"none":this.dom.displayType!=null?this.dom.displayType:"block")};y.prototype.getParam=
function(){this.param.hide=this.param.hide||false;return this.param};y.prototype.setButton=function(a,b,c){var d=this.scene;d&&(c==void 0&&(c=a),typeof a=="number"&&(a={from:a,to:a,isLoop:false}),typeof b=="number"&&(b={from:b,to:b,isLoop:false}),typeof c=="number"&&(c={from:c,to:c,isLoop:false}),d.setSegment("__normal",a.from,a.to,a.isLoop),d.setSegment("__push",b.from,b.to,b.isLoop),d.setSegment("__up",c.from,c.to,c.isLoop),d.playSegment("__normal"),this.addEventListener("inputstart",function(){this.disabled||
this.scene.playSegment("__push")}),this.addEventListener("inputend",function(){this.scene.currentSegment==d.segment.__push&&this.scene.playSegment("__up")}),this.addEventListener("mouseout",function(){this.scene.currentSegment==d.segment.__push&&this.scene.playSegment("__up")}));this.dom.m_css("cursor","pointer");return this};y.prototype.appendChild=function(a,b){var c=a===this.currentScene.nameHash[a.name];if(!c&&a.name&&this.currentScene.nameHash[a.name])throw"object name: "+a.name+" had been used";
this.currentScene.nameHash[a.name]=a;if(c)this.dom.appendChild(a.dom);else{for(var d=this.unit?this.unit.data.frameStart:0,c=this.unit?d+this.unit.data.frameCount:this.currentScene.frameLength||1;d<c;d++)this.currentScene.cachedVisibility[d]=this.currentScene.cachedVisibility[d]||[],this.currentScene.cachedVisibility[d].push(a);a.currentScene=this.currentScene;a.initAndGetDom(this.dom,b&&b.dom?b.dom:null)}Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";this.group&&this.group.objectList.push(a);
return a};y.prototype.updateObjectParam=function(a){a=a||{};staticMode=a.staticMode||false;readyCachedMode=a.readyCachedMode||false;var c=this.dom,e=this.offset||this.currentScene.offset,f=a.param||this.data.param,m=this;this.param=f;if(staticMode&&(a.isImage?(f.rawWidth=f.width-(a.dw?a.dw*2:0),f.rawHeight=f.height-(a.dh?a.dh*2:0)):(f.rawWidth=f.rawWidth||f.width,f.rawHeight=f.rawHeight||f.height),readyCachedMode||(c.m_width(f.rawWidth).m_height(f.rawHeight),(f.vF||f.hF)&&c.childNodes[0].m_width(f.rawWidth).m_height(f.rawHeight)),
f.action))if(f.action=="link"&&f.url&&f.url.length){var i=function(){MugedaMraid.openLink(f.url,f.urlTarget)};c.m_css("cursor","pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":j?"touchend":"mouseup",function(a){i();a.preventDefault();a.stopPropagation();return false})}else if(f.action=="form"&&f.form&&f.form.length)i=function(){MugedaBehavior.popupForm(JSON.parse(f.form))},c.m_css("cursor","pointer").m_event(j?"touchend":"mouseup",function(a){i();a.preventDefault();a.stopPropagation();
return false});else if(f.action=="behavior"&&f.behavior)a=JSON.parse(f.behavior),f.behaviorObj=a,a.m_operate(function(a){if(a.type=="audio"){var c=a.param.audio_id?b.audioSym[a.param.audio_id]:b.resDir+a.param.audio_url;b.audioBeList=b.audioBeList||{};var d=Mugeda.guidGen();a.param.audioId=d;b.audioBeList[d]=k(c);if(a.param.audio_loop=="1")b.audioBeList[d].loop=true;a.param.audio_name&&(m.currentScene.nameHash[a.param.audio_name]=b.audioBeList[d]);b.audioList[d]=b.audioBeList[d]}else if(a.type=="video")c=
a.param.video_id?b.videoSym[a.param.video_id]:b.resDir+a.param.video_url,d=Mugeda.guidGen(),b.videoBeList=b.videoBeList||{},b.videoBeList.videoId=t(c),a.param.video_name&&(m.currentScene.nameHash[a.param.video_name]=b.videoBeList[d])});var a=f.width/f.rawWidth,g=f.height/f.rawHeight,r=f.rotateCenterX!=void 0?f.rotateCenterX:f.width/2,n=f.rotateCenterY!=void 0?f.rotateCenterY:f.height/2,h=Math.round(r/a),p=Math.round(n/g),r=h*a,n=p*g,s=f.left-(h-r)-e.x,o=f.top-(p-n)-e.y,l=f.rotate;s.toString().indexOf("e")>
-1&&(s=0);o.toString().indexOf("e")>-1&&(o=0);a.toString().indexOf("e")>-1&&(a=0);g.toString().indexOf("e")>-1&&(g=0);l.toString().indexOf("e")>-1&&(l=0);this.userParam.x=s+h;this.userParam.y=o+p;this.userParam.rx=r;this.userParam.ry=n;this.userParam.sx=a;this.userParam.sy=g;this.userParam.rsx=h;this.userParam.rsy=p;this.userParam.ox=e.x;this.userParam.oy=e.y;c.m_css("opacity",Math.floor(100*f.alpha)*0.01,b).m_css("transform-origin",h.toString()+"px "+p.toString()+"px",b);this.beforeHiddenTrans="translate("+
s.toString()+"px,"+o.toString()+"px) rotate("+l.toString()+"rad) scale("+a.toString()+","+g.toString()+")";this.hidden||c.m_css("transform",this.beforeHiddenTrans,m.realtimeUpdate?null:b);if(f.textContent!=void 0&&c.childNodes[0].txt!=f.textContent)c.childNodes[0].innerHTML=f.tO=="visible"?d.escapeHTML(unescape(f.textContent)).replace(/\n/g,"<br>").replace(/\s/g," &nbsp;"):"<div class='overflow' style='height:"+f.height+"px; overflow: "+f.tO+";'>"+d.escapeHTML(unescape(f.textContent)).replace(/\n/g,
"<br>").replace(/\s/g," &nbsp;")+"</div>",c.childNodes[0].txt=f.textContent};y.prototype.hide=function(){if(!this.hidden)return this.dom.m_css("transform","translate(-9999999px, -99999999px)",b),this.hidden=true,this};y.prototype.show=function(){if(this.hidden)return this.beforeHiddenTrans&&this.dom.m_css("transform",this.beforeHiddenTrans,b),this.hidden=false,this};y.prototype.clone=function(a){var b=JSON.parse(JSON.stringify(this.data));b.param.name=a;b.guid=Mugeda.guidGen();return new y(b,null)};
a=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(a);b.styleBlock=a;b.externalStylesheet=a.sheet||a.styleSheet;b.indexedStylesheet={};b.cachedRule=[];this.dom.m_attr("name",c.title).m_addClass("MugedaStage").m_width(c.width).m_height(c.height).m_css("background-color",c.color).m_css("background-image",c.image?"url("+c.image+")":"").m_css("background-repeat","no-repeat").m_css("background-size",c.width+"px "+c.height+"px").m_css("overflow","hidden").m_css("position",
"relative");Mugeda.enablePulse&&this.dom.m_css("transform","translate(0,0)");this.dom.style.webkitTapHighlightColor="rgba(0,0,0,0)";a=b.aniData.loadInfo||{};a.style&&Mugeda.loadProcessHandle&&Mugeda.loadProcessHandle[a.style]?(b.loadProcessHandle=new Mugeda.loadProcessHandle[a.style]({loadInfo:a,thisAni:b}),b.loadProcessHandle.init()):(b.loadingDiv=d("<div>").m_css("line-height",c.height+"px").m_css("text-align","center").m_css("background","black").m_css("color","white").m_css("font-family","arial"),
b.dom.insertBefore(b.loadingDiv,b.dom.firstChild),b.loadingDiv.innerHTML="Loading...",b.loadingDiv.id="loadingDiv");var w=b.dom,z=function(){b.adaption=b.adaption||{};if(typeof _mrmcp=="undefined"||_mrmcp.render_mode!="inline"&&_mrmcp.render_mode!="embedded"){var a=document.body.offsetWidth/c.width,d=document.body.offsetHeight/c.height,d=document.body.offsetHeight/c.height,f=c.metadata?c.metadata.adaptMode:null,e=1,i=c.width,k=c.height;b.adaption.type=f;switch(f){case "contain":e=Math.max(0.001,Math.min(a,
d));break;case "cover":e=Math.max(a,d,0.001);break;case "width":case "width2":case "none_mobile":e=Math.max(a,0.001);break;case "height":e=Math.max(d,0.001)}a=f=="fill"?a:e;d=f=="fill"?d:e;i*=a;k*=d;w.parentNode.style.width=i+"px";w.parentNode.style.height=k+"px";b.overAllScaleX=a;b.overAllScaleY=d;b.adaption.scale=e;b.adaption.scaleX=a;b.adaption.scaleY=d;f=="width2"?b.adaption.marginLeft=b.adaption.marginRight=b.adaption.marginTop=b.adaption.marginBottom=0:(b.adaption.marginLeft=b.adaption.marginRight=
(document.body.offsetWidth/a-c.width)/2,b.adaption.marginTop=b.adaption.marginBottom=(document.body.offsetHeight/d-c.height)/2);f=="none_mobile"||f=="none_pc"?(e=document.body.offsetHeight-c.height*d<0)?(b.adaption.marginTop=b.adaption.marginBottom=0,w.parentNode.style.marginTop="0",w.parentNode.style.marginBottom="0"):(w.parentNode.style.marginTop="auto",w.parentNode.style.marginBottom="auto"):f=="width2"?(w.parentNode.style.marginTop="0",w.parentNode.style.marginBottom="0"):(e=document.body.offsetHeight-
c.height*d<0)?(w.parentNode.style.marginTop=-(c.height*d-document.body.offsetHeight)/2+"px",w.parentNode.style.marginBottom="0",w.parentNode.style.height="auto"):(w.parentNode.style.marginTop="auto",w.parentNode.style.marginBottom="auto",w.parentNode.style.height=k+"px");f=="none_pc"?document.body.offsetWidth-c.width*a<0?(b.adaption.marginLeft=b.adaption.marginRight=0,w.parentNode.style.marginLeft="0"):w.parentNode.style.marginLeft="auto":(e=document.body.offsetWidth-c.width*a<0)?(w.parentNode.style.marginLeft=
-(c.width*a-document.body.offsetWidth)/2+"px",w.parentNode.style.marginRight="0",w.parentNode.style.width="auto"):(w.parentNode.style.marginLeft="auto",w.parentNode.style.marginRight="auto",w.parentNode.style.width=i+"px");w.m_transform(null,null,null,a,d,0,0)}u.call(b,"resize",b.adaption)};z();Mugeda.textAsFlexbox&&(b.insertRule(".flex.middle","-webkit-box-align: center;-moz-box-align: center;-ms-flex-align: center;-webkit-justify-content: center;-moz-justify-content: center;justify-content: center;-webkit-box-pack: center;-moz-box-pack: center;-ms-flex-pack: center;-webkit-align-items: center;-moz-align-items: center;align-items: center;"),
b.insertRule(".flex","display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -moz-flex; display: -ms-flexbox; display: flex;"),b.insertRule(".flex.top","-webkit-box-align: start;-moz-box-align: start;-ms-flex-align: start;-webkit-justify-content: start;-moz-justify-content: start;justify-content: flex-start;-webkit-box-pack: start;-moz-box-pack: start;-ms-flex-pack: start;-webkit-align-items: flex-start;-moz-align-items: flex-start;align-items: flex-start;"),b.insertRule(".flex.bottom",
"-webkit-box-align: end;-moz-box-align: end;-ms-flex-align: end;-webkit-justify-content: end;-moz-justify-content: end;justify-content: flex-end;-webkit-box-pack: end;-moz-box-pack: end;-ms-flex-pack: end;-webkit-align-items: flex-end;-moz-align-items: flex-end;align-items: flex-end;"));b.updateRuleCached();b.loadProcess="script";if(b.aniData.sL)if(Mugeda.previewMode){a=Math.random();if(/buildno=(.*)\&?/.test(location.search))a=RegExp.$1;if(b.aniData.sL.extra&&b.aniData.sL.extra.length)for(x=0;x<
b.aniData.sL.extra.length;x++)F=b.aniData.sL.extra[x],F.indexOf("://")>-1?b.loadImage("script",b.aniData.sL.extra[x]):b.loadImage("script",b.resDir+b.aniData.sL.extra[x]);b.aniData.sL.cardCommon&&b.loadImage("script","/mugeda_client_utils/js/card_common.js?buildno="+a);(b.aniData.sL.mugedaPage||b.aniData.sL.mugedaPageAuto)&&b.loadImage("script","/mugeda_client_utils/js/mugeda_page.js?buildno="+a)}else{b.aniData.sL.jquery&&b.loadImage("script",b.resDir+"jquery-1.10.2.min.js");b.aniData.sL.socketio&&
(b.loadImage("script",b.resDir+"socket.io.1.9.16.min.js"),b.loadImage("script",b.resDir+"mugeda_connection.js"));b.aniData.sL.box2d&&b.loadImage("script",b.resDir+"Box2dWeb-2.1.a.3.min.js");b.aniData.sL.qrcode&&(b.loadImage("script",b.resDir+"qrcode.min.js"),b.loadImage("script",b.resDir+"jquery.qrcode.min.js",1));if(b.aniData.sL.extra&&b.aniData.sL.extra.length)for(var x=0;x<b.aniData.sL.extra.length;x++){var F=b.aniData.sL.extra[x];F.indexOf("://")>-1?b.loadImage("script",b.aniData.sL.extra[x]):
b.loadImage("script",b.resDir+b.aniData.sL.extra[x])}a=_mrmcp.version!=null?_mrmcp.version:"";b.aniData.sL.cardCommon&&b.loadImage("script",b.resDir+"card_common"+a+".js");(b.aniData.sL.mugedaPage||b.aniData.sL.mugedaPageAuto)&&b.loadImage("script",b.resDir+"mugeda_page"+a+".js")}b.scriptFile&&b.loadImage("script",b.resDir+b.scriptFile,2);setTimeout(function(){b.checkCountDownRef(true,true)},0);var H=function(){if(b.scriptFile){if(b.script=Mugeda.script[b.aniData.crid],typeof b.script=="function")b.script(b),
b.scriptExeced=true}else if(b.aniData.script)(function(a){eval(a.aniData.script)})(b),Mugeda.customScript=b.aniData.script;var a=function(){--c._n<=0&&(delete b.evt,b.afterLoadScriptProcess())},c={_n:0,goOnLoad:function(){c.stopLoad=false}};Object.defineProperty(c,"stopLoad",{set:function(a){a?c._n++:c._n--},get:function(){return c._n>0}});b.evt=c;b.scriptLoaded=true;u.call(b,"scriptReady",c);c.stopLoad?c.goOnLoad=a:a();b.loadProcess="image"};b.checkCountDownRef=function(a,c){function d(){for(var a in b.paramUpdatePool){var c=
b.paramUpdatePool[a];c.object.style.cssText+=c.text}b.paramUpdatePool={};a=function(){--f._n<=0&&(delete b.evt,b.loadOver.call(b),b.setupTimer())};var f={_n:0,goOnLoad:function(){f.stopLoad=false}};Object.defineProperty(f,"stopLoad",{set:function(a){a?f._n++:f._n--},get:function(){return f._n>0}});b.evt=f;u.call(b,"imageReady",f);f.stopLoad?f.goOnLoad=a:a();b.loadProcess="loaded"}a||--b.countDownRef;if(b.countDownRef==0)for(key in b.loadProcess=="script"&&!b.scriptLoaded?c?setTimeout(H,10):H():b.loadProcess==
"image"&&b.scriptLoaded&&(c?setTimeout(d,10):d()),b.loadNumBySource)b.loadNumBySource[key]===0&&(u.call(b,"cacheupdated",key),b.loadNumBySource[key]--);this.zoneLoadCallback&&this.zoneLoadCallback(this.zoneLoadTotal==0?1:(this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal);return b.countDownRef};b.getCacheStatus=function(a){return b.loadNumBySource?b.loadNumBySource[a]:void 0};b.afterLoadScriptProcess=function(){if(c.action=="link"&&c.url&&c.url.length){var a=function(){MugedaMraid.openLink(c.url,
c.urlTarget)};this.dom.m_css("cursor","pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":j?"touchend":"mouseup",function(b){a();b.preventDefault();b.stopPropagation();return false})}c.action=="form"&&c.form&&c.form.length&&(a=function(){MugedaBehavior.popupForm(JSON.parse(c.form))},this.dom.m_css("cursor","pointer").m_event(j?"touchend":"mouseup",function(b){a();b.preventDefault();b.stopPropagation();return false}));var d=function(a){var c=c||[];(a=a.layers)&&a.m_operate(function(){var a=
this.units;a&&a.m_operate(function(){var a=this.objects;if(a){var f=function(){var a=this.type;a==2005?c.push(b.resDir+this.param.imageSrc):a==2021?c=c.concat(d(b.symbols[this.param.symbolId])):a==2014&&this.items.m_operate(function(){f.call(this)})};a.m_operate(function(){f.call(this)})}})});return c};b.symbols={};b.audioSym={};b.audioSymName={};b.videoSym={};b.videoSymName={};b.symbolsName={};b.aniData.symbols.m_operate(function(a){if(a.type===2)b.audioSym[a.id]=b.resDir+a.url,b.audioSymName[a.name]=
b.resDir+a.url;else{a.type===3&&(b.videoSym[a.id]=b.resDir+a.url,b.videoSymName[a.id]=b.resDir+a.url);b.symbols[a.id]=a;b.symbolsName[a.name]=a;var c=99999999,f=-c,e=c,m=-c;a.layers.m_operate(function(a){a.units.m_operate(function(a){a.objects.m_operate(function(a){a=a.param;c=Math.min(c,a.left);f=Math.max(f,a.right);e=Math.min(e,a.top);m=Math.max(m,a.bottom)})})});a.bound={left:c,right:f,top:e,bottom:m,width:f-c,height:m-e};a.zoneCached=false;a.imageList=a.imageList||d(a);var i={guid:Mugeda.guidGen(),
type:2021,param:{name:"",fillInfo:{fillStyle:0,fillImage:"",fillColors:[{p:0,r:144,g:200,b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:a.bound.width,rawHeight:a.bound.height,symbolId:a.id,offsetX:(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,offsetY:(a.bound.top+a.bound.bottom-a.ch-a.bound.height)/2,rotateCenterX:a.bound.width/2,rotateCenterY:a.bound.height/2,strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-a.bound.width,right:0,top:0,bottom:a.bound.height,
scaleX:1,scaleY:1,rotate:0,lineWidth:1,alpha:1,strokeColor:"#0683ff",startX:0,startY:0,endX:a.bound.width,endY:a.bound.height,width:a.bound.width,height:a.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},i=new y(i,null),k={};k.dom=document.createElement("div");k.objectHash={};k.offset={x:a.cw/2+(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,y:a.ch/2+(a.bound.top+a.bound.bottom-a.ch-a.bound.height)/2};i.currentScene=k;i.initAndGetDom(k.dom,null);a.cachedInstance=i}});b.scene=
new s("_main",c,true,0,{x:0,y:0},h,false,null,null);b.scene.initAndGetDom();b.updateRuleCached();if(c.action==="behavior"&&c.behavior)b.dom.object=b.dom.object||b,b.handleBehavior(c.behavior,b.dom,b.id,b.scene);for(var f in b.scene.unitHash)b.scene.unitHash[f]instanceof v&&b.scene.unitHash[f].updateUnitVisibility(false);f=false;for(var e in b.imageCache)if(b.imageCache.hasOwnProperty(e)&&!b.imageCache[e].duringBuilding){var k={noCache:false};u.call(b,"beforeLoadImage",e,b.imageCache[e],k);if(!k.noCache){var p=
new Image;p.src=e;p.url=e;f=true;b.countDownRef++;b.maxNum=b.countDownRef;p.m_event("load",function(){b.imageCache[this.url].loaded=true;b.updateLoading(b.maxNum-b.countDownRef+1,b.maxNum);var a=this.url;b.imageCache[this.url].dom.m_operate(function(){this.src=a});b.checkCountDownRef()}).m_event("error",function(){b.updateLoading(b.maxNum-b.countDownRef+1,b.maxNum);b.checkCountDownRef();console.log("Error when loading image: "+p.src)})}}b.loadImageDecided=true;!f&&b.countDownRef==0&&setTimeout(function(){b.checkCountDownRef(true)},
10);b.playTriggered=true;z();window.addEventListener("resize",z);b.zoneCachedMode?b.cacheZone(b.zoneStart,b.zoneEnd,b.zoneSymbolList):b.checkCountDownRef(true)};b.setupTimer=function(){if(!b.timerSetted){var a;if(Mugeda.FPSMeter){var c=document.createElement("div");c.style.cssText+="position: absolute; left: 0; right: 0; background:black; color:red; z-index:999999; width:2em;";a=function(a){c.innerHTML=a.toString()};this.dom.appendChild(c);setInterval(function(){Mugeda.FPSMeter&&a(b.fpsFrame);b.fpsFrame=
0},1E3)}b.fpsFrame=0;b.timerSetted=true;b.lastFrameTime=d.getTime();b.nextRenderTime=b.lastFrameTime+b.frameTime;b.timeDuring=0;b.loadProcessHandle?b.loadProcessHandle.remove():b.dom.removeChild(b.loadingDiv);if(Mugeda.enablePulse&&Mugeda.pulse==null){b.insertRule("@"+d.css3Per+"keyframes MugedaPulse","from {"+d.css3Per+"transform: translate(-100px,0px);}to {"+d.css3Per+"transform: translate(-99px,0px);}");b.insertRule(".MugedaStamp","margin-top:-1em;");Mugeda.pulse=d("<div>").m_addClass("MugedaStamp");
var f=document.getElementsByTagName("body")[0];f.insertBefore(Mugeda.pulse,f.firstChild);Mugeda.pulse.innerHTML="Mugeda";Mugeda.pulse.style[d.css3PerH+"Animation"]="MugedaPulse 1s infinite"}(f=b.dom.m_attr("onRenderReady"))&&eval(f);u.call(b,"renderReady");var e=function(){if(!b.stopRedraw){b.fpsFrame++;var a=d.getTime();if(Mugeda.flexibleFrameRate){var c=a-b.lastFrameTime;if(c>b.frameTime)c=b.frameTime;b.timeDuring=c}for(;I(b.scene,true););if(!(c=B.old)){var f;a:{for(f in b.paramUpdatePool){f=false;
break a}f=true}c=!f}if(c){Mugeda.pulse&&(Mugeda.pulse.style[d.css3PerH+"AnimationPlayState"]="running");B.old&&p();for(var m in b.paramUpdatePool)f=b.paramUpdatePool[m],f.object.style.cssText+=f.text;b.paramUpdatePool={};Mugeda.pulse&&(Mugeda.pulse.style[d.css3PerH+"AnimationPlayState"]="paused")}m=d.getTime();if(Mugeda.flexibleFrameRate)b.lastFrameTime=a,b.timeoutHandle=setTimeout(e,Math.max(40-(m-a),0));else{b.nextRenderTime+=b.frameTime;if(m>b.nextRenderTime)b.nextRenderTime=m;b.timeoutHandle=
setTimeout(e,b.nextRenderTime-m)}}};b.timeoutHandle=setTimeout(e,0)}};typeof MugedaBehavior!="undefined"&&MugedaBehavior.processCloseButton&&MugedaBehavior.processCloseButton();var I=function(a){if(a!=null){if(a.currentId==null||a.gotoFlag)a.currentId=a.nextId,a.gotoFlag=false;if(a.pauseFlag&&Mugeda.flexibleFrameRate)a.currentId=Math.floor(a.currentId),a.nextId=a.currentId,a.pauseFlag=false;for(var c=a.currentId,d=[],f=Math.floor(c),e=a.cachedAudio?a.cachedAudio[f]||[]:[],m=a.playingAudio||[],g={},
i=0;i<e.length;i++){var k=e[i];m[k.hash]&&delete m[k.hash];if(k.audio.playStatus!=1)k.audio.play(),k.audio.playStatus=1;g[k.hash]=k}for(hash in m)if(i=m[hash],i.audio)i=i.audio,i.pause(),i.playStatus=0,i.currentTime=0,i.playStatus=0;a.playingAudio=g;g=a.cachedVisibility[f]||[];m={};for(i=0;i<g.length;i++){if(g[i].userParam.visible!==false){if(a.lastRenderList[g[i].id])a.lastRenderList[g[i].id]=false;else{Mugeda.nonDisplay?g[i].show():g[i].dom.m_css("display",g[i].dom.displayType!=null?g[i].dom.displayType:
"block");e=g[i].unit?g[i].unit.scrollTexts||[]:[];for(k=0;k<e.length;k++){var h=e[k];h.data.waitCount=0;h=h.dom.childNodes[0].childNodes[0];h.scrollTop=0}}m[g[i].id]=g[i]}if(!B[g[i].id]&&a.lastDrawId!=c&&g[i].unit&&(g[i].unit.data.keyframes.length>1||g[i].unit.data.pg)&&g[i].unit.data.objects.length==1){if(g[i].unit.data.pg&&g[i].data.type==2010){e=g[i].data;if(!e.originText)e.originText=unescape(e.param.textContent);k=e.originText;h=Math.ceil(k.length*((c-g[i].unit.data.frameStart)/g[i].unit.data.frameCount));
e.param.textContent=escape(k.substr(0,h))}else if(a.unitHash[g[i].unit.id].cachedFrame[c])k=a.unitHash[g[i].unit.id].cachedFrame[c],e=g[i].data.param,e.rawWidth=k.rawWidth,e.rawHeight=k.rawHeight,e.width=k.width,e.height=k.height,e.rotateCenterX=k.rotateCenterX,e.rotateCenterY=k.rotateCenterY,e.left=k.left,e.top=k.top,e.rotate=k.rotate,e.alpha=k.alpha,e.behaviorObj=k.behaviorObj,e.action=k.action;else if((e=TimelineUnit.getKeyframe(g[i].unit.data,c))?Param.exchange(e.param,g[i].data.param,true):(e=
TimelineUnit.getTweenParam(g[i].unit.data,c))&&Param.exchange(e,g[i].data.param,true),!Mugeda.flexibleFrameRate)k=g[i].data.param,a.unitHash[g[i].unit.id].cachedFrame[c]={rawWidth:k.rawWidth,rawHeight:k.rawHeight,width:k.width,height:k.height,rotateCenterX:k.rotateCenterX,rotateCenterY:k.rotateCenterY,left:k.left,top:k.top,rotate:k.rotate,alpha:k.alpha,behaviorObj:k.behaviorObj,action:k.action};d.push(g[i])}if(g[i].symbolList)for(e=0;e<g[i].symbolList.length;e++)if(k=I(b.sceneHash[g[i].symbolList[e]]),
typeof k=="string")return k;else d=d.concat(k);var j=function(c){var d=c.data;if(d.type==2014)for(var f=c.group.objectList.length,e=0;e<f;e++)j(c.group.objectList[e]);f=d.param.behaviorObj||d.param.behavior;if(d.param.action=="behavior"&&f)c.dom=c.dom||c,b.handleBehavior(f,c.dom,c.id,a,c.unit)};a.lastDrawId!=c&&j(g[i]);if(g[i].data.param.drag>0&&(g[i].realtimeUpdate=true,e=g[i].dom,!e.dragHooked))e.dragHooked=true,e.dragInfo={start:{},end:{}},k=isMobile(),e.addEventListener(k?"touchstart":"mousedown",
function(a){a.preventDefault();this.dragCaptured=true;this.dragInfo.initX=this.object.left;this.dragInfo.initY=this.object.top;var b=a.changedTouches?a.changedTouches[0]:null;this.dragInfo.start.x=b?b.pageX:a.pageX;this.dragInfo.start.y=b?b.pageY:a.pageY},true),e.addEventListener(k?"touchmove":"mousemove",function(a){if(this.dragCaptured){a.preventDefault();var c=a.changedTouches?a.changedTouches[0]:null;this.dragInfo.end.x=c?c.pageX:a.pageX;this.dragInfo.end.y=c?c.pageY:a.pageY;a=this.dragInfo.initX+
(this.dragInfo.end.x-this.dragInfo.start.x);c=this.dragInfo.initY+(this.dragInfo.end.y-this.dragInfo.start.y);a<0&&a+this.object.width<b.width?a=Math.min(0,b.width-this.object.width):a>0&&a+this.object.width>b.width&&(a=Math.max(0,b.width-this.object.width));c<0&&c+this.object.height<b.height?c=Math.min(0,b.height-this.object.height):c>0&&c+this.object.height>b.height&&(c=Math.max(0,b.height-this.object.height));var d=this.object.data.param.drag;if(d==1||d==3)this.object.left=a;if(d==2||d==3)this.object.top=
c}},true),e.addEventListener(k?"touchend":"mouseup",function(a){a.preventDefault();this.dragCaptured=false},true);e=g[i].unit?g[i].unit.scrollTexts||[]:[];for(k=0;k<e.length;k++)h=e[k],h.data.waitCount++,h.data.waitCount>24&&(h=h.dom.childNodes[0].childNodes[0],h.scrollTop+=1)}var p=a.getPageIndexByFrameId(c),i=false;p!=null&&p!=a.currentPageIndex&&(i=true);if(i){var s=[],o;for(o in a.lastRenderList)a.lastRenderList[o]&&s.push(a.lastRenderList[o]);a.pageDom[p].m_css("display","block");o=function(){a.pageDom[a.currentPageIndex]&&
a.pageDom[a.currentPageIndex].m_css("display","none");s.forEach(function(a){Mugeda.nonDisplay?a.hide():a.dom.m_css("display","none")});var b=a.currentPageIndex;a.currentPageIndex=p;a.playing=a.beforeSwitchStatus;a.beforeSwitchStatus=null;u.call(a,"afterSwitchPage",b,p);a._beforeSwitchPageFired=false};i=u.call(a,"beforeSwitchPage",p,o);if(a.beforeSwitchStatus==null)a.beforeSwitchStatus=a.playing;a.playing=false;i.indexOf(false)===-1&&o()}else for(o in a.lastRenderList)a.lastRenderList[o]&&(Mugeda.nonDisplay?
a.lastRenderList[o].hide():a.lastRenderList[o].dom.m_css("display","none"));a.lastRenderList=m;u.call(a,"enterframe");if(a.playing&&!a.gotoFlag)Mugeda.flexibleFrameRate?a.nextId=a.currentId+b.timeDuring/b.frameTime:a.nextId++;for(;a.frameout.length&&a.frameout[0].time==0;)o=a.frameout[0].fun,a.frameout.splice(0,1),o.call(a);a.frameout.length&&a.frameout[0].time--;if(a.currentSegment&&a.currentSegment.from!=void 0)o=a.currentSegment,a.nextId>o.to&&(o.isLoop?a.gotoAndPlay(a.currentSegment.from):(a.gotoAndPause(o.to),
a.lastDrawId!=c&&u.call(a,"segmentend")));else if(a.nextId>=a.length)(a.id=="_main"||a.id.indexOf("_page")===0)&&!b.aniData.loop?a.nextId=a.length-1:a.looped===false?a.nextId=a.length-1:(a.nextId=0,showAnimation=false);a.currentId=a.nextId;a.lastDrawId=c;if(a.pauseFlag&&Mugeda.flexibleFrameRate&&c!=f)return"inval";if(a.id!="_main")return d;else{for(i=0;i<d.length;i++)d[i].updateObjectParam();return null}}};e.prototype.createInstanceOfSymbol=function(a,c){var d=b.symbolsName[a],f=b.audioSymName[a],
e=b.videoSymName[a];if(d)return d={guid:Mugeda.guidGen(),type:2021,param:{name:c,fillInfo:{fillStyle:0,fillImage:"",fillColors:[{p:0,r:144,g:200,b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:d.bound.width,rawHeight:d.bound.height,symbolId:d.id,cw:d.cw,ch:d.ch,boundLeft:d.bound.left,boundTop:d.bound.top,offsetX:(d.bound.left+d.bound.right-d.cw-d.bound.width)/2,offsetY:(d.bound.top+d.bound.bottom-d.ch-d.bound.height)/2,rotateCenterX:d.bound.width/2,rotateCenterY:d.bound.height/2,
strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-d.bound.width,right:0,top:0,bottom:d.bound.height,scaleX:1,scaleY:1,rotate:0,lineWidth:1,alpha:1,strokeColor:"#0683ff",startX:0,startY:0,endX:d.bound.width,endY:d.bound.height,width:d.bound.width,height:d.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},new y(d,null);else if(f)return k(f);else if(e)return t(e)};e.prototype.unloadAnimation=function(){this.stopRedraw=true;this.dom&&this.dom.parentNode&&this.dom.parentNode.removeChild(this.dom);
for(var a in MugedaCss3.stage)MugedaCss3.stage[a]==this&&delete MugedaCss3.stage[a];Mugeda.scene=null;a=this.aniData.crid;Mugeda.scriptCounter[a]&&Mugeda.scriptCounter[a]--;Mugeda.scriptCounter[a]==0&&delete Mugeda.script[a]}}};e.prototype.checkLoad=function(a){a&&--this.imageNum;this.zoneLoadCallback&&this.zoneLoadCallback(this.zoneLoadTotal==0?1:(this.zoneLoadTotal-this.imageNum)/this.zoneLoadTotal);this.imageNum==0&&(this.loadOver.call(this),this.setupTimer())};e.prototype.updateLoading=function(a,
c){this.loadProcessHandle?this.loadProcessHandle.update(a,c):this.loadingDiv.innerHTML="Loading..."+a+"/"+c;u.call(this,"loadProcess",a,c)};e.prototype.loadAudio=function(a){e.prototype.loadImage("audio",a)};e.prototype.loadImage=function(a,c,d){d==null&&(d=0);var b=this;b.countDownRef=b.countDownRef||0;if(a=="dom_back"){var d=c.dom,e=c.url,a=c.source,h=c.duringBuilding&&c.unit||false,j=c.cacheZone||false;if(b.imageCache[e]){if(typeof a!="undefined"&&!b.imageCache[e].source)b.imageCache[e].source=
a;if(b.imageCache[e].loaded){if(d)d.src=e;return false}else if(j){c=b.imageCache[e];if(b.imageCache[e].loading)return false;l=new Image;l.src=e;l.url=e;l.cacheObject=c;b.imageCache[e].loaded=true;b.countDownRef++;b.maxNum=b.countDownRef;l.m_event("load",function(){this.cacheObject&&this.cacheObject.source&&b.loadNumBySource[this.cacheObject.source]--;b.checkCountDownRef();b.loadProcess=="image"&&b.updateLoading(b.maxNum-b.countDownRef+1,b.maxNum);b.imageCache[this.url].dom.m_operate(function(){this.src=
e})}).m_event("error",function(){console.log("Error when loading image: "+l.src);b.loadProcess=="image"&&b.updateLoading(b.maxNum-b.countDownRef+1,b.maxNum);this.cacheObject&&this.cacheObject.source&&b.loadNumBySource[this.cacheObject.source]--;b.checkCountDownRef()});return b.imageCache[e].loading=true}else return b.imageCache[e].dom.push(d),h&&c.scene&&c.scene.id=="_main"&&c.unit&&(c.unit.imageList[e]=b.imageCache[e]),false}else if(h)return b.imageCache[e]={image:null,url:e,source:a,dom:[d],loaded:false,
duringBuilding:true},c.scene&&c.scene.id=="_main"&&c.unit&&(c.unit.imageList[e]=b.imageCache[e]),false;else if(b.imageCache[e]={image:l,dom:[d],source:a,loaded:false},b.loadImageDecided){var l=new Image;l.src=e;l.url=e;l.m_event("load",function(){b.imageCache[this.url].loaded=true;b.updateLoading(b.maxNum-b.countDownRef+1,b.maxNum);var a=this.url;b.imageCache[this.url].dom.m_operate(function(){this.src=a})}).m_event("error",function(){console.log("Error when loading image: "+l.src)})}}else if(a==
"script"){b.countDownRef++;b.maxNum=b.countDownRef;for(a=b.scriptList.length;a<d;a++)b.scriptList[a]=[];b.scriptList[d]=b.scriptList[d]||[];b.scriptList[d].push(c);if(typeof v!="undefined")return Mugeda.loadJs(c);var v=-1;if(!b.scriptLoadTimer)b.scriptLoadTimer=setTimeout(function(){var a=function(c){if(!(c>=b.scriptList.length)){var d=b.scriptList[c];d||a(++c);for(var e=d.length,f=0;f<d.length;f++)Mugeda.loadJs(d[f],function(){b.updateLoading(b.maxNum-b.countDownRef+1,b.maxNum);b.checkCountDownRef();
--e==0&&a(++c)},function(){console.log("Error when loading user script");b.updateLoading(b.maxNum-b.countDownRef+1,b.maxNum);b.checkCountDownRef();--e==0&&a(++c)},b.aniData.crid);d.length==0&&a(++c)}};a(++v)},0)}else a="audio"};e.prototype.cacheZone=function(a,c,d,b){if(c==null||c<a)c=a;a<0&&(a=0);var e=this;if(!e.cacheStatus)e.cacheStatus={};if(e.scene){a++;c++;if(c>e.scene.length)c=e.scene.length;d==null&&(d=[]);e.zoneCachedMode=true;e.zoneLoadCallback=b||function(){};var h=d.skipLayer||[],j=d.skipFrame||
[],l=d.useScene||e.scene;d.forEach||(d=[]);var v={},q={},b=0;for(a-=1;a<c;a++)l.zoneCached[a]||j.indexOf(a)!=-1||((l.frameUnitHash[a]||[]).m_operate(function(){if(!(this.zoneCached||h.indexOf(this.layer.data.name)!=-1)){this.symbolList.m_operate(function(){e.symbols[this.toString()]&&(v[this.toString()]=e.symbols[this.toString()])});var a=this.imageList;for(p in a)a[p].loaded==false&&(q[p]=a[p]);this.zoneCached=true}}),l.zoneCached[a]=true);d.m_operate(function(){var a=this.toString();v[e.symbolsName[a].id]=
e.symbolsName[a]});if(!e.loadNumBySource)e.loadNumBySource={};for(var u in v){var t=v[u];e.loadNumBySource[t.name]=0;if(t.zoneCached==false)t.imageList.m_operate(function(){var a=this.toString();q[a]||(q[a]={dom:[],url:a,source:t.name})}),t.zoneCached=true}for(var p in q)c=q[p],c.url&&e.loadImage("dom_back",{url:p,cacheZone:true,dom:[],source:c.source})&&(c=c.source||"_main",e.loadNumBySource[c]===void 0?e.loadNumBySource[c]=1:e.loadNumBySource[c]++,b++);e.zoneLoadTotal=b;if(b==0){var o=this.zoneLoadTotal==
0?1:(this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal,o=o||1;o==1?setTimeout(function(){e.zoneLoadCallback(o)},0):e.zoneLoadCallback(o)}}else e.zoneCachedMode=true,e.zoneStart=a,e.zoneEnd=c,e.zoneSymbolList=d};var t=function(a){var c=a.className,d=c.indexOf("guid");return d>-1?(a=c.indexOf(" ",d),a==-1?c.substr(d):c.substr(d,a-d)):(c="guid_"+Mugeda.guidGen(),a.m_addClass(c),c)};e.prototype.insertRuleCached=function(a,c){if(this.cachedRule){if(this.cachedRule.push({obj:a,cssText:c}),!this.waitToupdateRuleCached){this.waitToupdateRuleCached=
true;var d=this;setTimeout(function(){d.updateRuleCached()},0)}}else this.insertRule("."+t(a),c)};e.prototype.updateRuleCached=function(){for(var a=0;a<this.cachedRule.length;a++){var c=this.cachedRule[a];this.insertRule("."+t(c.obj),c.cssText)}this.cachedRule=[];delete this.waitToupdateRuleCached};e.prototype.insertRule=function(a,c){var d=this.externalStylesheet,b=this.indexedStylesheet;if(b[a]&&b[a].style)b[a].style.cssText+=c;else{var e=0,h=d.rules?d.rules.length:d.cssRules.length;d.insertRule?
e=d.insertRule(a+"{"+c+"}",h):d.addRule&&(e=d.addRule(a,c,h));b[a]=d.rules?d.rules[e]:d.cssRules[e]}};e.prototype.handleBehavior=function(a,c,d,b,e){var h=this;(typeof a=="string"?JSON.parse(a):a).m_operate(function(a,f){var l=null;a.unit=e?e.data||{}:{};a.param=a.param||{};a.param.thisAni=h;var q=a.param.scope=="symbol"?b:h.scene;if(a.type=="play")l=function(){q.play.call(q)};else if(a.type=="pause")l=function(){q.pause.call(q)};else if(a.type=="gotoAndPlay")var u=parseInt(a.param.frame_number),
t=a.param.frame_name,l=function(){var a=null;if(isNaN(u)){if(a=q.getFrameId(t),q.pages){var b=q.pages[q.currentPageIndex],c=b.startFrame,b=b.length;a<c?a=c:a>c+b-1&&(a=c+b-1)}}else if(a=u-1,q.pages)b=q.pages[q.currentPageIndex],c=b.startFrame,b=b.length,a<0?a=0:a>b-1&&(a=b-1),a+=c;q.gotoAndPlay.call(q,a)};else if(a.type=="gotoAndStop"||a.type=="gotoAndPause")u=parseInt(a.param.frame_number),t=a.param.frame_name,l=function(){var a=null;if(isNaN(u)){if(a=q.getFrameId(t),q.pages){var b=q.pages[q.currentPageIndex],
c=b.startFrame,b=b.length;a<c?a=c:a>c+b-1&&(a=c+b-1)}}else if(a=u-1,q.pages)b=q.pages[q.currentPageIndex],c=b.startFrame,b=b.length,a<0?a=0:a>b-1&&(a=b-1),a+=c;q.gotoAndPause.call(q,a)};else if(a.type=="next")parseInt(a.param.frame_number),l=function(){q.gotoAndPause.call(q,Math.min(q.length,q.currentId+0+1))};else if(a.type=="previous")parseInt(a.param.frame_number),l=function(){q.gotoAndPause.call(q,Math.max(1,q.currentId-2+1))};else if(a.type!="callback")if(a.type=="audio"){if(a.param.audio_id)a.param.audio_url=
h.audioSym[a.param.audio_id]}else a.type=="stopAllAudio"&&(l=function(){for(var a in h.audioList){var b=h.audioList[a];try{b.pause(),b.currentTime=0}catch(c){}}});if(a.event.indexOf("slide_")==0||a.event=="shake"||a.event.indexOf("touch_")==0)MugedaBehavior.setupMobileActions(c.object,a,l);else if(a.event=="click"){if(!q.clickEventAttached[d+"_"+f])c.style.cursor="pointer",c.m_event(j?"touchstart":"mousedown",function(a){a.target.clickCaptured=true;a.target.moved=false;var b=a.changedTouches?a.changedTouches[0]:
null;a.target.clickX=b?b.pageX:a.pageX;a.target.clickY=b?b.pageY:a.pageY;return false}),c.m_event(j?"touchmove":"mousemove",function(a){if(a.target.clickCaptured){var b=a.changedTouches?a.changedTouches[0]:null,c=b?b.pageY:a.pageY;if((b?b.pageX:a.pageX)!=a.target.clickX||c!=a.target.clickY)a.target.moved=true}return false}),c.m_event(j?"touchend":"mouseup",function(b){b.target.clickCaptured=false;if(b.target.moved)return false;MugedaBehavior.processAction(a,"click",true);l&&l.call();b.preventDefault();
b.stopPropagation();return false}),q.clickEventAttached[d+"_"+f]=true}else a.event=="appear"&&(l?l():MugedaBehavior.processAction(a,"appear",true))})};window.HTMLElement.prototype.m_attr=function(a,c){return typeof c!="undefined"?(this.setAttribute(a,c),this):this.getAttribute(a)};window.HTMLElement.prototype.m_addClass=function(a){if(a&&typeof a==="string")this.className=this.className?this.className+" "+a:a;return this};window.HTMLElement.prototype.m_removeClass=function(a){if(a&&typeof a==="string"&&
this.className)this.className=this.className.replace(RegExp("("+a+"\\s)|(\\s*"+a+")"),"");return this};window.HTMLElement.prototype.m_event=function(a,c,e){/(transition)|(other)/.test(a)&&(a=d.css3Per+(d.css3Per?a.substr(0,1).toUpperCase():a.substr(0,1))+a.substr(1));this.addEventListener(a,c,e||false);return this};var z={transform:d.css3Per+"transform",transition:d.css3Per+"transition",textStroke:d.css3Per+"textStroke",textFillColor:d.css3Per+"textFillColor","transform-origin":d.css3Per+"transform-origin",
"user-select":d.css3Per+"user-select"};window.HTMLElement.prototype.m_css=function(a,c,e){z[a]&&(a=z[a]);if(c!=null)if(e)if(c!==""){if(this.guid==null)this.guid=Mugeda.guidGen();e.paramUpdatePool[this.guid]==null&&(e.paramUpdatePool[this.guid]={object:this,text:""});e.paramUpdatePool[this.guid].text+=a+":"+c+";"}else this.style[a]=null;else a.indexOf("opacity")>-1||a.indexOf("tran")>-1||!Mugeda.nonDisplay&&a.indexOf("display")>-1||!Mugeda.nonDisplay&&a.indexOf("vertical")>-1?c!==""?this.style.cssText+=
a+":"+c+";":this.style[a]=null:c!==""?Mugeda.currentAni.insertRuleCached(this,a+":"+c+";"):this.style[a]=null;else return d.getCurrentStyle(this,a);return this};window.HTMLElement.prototype.m_width=function(a){if(a!=void 0)return this.m_css("width",a+"px")};window.HTMLElement.prototype.m_height=function(a){if(a!=void 0)return this.m_css("height",a+"px")};window.HTMLElement.prototype.m_transform=function(a,c,d,b,e,h,j){data={};a!=null&&(data.translateX=a.toString()+"px");c!=null&&(data.translateY=
c.toString()+"px");d!=null&&(data.rotate=d.toString()+"rad");b!=null&&(data.scaleX=b.toString());b!=null&&(data.scaleY=e.toString());Mugeda.threeDRendering&&(data.translateZ="0px");var a="",l;for(l in data)a+=l+"("+data[l]+") ";if(h!=null||j!=null)this.m_css("transform-origin",(Math.abs(h)<0.01?0:Math.floor(100*h)*0.01)+"px "+(Math.abs(j)<0.01?0:Math.floor(100*j)*0.01)+"px");return this.m_css("transform",a)};window.HTMLElement.prototype.m_append=function(a,c){a instanceof window.HTMLElement&&(c?this.insertBefore(a,
c):this.appendChild(a));return this};window.HTMLElement.prototype.m_appendTo=function(a){a instanceof window.HTMLElement&&a.appendChild(this);return this};window.HTMLElement.prototype.m_setCapture=function(a){MugedaCss3.captureObject={object:this,capture:a==void 0?true:a};return this};window.HTMLElement.prototype.m_releasecapture=function(){MugedaCss3.captureObject=null;return this};Array.prototype.m_operate=function(a,c){for(var d=c?this.length-1:0;c&&d>=0||!c&&d<this.length;c?d--:d++)if(a.call(this[d],
this[d],d)==false)break};String.prototype.m_trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};return d}}(window.MugedaCss3);
var MugedaCompress={keys:"Ac,action,fM,form,tt,title,wt,width,ht,height,cl,color,sm,symbols,ly,layers,vr,version,sC,scripts,zI,zoomInfo,pd,pid,tp,type,nm,name,un,units,lI,layerId,fS,frameStart,fC,frameCount,ad,animated,vb,visible,ob,objects,pm,param,fI,fillInfo,cv,curve,kf,keyframes,md,mode,tw,tween,hK,hashKey,ix,index,rW,rawWidth,rH,rawHeight,sI,symbolId,oX,offsetX,oY,offsetY,rX,rotateCenterX,rY,rotateCenterY,it,items,nI,nodeId,gP,guidPath,ph,path,gi,guid,sm,smooth,iX,innerX,iY,innerY,uX,outerX,uY,outerY,cX,centerX,cY,centerY,ed,edges,st,section,fZ,fontSize,fT,fontStyle,fW,fontWeight,fF,fontFamily,tA,textAlign,tC,textContent,tD,textDecoration,cR,cornerRadius,iS,imageSrc,lC,lineCap,lJ,LineJoin,fR,frameRate,iP,innerPercent,TA,trackAnchors,MT,mugedaTrackAnchors".split(","),unzip:function(a){if(!a)return a;
if(a.zip!=1)return HaniData.unzip(a);a=JSON.parse(JSON.stringify(a));a=MugedaCompress.unzipKey(a);delete a.zip;if(a.rate==void 0)a.rate=12;if(a.width==void 0)a.width=600;if(a.height==void 0)a.height=400;if(a.guid==void 0)a.guid="";if(a.title==void 0)a.title="";if(a.script==void 0)a.script="";if(a.loop==void 0)a.loop=true;if(a.useCamera==void 0)a.useCamera=false;if(a.symbols==void 0)a.symbols=[];if(a.symbols.length)for(var d=a.symbols,c=0;c<d.length;c++){var e=d[c];e.runtime=true;e.dirtyFlag=false;
MugedaCompress.unzipLayers(e.layers)}if(a.pages&&a.pages.length){d=a.pages;for(c=0;c<d.length;c++)e=d[c],e.runtime=true,e.dirtyFlag=false,MugedaCompress.unzipLayers(e.layers)}MugedaCompress.unzipZoomInfo(a);MugedaCompress.unzipLayers(a.layers);return a},unzipKey:function(a){for(var d,a=JSON.stringify(a),c=0;c<MugedaCompress.keys.length;c+=2)d=eval('/"'+MugedaCompress.keys[c]+'":/g'),a=a.replace(d,'"'+MugedaCompress.keys[c+1]+'":');return JSON.parse(a)},unzipZoomInfo:function(a){for(var d=[],c=a.zoomInfo.split(",")||
[],e=0;e<c.length;e+=4){var h=c[e];if(h.indexOf("i")==0){h=h.substr(1);e++;var j=c[e];j.indexOf("t")==0?(j=j.substr(1),e++):j=null;d[h]={offsetLeft:Number(c[e]),offsetTop:Number(c[e+1]),rotation:Number(c[e+2]),zoomLevel:Number(c[e+3])};if(j)d[h].tween=j}}a.zoomInfo=d},unzipLayers:function(a){for(var d=0;d<a.length;d++){var c=a[d];c.hide=false;c.lock=false;for(var c=c.units,e=0;e<c.length;e++){var h=c[e];h.animated&&MugedaCompress.unzipPath(h);for(var j=h.keyframes||[],l=0;l<j.length;l++)MugedaCompress.unzipParam(j[l].param);
if(h.visible==void 0)h.visible=true;MugedaCompress.unzipObjects(h.objects)}}},unzipPath:function(a){for(var d=a.path.split(","),c=[],e=d.shift(),h=d.shift(),j=0;j<d.length;j+=7)c.push({id:Number(d[j]),backwardX:Number(d[j+1]),backwardY:Number(d[j+2]),forwardX:Number(d[j+3]),forwardY:Number(d[j+4]),nodeX:Number(d[j+5]),nodeY:Number(d[j+6])});c.length?(a.pathLeft=Number(e),a.pathTop=Number(h),a.path=c):(delete a.path,delete a.pathLeft,delete a.pathTop)},unzipObjects:function(a){for(var d=0;d<a.length;d++){var c=
a[d];c.items&&c.items.length?MugedaCompress.unzipObjects(c.items):(c.id=0,c.name="",c.items=[],c.aryAnchors=[]);MugedaCompress.unzipCurve(c);MugedaCompress.unzipParam(c.param)}},unzipCurve:function(a){var d=a.curve;if(typeof d=="string"){a.curve={};var d=d.split(","),c=d.shift()==1;a.curve.closed=c;for(var c=[],e=0;e<d.length;e+=6)c.push({backwardX:Number(d[e]),backwardY:Number(d[e+1]),forwardX:Number(d[e+2]),forwardY:Number(d[e+3]),nodeX:Number(d[e+4]),nodeY:Number(d[e+5])});a.curve.points=c}},unzipParam:function(a){if(a.strokeType==
void 0)a.strokeType=0;if(a.frameRate==void 0)a.frameRate=12;if(a.lineCap==void 0)a.lineCap="round";if(a.lineJoin==void 0)a.lineJoin="round";for(var d=a.m.split(";"),c=0;c<d.length;c++){var e=d[c].substr(0,1),h=d[c].substr(1);switch(e){case "L":a.left=Number(h);break;case "R":a.right=Number(h);break;case "T":a.top=Number(h);break;case "B":a.bottom=Number(h);break;case "S":a.startX=Number(h);break;case "P":a.startY=Number(h);break;case "E":a.endX=Number(h);break;case "N":a.endY=Number(h);break;case "X":a.scaleX=
Number(h);break;case "Y":a.scaleY=Number(h);break;case "O":a.rotate=Number(h);break;case "W":a.lineWidth=Number(h);break;case "A":a.alpha=Number(h);break;case "C":a.strokeColor=h}}if(a.startX==void 0)a.startX=a.left;if(a.startY==void 0)a.startY=a.top;if(a.endX==void 0)a.endX=a.right;if(a.endY==void 0)a.endY=a.bottom;a.width=a.right-a.left;a.height=a.bottom-a.top;delete a.m;MugedaCompress.unzipFillInfo(a)},unzipFillInfo:function(a){if(a.fillInfo){for(var d=a.fillInfo.split(";"),c=Number(d[0]),e=d[1].split(","),
h=d[3],j=[],l=0;l<e.length;l+=5)j.push({p:Number(e[l]),r:Number(e[l+1]),g:Number(e[l+2]),b:Number(e[l+3]),a:Number(e[l+4])});c={fillStyle:c,fillImage:h,fillColors:j};d=d[2].split(",");d.length!=4&&(d=[0,0,0,0]);c.fillStartPos={x:Number(d[0]),y:Number(d[1])};c.fillEndPos={x:Number(d[2]),y:Number(d[3])};a.fillInfo=c}}},TimelineUnit={getKeyframe:function(a,d){var c=a.hashKey["key_"+d];c||(c=null);return c},getTweenParam:function(a,d){var c=a.keyframes.length,e=a.keyframes[0],h=null,j=null,l=0,A=-1;bezierInterpolate=
function(a,c,b,d,e,f){return Math.pow(c,3)*b+3*Math.pow(c,2)*a*d+3*c*Math.pow(a,2)*e+Math.pow(a,3)*f};var u=function(a,c,b){var d=1-b,e=a.nodeY,f=a.forwardY,h=c.backwardY,j=c.nodeY,a=bezierInterpolate(b,d,a.nodeX,a.forwardX,c.backwardX,c.nodeX),b=bezierInterpolate(b,d,e,f,h,j);return{x:a,y:b}};if(c>1&&!a.hashKey["key_"+d]){for(var t=1;t<c;t++){h=a.keyframes[t];if(h.id>d){A=t;break}e=h;l=t;h=null}if(h){c=Math.abs(h.id-e.id);j=d-e.id;c=TimelineUnit.getTweenFactors(c,e.tween);if(Mugeda.flexibleFrameRate){c.push(1);
var t=Math.floor(j),z=Math.ceil(j),f=c[t],c=c[z],c=z==t?c:(j-z)*(c-f)/(z-t)+c}else c=c[j];j={left:0,top:0,right:0,bottom:0,startX:0,startY:0,endX:0,endY:0,width:0,height:0,alpha:1,rotate:0,scaleX:1,scaleY:1,lineWidth:1,strokeType:0,strokeColor:"#0683ff",lineCap:"round",lineJoin:"round",fillInfo:{fillStyle:0,fillImage:"",fillStartPos:{x:32,y:10},fillEndPos:{x:80,y:100},fillColors:[{p:0,r:144,g:200,b:255,a:1},{p:0.8,r:255,g:144,b:200,a:1},{p:1,r:200,g:255,b:144,a:1}]}};Param.tweenParam(j,e.param,h.param,
c);if(a.pathMode>Hanimation.PATHMODE_DEFAULT&&l>=0&&A>=0)h=a.path,l=u(h[l],h[A],c),l.x=a.pathLeft+l.x-j.rotateCenterX,l.y=a.pathTop+l.y-j.rotateCenterY,j.startX=l.x,j.startY=l.y,j.endX=j.startX+j.width,j.endY=j.startY+j.height,j.left=j.startX,j.top=j.startY,j.right=j.endX,j.bottom=j.endY}}if(!j)j=e.param;return j},getTweenFactors:function(a,d){var c=[],e=new TWEEN.Tween({x:0});e.to({x:1},1E3);d||(d="Linear.EaseNone");for(var d=d.split("."),h=d.length,j=TWEEN.Easing;h;)j=j[d[d.length-h]],h--;e.easing(j);
for(h=0;h<a;h++)c[h]=e.getFactor(h/a);return c}},TWEEN=TWEEN||function(){var a,d,c,e,h=[];return{start:function(a){c=setInterval(this.update,1E3/(a||60))},stop:function(){clearInterval(c)},add:function(a){h.push(a)},getAll:function(){return h},removeAll:function(){h=[]},remove:function(c){a=h.indexOf(c);a!==-1&&h.splice(a,1)},update:function(){a=0;d=h.length;for(e=(new Date).getTime();a<d;)h[a].update(e)?a++:(h.splice(a,1),d--)}}}();
TWEEN.Tween=function(a){var d={},c={},e={},h=1E3,j=0,l=null,A=TWEEN.Easing.Linear.EaseNone,u=null,t=null,z=null;this.to=function(c,d){d!==null&&(h=d);for(var i in c)a[i]!==null&&(e[i]=c[i]);return this};this.start=function(){TWEEN.add(this);l=(new Date).getTime()+j;for(var f in e)a[f]!==null&&(d[f]=a[f],c[f]=e[f]-a[f]);return this};this.stop=function(){TWEEN.remove(this);return this};this.delay=function(a){j=a;return this};this.easing=function(a){A=a;return this};this.chain=function(a){u=a};this.onUpdate=
function(a){t=a;return this};this.onComplete=function(a){z=a;return this};this.getFactor=function(a){a=Math.min(1,Math.max(0,a));return A(a)};this.update=function(e){var j,i;if(e<l)return true;e=(e-l)/h;e=e>1?1:e;i=A(e);for(j in c)a[j]=d[j]+c[j]*i;t!==null&&t.call(a,i);return e==1?(z!==null&&z.call(a),u!==null&&u.start(),false):true}};TWEEN.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{},Step:{}};
TWEEN.Easing.Linear.EaseNone=function(a){return a};TWEEN.Easing.Quadratic.EaseIn=function(a){return a*a};TWEEN.Easing.Quadratic.EaseOut=function(a){return-a*(a-2)};TWEEN.Easing.Quadratic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a:-0.5*(--a*(a-2)-1)};TWEEN.Easing.Cubic.EaseIn=function(a){return a*a*a};TWEEN.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};TWEEN.Easing.Cubic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a:0.5*((a-=2)*a*a+2)};TWEEN.Easing.Quartic.EaseIn=function(a){return a*a*a*a};
TWEEN.Easing.Quartic.EaseOut=function(a){return-(--a*a*a*a-1)};TWEEN.Easing.Quartic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};TWEEN.Easing.Quintic.EaseIn=function(a){return a*a*a*a*a};TWEEN.Easing.Quintic.EaseOut=function(a){return(a-=1)*a*a*a*a+1};TWEEN.Easing.Quintic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};TWEEN.Easing.Sinusoidal.EaseIn=function(a){return-Math.cos(a*Math.PI/2)+1};
TWEEN.Easing.Sinusoidal.EaseOut=function(a){return Math.sin(a*Math.PI/2)};TWEEN.Easing.Sinusoidal.EaseInOut=function(a){return-0.5*(Math.cos(Math.PI*a)-1)};TWEEN.Easing.Exponential.EaseIn=function(a){return a==0?0:Math.pow(2,10*(a-1))};TWEEN.Easing.Exponential.EaseOut=function(a){return a==1?1:-Math.pow(2,-10*a)+1};TWEEN.Easing.Exponential.EaseInOut=function(a){return a==0?0:a==1?1:(a*=2)<1?0.5*Math.pow(2,10*(a-1)):0.5*(-Math.pow(2,-10*(a-1))+2)};
TWEEN.Easing.Circular.EaseIn=function(a){return-(Math.sqrt(1-a*a)-1)};TWEEN.Easing.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};TWEEN.Easing.Circular.EaseInOut=function(a){return(a/=0.5)<1?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};TWEEN.Easing.Elastic.EaseIn=function(a){var d,c=0.1,e=0.25;if(a==0)return 0;if(a==1)return 1;e||(e=0.3);!c||c<1?(c=1,d=e/4):d=e/(2*Math.PI)*Math.asin(1/c);return-(c*Math.pow(2,10*(a-=1))*Math.sin((a-d)*2*Math.PI/e))};
TWEEN.Easing.Elastic.EaseOut=function(a){var d,c=0.1,e=0.25;if(a==0)return 0;if(a==1)return 1;e||(e=0.3);!c||c<1?(c=1,d=e/4):d=e/(2*Math.PI)*Math.asin(1/c);return c*Math.pow(2,-10*a)*Math.sin((a-d)*2*Math.PI/e)+1};
TWEEN.Easing.Elastic.EaseInOut=function(a){var d,c=0.1,e=0.25;if(a==0)return 0;if(a==1)return 1;e||(e=0.3);!c||c<1?(c=1,d=e/4):d=e/(2*Math.PI)*Math.asin(1/c);return(a*=2)<1?-0.5*c*Math.pow(2,10*(a-=1))*Math.sin((a-d)*2*Math.PI/e):c*Math.pow(2,-10*(a-=1))*Math.sin((a-d)*2*Math.PI/e)*0.5+1};TWEEN.Easing.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};TWEEN.Easing.Back.EaseOut=function(a){return(a-=1)*a*(2.70158*a+1.70158)+1};
TWEEN.Easing.Back.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};TWEEN.Easing.Bounce.EaseIn=function(a){return 1-TWEEN.Easing.Bounce.EaseOut(1-a)};TWEEN.Easing.Bounce.EaseOut=function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};
TWEEN.Easing.Bounce.EaseInOut=function(a){return a<0.5?TWEEN.Easing.Bounce.EaseIn(a*2)*0.5:TWEEN.Easing.Bounce.EaseOut(a*2-1)*0.5+0.5};TWEEN.Easing.Step.EaseIn=function(){return 0};
Param={exchange:function(a,d,c){c?(c=a,a=d):c=d;a.startX=c.startX;a.startY=c.startY;a.endX=c.endX;a.endY=c.endY;a.left=c.left;a.right=c.right;a.top=c.top;a.bottom=c.bottom;a.width=c.width;a.height=c.height;a.alpha=c.alpha;a.scaleX=c.scaleX;a.scaleY=c.scaleY;a.rotate=c.rotate;a.rotateCenterX=c.rotateCenterX;a.rotateCenterY=c.rotateCenterY;a.customPivot=c.customPivot},tweenParam:function(a,d,c,e){a.startX=d.startX+e*(c.startX-d.startX);a.startY=d.startY+e*(c.startY-d.startY);a.endX=d.endX+e*(c.endX-
d.endX);a.endY=d.endY+e*(c.endY-d.endY);a.width=d.width+e*(c.width-d.width);a.height=d.height+e*(c.height-d.height);a.alpha=d.alpha+e*(c.alpha-d.alpha);a.scaleX=d.scaleX+e*(c.scaleX-d.scaleX);a.scaleY=d.scaleY+e*(c.scaleY-d.scaleY);a.rotate=d.rotate+e*(c.rotate-d.rotate);a.rotateCenterX=d.rotateCenterX+e*(c.rotateCenterX-d.rotateCenterX);a.rotateCenterY=d.rotateCenterY+e*(c.rotateCenterY-d.rotateCenterY);a.customPivot=true;if(d.fillInfo&&d.fillInfo&&(d.fillInfo.fillStyle==1||d.fillInfo.fillStyle==
2))a.fillInfo.fillStartPos.x=d.fillInfo.fillStartPos.x+e*(c.fillInfo.fillStartPos.x-d.fillInfo.fillStartPos.x),a.fillInfo.fillStartPos.y=d.fillInfo.fillStartPos.y+e*(c.fillInfo.fillStartPos.y-d.fillInfo.fillStartPos.y),a.fillInfo.fillEndPos.x=d.fillInfo.fillEndPos.x+e*(c.fillInfo.fillEndPos.x-d.fillInfo.fillEndPos.x),a.fillInfo.fillEndPos.y=d.fillInfo.fillEndPos.y+e*(c.fillInfo.fillEndPos.y-d.fillInfo.fillEndPos.y);a.left=a.startX;a.top=a.startY;a.right=a.startX+a.width;a.bottom=a.startY+a.height}};
Hanimation={PATHMODE_DEFAULT:0};
(function(){Mugeda.initCss3Player=function(){document.addEventListener("mousedown",MugedaCss3.handleCapture,true);document.addEventListener("mouseup",MugedaCss3.handleCapture,true);document.addEventListener("mouseover",MugedaCss3.handleCapture,true);document.addEventListener("mouseout",MugedaCss3.handleCapture,true);document.addEventListener("mousemove",MugedaCss3.handleCapture,true);Mugeda.loadJs=function(c,d,e,h){if(a(c))d&&d();else{var f=document.createElement("script");f.src=c;document.getElementsByTagName("head")[0].appendChild(f);
f.onload=f.onreadystatechange=function(){this.readyState&&this.readyState=="loading"||(h&&Mugeda.script.length&&(Mugeda.script[h]=Mugeda.script.splice(0,1)[0],Mugeda.scriptCounter[h]=Mugeda.scriptCounter[h]||0,Mugeda.scriptCounter[h]++),d&&(d(),d=function(){}))};f.onerror=function(){f.parentNode.removeChild(f);e()}}};var a=function(a){var c=document.getElementsByTagName("script"),d=false;for(e=0;e<c.length;e++)if(c[e].src&&c[e].src.indexOf(a)!=-1&&(c[e].readyState=="loaded"||c[e].readyState=="complete")){d=
true;break}return d};Mugeda.startAnimation=function(a,c,d,e,f,h){var i=navigator.userAgent.toLowerCase();Mugeda.isAndroid=i.indexOf("android")>-1;Mugeda.androidVersion=parseFloat(i.slice(i.indexOf("android")+8));var b=MugedaCss3.initAnimation(Mugeda.data[a],c,d,e,function(){f&&(MugedaCss3.stage[f]=b);h&&h(b)});Mugeda.scene=b;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript);return b};if(Mugeda.css3PlayerLoaded==void 0)for(var d=document.getElementsByClassName("MugedaStage"),
c=d.length,e=0;e<c;e++){var h=d[e],j=h.getAttribute("mugedaName"),l=MugedaCss3.initAnimation(Mugeda.data[j],h.m_attr("hasScript")=="true"?"actions_"+(j.substr(j.indexOf("_")+1)+".js"):"",h,h.m_attr("relDir")||"",function(){MugedaCss3.stage[j]=l;--c==0&&typeof Mugeda.script=="function"&&Mugeda.script()});Mugeda.scene=l;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript)}else if(Mugeda.css3PlayerLoaded=2,Mugeda.creationToBeLoad){for(e=0;e<Mugeda.creationToBeLoad.length;e++)Mugeda.creationToBeLoad[e].start();
Mugeda.creationToBeLoad=[]}}})();document&&document.getElementsByTagName&&document.getElementById&&document.body?Mugeda.initCss3Player():document.addEventListener("DOMContentLoaded",Mugeda.initCss3Player);
